// Grade 7: section 1.10 and chapter II (2.1–2.14), pages 34–74.
import { S, R, L } from './g7p1-helpers.mjs'

const EX = { fromExercise: true }
const ex = (note, more = {}) => ({ fromExercise: true, note, ...more })

export const C2 = {
  'c1-s10': {
    substances: [
      S('Cu', 'медь', 'simple', 'mentioned', 34, 'Вещества 1. Mедь 1. 2. Железо 1. 3. Стекло 1.', EX),
      S('Fe', 'железо', 'simple', 'mentioned', 34, 'Вещества 1. Mедь 1. 2. Железо 1. 3. Стекло 1.', EX),
      S(null, 'стекло', 'other', 'mentioned', 34, 'Вещества 1. Mедь 1. 2. Железо 1. 3. Стекло 1.', EX),
      S('CO2', 'углекислый газ', 'oxide', 'mentioned', 34, 'Объясните точную разницу между следующими веществами: A) углекислый газ и вода', EX),
      S('H2O', 'вода', 'oxide', 'mentioned', 34, 'A) углекислый газ и вода', EX),
      S(null, 'бензин', 'other', 'mentioned', 34, 'Б) бензин и уксус', EX),
      S('CH3COOH', 'уксус', 'organic', 'mentioned', 34, 'Б) бензин и уксус', ex('formula inferred (acetic acid solution)')),
      S('C12H22O11', 'сахар', 'organic', 'mentioned', 34, 'B) сахар и поваренная соль', ex('formula inferred (sucrose)')),
      S('NaCl', 'поваренная соль', 'salt', 'mentioned', 34, 'B) сахар и поваренная соль', EX),
      S('Al', 'алюминий', 'simple', 'mentioned', 34, 'Г) алюминий и медь', EX),
      S('Ca(OH)2', 'известковая вода', 'base', 'reagent', 34, 'помутнение известковой воды от углекислого газа', ex('formula inferred (solution of Ca(OH)2)')),
      S('Ag', 'серебро (серебряная ложка)', 'simple', 'mentioned', 34, 'потускнение серебряной ложки', EX),
      S('N2', 'азот', 'simple', 'mentioned', 35, 'Какие из веществ являются чистыми: морская вода, азот, кислород, воздух, гранит, молоко, сахар', EX),
      S('O2', 'кислород', 'simple', 'mentioned', 35, 'Какие из веществ являются чистыми: морская вода, азот, кислород, воздух, гранит, молоко, сахар', EX),
      S(null, 'гранит', 'other', 'mentioned', 35, 'морская вода, азот, кислород, воздух, гранит, молоко, сахар, варенье, железо', ex('rock (mixture)')),
    ],
    reactions: [
      R(null, 'Ca(OH)2 + CO2 → CaCO3↓ + H2O', 'exchange', 34, 'помутнение известковой воды от углекислого газа', ex('described in words (exercise: physical vs chemical phenomena); equation reconstructed')),
    ],
    labWorks: [],
    elementsMentioned: ['B', 'H', 'Mg', 'Li', 'C', 'Na'],
    notes: ['p36 chapter II opener: pictures captioned Бор, Водород, Магний, Литий, Углерод, Натрий (elements).'],
  },
  'c2-s01': {
    substances: [
      S('Cu', 'медь (медная проволока)', 'simple', 'mentioned', 37, 'Если кусок меди разбить на мелкие кусочки, он достигнет точки, в которой его уже нельзя разбить.'),
      S('CO2', 'углекислый газ', 'oxide', 'mentioned', 39, 'в углекислом газе один атом углерода соединяется с 2 атомами кислорода в соотношении 1:2'),
      S('NaCl', 'хлорид натрия', 'salt', 'mentioned', 39, 'Хлорид натрия содержит натрий и хлор, все атомы натрия одинаковы, все атомы хлора одинаковы.'),
      S('Cl2', 'хлор', 'simple', 'mentioned', 39, 'Хлор Бром Йод Вода Серная кислота Поваренная соль', { note: 'figure captions (molecule models); formula inferred' }),
      S('Br2', 'бром', 'simple', 'mentioned', 39, 'Хлор Бром Йод Вода Серная кислота Поваренная соль', { note: 'figure caption; formula inferred' }),
      S('I2', 'йод', 'simple', 'mentioned', 39, 'Хлор Бром Йод Вода Серная кислота Поваренная соль', { note: 'figure caption; formula inferred' }),
      S('H2O', 'вода', 'oxide', 'mentioned', 39, 'Хлор Бром Йод Вода Серная кислота Поваренная соль', { note: 'figure caption' }),
      S('H2SO4', 'серная кислота', 'acid', 'mentioned', 39, 'Хлор Бром Йод Вода Серная кислота Поваренная соль', { note: 'figure caption; formula inferred' }),
      S('C', 'графит (углерод)', 'simple', 'mentioned', 40, 'Предположим, что грифель карандаша сделан из чистого углерода, то есть из графита.'),
    ],
    reactions: [
      R(null, '2H2 + O2 → 2H2O', 'combination', 40, 'Показанная модель представляет собой образование молекулы воды из атомов водорода и кислорода.', ex('figure/model of water formation from hydrogen and oxygen atoms; equation reconstructed')),
    ],
    labWorks: [],
    elementsMentioned: ['Cu', 'Na', 'Cl', 'C', 'H', 'O'],
  },
  'c2-s02': {
    substances: [],
    reactions: [],
    labWorks: [],
    elementsMentioned: ['H', 'He', 'Li', 'Na', 'Cl'],
    notes: ['Atomic structure only (protons, neutrons, electrons); no substances.'],
  },
  'c2-s03': {
    substances: [
      S('=SiO2', 'оксид кремния', 'oxide', 'mentioned', 45, 'Большая его часть связана в виде оксидов, прежде всего оксида кремния (SiO2).'),
      S('Au', 'золото', 'simple', 'mentioned', 45, 'Металл Золото Символ Серебро Планета Солнце', { note: 'alchemy table of seven metals' }),
      S('Ag', 'серебро', 'simple', 'mentioned', 45, 'Металл Золото Символ Серебро Планета Солнце', { note: 'alchemy table of seven metals' }),
      S('Fe', 'железо', 'simple', 'mentioned', 45, 'Железо Марс Вторник', { note: 'alchemy table of seven metals' }),
      S('Hg', 'ртуть', 'simple', 'mentioned', 45, 'Ртуть Олово Меркурий Среда Юпитер Четверг', { note: 'alchemy table of seven metals' }),
      S('Sn', 'олово', 'simple', 'mentioned', 45, 'Ртуть Олово Меркурий Среда Юпитер Четверг', { note: 'alchemy table of seven metals' }),
      S('Cu', 'медь', 'simple', 'mentioned', 45, 'Медь Свинец Венера Пятница Сатурн Суббота', { note: 'alchemy table of seven metals' }),
      S('Pb', 'свинец', 'simple', 'mentioned', 45, 'Медь Свинец Венера Пятница Сатурн Суббота', { note: 'alchemy table of seven metals' }),
    ],
    reactions: [],
    labWorks: [],
    elementsMentioned: ['N', 'Al', 'H', 'O', 'K', 'C', 'Ca', 'Cl', 'Cu', 'B', 'F', 'S', 'Ag', 'Hg', 'Au', 'He', 'Mg', 'Na', 'Sn', 'Fe', 'Pb', 'Gd', 'Cm', 'Es', 'Fm', 'Md', 'No', 'Lr', 'Rf', 'Sg', 'Rg', 'Cn'],
  },
  'c2-s04': {
    substances: [
      S('Si', 'кремний', 'simple', 'mentioned', 47, 'Увеличенное изображение поверхности кремния', { note: 'figure caption' }),
    ],
    reactions: [],
    labWorks: [],
    elementsMentioned: ['H', 'He', 'Fr', 'C', 'O', 'U', 'S', 'Ag', 'Si', 'Na', 'N', 'Zn', 'Ba', 'P', 'Cl', 'Ca', 'K', 'Al', 'Fe', 'Mg'],
  },
  'c2-s05': {
    substances: [],
    reactions: [],
    labWorks: [],
    elementsMentioned: ['Na', 'S', 'C', 'Cl', 'Au', 'Cu', 'H', 'K', 'Ca', 'O'],
    notes: ['Isotopes only: 12C, 13C, 14C, протий, дейтерий, 35Cl, 37Cl, 40K, 40Ca; no substances.'],
  },
  'c2-s06': {
    substances: [
      S('=H2O', 'вода', 'oxide', 'studied', 51, 'Итак, молекула воды состоит из двух атомов водорода (Н) и одного атома кислорода (О).'),
      S('=Cl2O7', 'Cl2O7 (оксид хлора(VII))', 'oxide', 'mentioned', 52, 'Индекс записывается под химическим символом химических элементов – Cl2O7', { note: 'name not given in book' }),
      S('=Si3N4', 'Si3N4 (нитрид кремния)', 'other', 'mentioned', 52, 'Если валентность кремния IV, а азота III ... Запишем формулу соединения: Si3N4.', { note: 'name not given in book' }),
      S('=Mn2O7', 'соединение VII-валентного марганца с кислородом', 'oxide', 'mentioned', 52, 'Составим химическую формулу соединения элемента VII-валентного марганца с кислородом: Mn O → Mn2O7'),
      S('=SO3', 'SO3 (оксид серы(VI))', 'oxide', 'mentioned', 52, 'VI II S O → S2O6 → SO3', { note: 'S2O6 is an intermediate non-reduced formula, not a substance' }),
      S('=HCl', 'HCl (хлористый водород)', 'acid', 'mentioned', 52, 'хлор имеет валентность I в HCl, кислород валентностьII в H2O, азот валентность III в NH3'),
      S('=NH3', 'NH3 (аммиак)', 'other', 'mentioned', 52, 'хлор имеет валентность I в HCl, кислород валентностьII в H2O, азот валентность III в NH3'),
      S('=CuCl2', 'CuCl2', 'salt', 'mentioned', 53, '3CuCl2 2O3 5Al Коэффицент', { note: 'coefficient example' }),
      S('=O3', 'O3', 'simple', 'mentioned', 53, '3CuCl2 2O3 5Al Коэффицент', { note: 'coefficient example (озон)' }),
      S('=Al', 'Al', 'simple', 'mentioned', 53, '3CuCl2 2O3 5Al Коэффицент', { note: 'coefficient example' }),
      S('=Fe', 'железо', 'simple', 'mentioned', 52, 'три молекулы воды – это 3H2O, пять атомов железа – это 5Fe'),
      S('=H2', 'водород', 'simple', 'mentioned', 53, 'Некоторые элементы имеют форму молекул: H2, N2, O2, F2, Cl2, Br2, J2.'),
      S('=N2', 'азот', 'simple', 'mentioned', 53, 'Некоторые элементы имеют форму молекул: H2, N2, O2, F2, Cl2, Br2, J2.'),
      S('=O2', 'кислород', 'simple', 'mentioned', 53, 'Некоторые элементы имеют форму молекул: H2, N2, O2, F2, Cl2, Br2, J2.'),
      S('=F2', 'фтор', 'simple', 'mentioned', 53, 'Некоторые элементы имеют форму молекул: H2, N2, O2, F2, Cl2, Br2, J2.'),
      S('=Cl2', 'хлор', 'simple', 'mentioned', 53, 'Некоторые элементы имеют форму молекул: H2, N2, O2, F2, Cl2, Br2, J2.'),
      S('=Br2', 'бром', 'simple', 'mentioned', 53, 'Некоторые элементы имеют форму молекул: H2, N2, O2, F2, Cl2, Br2, J2.'),
      S('=I2', 'йод (J2)', 'simple', 'mentioned', 53, 'Некоторые элементы имеют форму молекул: H2, N2, O2, F2, Cl2, Br2, J2.', { note: 'book uses old symbol J for iodine' }),
      S('=HCl', 'хлористый водород', 'acid', 'mentioned', 53, 'водород (H2), такие как хлор (Cl2), хлористый водород (HCl), оксид углерода (IV)(CO2), этан (C2H6), вода (H2O)'),
      S('=CO2', 'оксид углерода (IV)', 'oxide', 'mentioned', 53, 'хлористый водород (HCl), оксид углерода (IV)(CO2), этан (C2H6), вода (H2O)'),
      S('=C2H6', 'этан', 'organic', 'mentioned', 53, 'оксид углерода (IV)(CO2), этан (C2H6), вода (H2O)'),
      S('H2SO4', 'серная кислота (графическая и электронная формула)', 'acid', 'mentioned', 53, 'Структурная или графическая формула вещества показывает расположение атомов в молекуле. Каждая строка в нем указывает валентность', { note: 'formula shown only as structural/electron-dot picture (verified on rendered page)' }),
      S('KF', 'фтор с калием', 'salt', 'mentioned', 53, 'Используя валентности элементов, напишите формулы соединений: A) фтор с калием', ex('exercise answer, not written in book')),
      S('MgO', 'магний с кислородом', 'oxide', 'mentioned', 53, 'B) магний с кислородом', ex('exercise answer, not written in book')),
      S('CaH2', 'кальций с водородом', 'other', 'mentioned', 53, 'C) кальций с водородом', ex('exercise answer, not written in book (hydride)')),
      S('AlF3', 'алюминий с фтором', 'salt', 'mentioned', 53, 'D) алюминий с фтором', ex('exercise answer, not written in book')),
      S('Al2O3', 'алюминий с кислородом', 'oxide', 'mentioned', 53, 'E) алюминия с кислородом', ex('exercise answer, not written in book')),
      S('=BeCl2', 'BeCl2', 'salt', 'mentioned', 53, 'A) HCl; B) BeCl2; C) AlBr3; D) PH3; E) TiC.', EX),
      S('=AlBr3', 'AlBr3', 'salt', 'mentioned', 53, 'A) HCl; B) BeCl2; C) AlBr3; D) PH3; E) TiC.', EX),
      S('=PH3', 'PH3', 'other', 'mentioned', 53, 'A) HCl; B) BeCl2; C) AlBr3; D) PH3; E) TiC.', EX),
      S('=TiC', 'TiC', 'other', 'mentioned', 53, 'A) HCl; B) BeCl2; C) AlBr3; D) PH3; E) TiC.', ex('carbide; on p72 the same exercise has TiCl4 instead')),
      S('SiH4', 'SiH4 (структурная формула в задании)', 'other', 'mentioned', 53, '3. Напишите молекулярные формулы следующих соединений.', ex('shown only as a structural formula picture (verified on rendered page)')),
      S('H2SO3', 'H2SO3 (структурная формула в задании)', 'acid', 'mentioned', 53, '3. Напишите молекулярные формулы следующих соединений.', ex('shown only as a structural formula picture (verified on rendered page)')),
      S('MgCO3', 'MgCO3 (структурная формула в задании)', 'salt', 'mentioned', 53, '3. Напишите молекулярные формулы следующих соединений.', ex('shown only as a structural formula picture (verified on rendered page)')),
    ],
    reactions: [],
    labWorks: [],
    elementsMentioned: ['H', 'Li', 'Na', 'K', 'F', 'O', 'Mg', 'Ca', 'Ba', 'Zn', 'Al', 'B', 'S', 'N', 'P', 'Fe', 'Cu', 'C', 'Si', 'Cl', 'Br', 'I', 'Mn'],
  },
  'c2-s07': {
    substances: [
      S('H2', 'водород (газообразный)', 'simple', 'mentioned', 54, 'молекулы газообразного водорода имеют два атома водорода'),
      S('C6H12O6', 'глюкоза (фруктовый сахар)', 'organic', 'mentioned', 54, 'молекула глюкозы (фруктового сахара) имеет 24 атома – 12 атомов водорода, по 6 атомов углерода и кислорода', { note: 'formula inferred from the atom count given' }),
      S('C12H22O11', 'сахар', 'organic', 'mentioned', 54, 'растворение сахара в воде и другие подобные явления', { note: 'formula inferred (sucrose)' }),
      S('=H2O', 'вода', 'oxide', 'studied', 55, 'Mr (H2O) = 2⋅Ar (H) + Ar (O) = 2 ⋅ 1 + 16 = 18'),
      S('=CO2', 'CO2', 'oxide', 'studied', 55, 'Mr (CO2)= Ar(C) + 2⋅Ar(O) = 12 + 2 ⋅ 16 = 44'),
      S('=H2SO4', 'серная кислота', 'acid', 'studied', 55, 'Относительная молекулярная масса серной кислоты H2SO4', { note: 'book arithmetic "2 ⋅ 16" should be "4 ⋅ 16" (result 98 is correct)' }),
      S('HNO3', 'азотная кислота', 'acid', 'mentioned', 55, 'Азотная кислота содержит один атом водорода, один атом азота и три атома кислорода', ex('formula inferred from composition in the text')),
      S('=H3PO4', 'H3PO4', 'acid', 'mentioned', 55, 'Какое из перечисленных веществ имеет относительную молекулярную массу 100? H3PO4, CaCO3, NaCl, NO2', EX),
      S('=CaCO3', 'CaCO3', 'salt', 'mentioned', 55, 'H3PO4, CaCO3, NaCl, NO2', EX),
      S('=NaCl', 'NaCl', 'salt', 'mentioned', 55, 'H3PO4, CaCO3, NaCl, NO2', EX),
      S('=NO2', 'NO2', 'oxide', 'mentioned', 55, 'H3PO4, CaCO3, NaCl, NO2', EX),
    ],
    reactions: [],
    labWorks: [],
  },
  'c2-s08': {
    substances: [
      S('O2', 'кислород', 'simple', 'studied', 56, 'Кислород набирают в пробирку – в этом случае кислород – простое вещество'),
      S('O3', 'озон', 'simple', 'mentioned', 56, 'Образование озона из кислорода в природе', { note: 'figure caption; allotropy' }),
      S('Br2', 'бром', 'simple', 'studied', 56, 'Например, бром и ртуть жидкие, водород, кислород, азот, хлор, газообразный гелий'),
      S('Hg', 'ртуть', 'simple', 'studied', 56, 'Например, бром и ртуть жидкие, водород, кислород, азот, хлор, газообразный гелий'),
      S('H2', 'водород', 'simple', 'studied', 56, 'бром и ртуть жидкие, водород, кислород, азот, хлор, газообразный гелий'),
      S('N2', 'азот', 'simple', 'studied', 56, 'бром и ртуть жидкие, водород, кислород, азот, хлор, газообразный гелий'),
      S('=Cl2', 'хлор', 'simple', 'studied', 56, 'Чем молекулы кислорода и хлора отличаются от молекул воды и углекислого газа? O2 и Cl2, H2O и CO2'),
      S('He', 'гелий', 'simple', 'studied', 56, 'хлор, газообразный гелий, железо, углерод, сера, магний, кальций, железо – твердые при комнатной температуре'),
      S('Fe', 'железо', 'simple', 'studied', 56, 'железо, углерод, сера, магний, кальций, железо – твердые при комнатной температуре'),
      S('C', 'углерод', 'simple', 'studied', 56, 'железо, углерод, сера, магний, кальций, железо – твердые при комнатной температуре'),
      S('S', 'сера', 'simple', 'studied', 56, 'железо, углерод, сера, магний, кальций, железо – твердые при комнатной температуре'),
      S('Mg', 'магний', 'simple', 'studied', 56, 'железо, углерод, сера, магний, кальций, железо – твердые при комнатной температуре'),
      S('Ca', 'кальций', 'simple', 'studied', 56, 'железо, углерод, сера, магний, кальций, железо – твердые при комнатной температуре'),
      S('=H2O', 'вода', 'oxide', 'studied', 57, 'вода (Н2О) – это соединение, состоящее из двух элементов, соединенных в соотношении 2 : 1'),
      S('=CO2', 'углекислый газ', 'oxide', 'studied', 57, 'На воздухе углерод сгорает в кислороде и образует одно вещество – углекислый газ.'),
      S('C', 'графит', 'simple', 'studied', 57, 'Модификации углерода: Графит Аморфный уголь Алмаз'),
      S('C', 'аморфный уголь', 'simple', 'studied', 57, 'Модификации углерода: Графит Аморфный уголь Алмаз'),
      S('C', 'алмаз', 'simple', 'studied', 57, 'Модификации углерода: Графит Аморфный уголь Алмаз'),
      S('P', 'белый фосфор', 'simple', 'studied', 57, 'Модификации фосфора: Белый фосфор Красный фосфор Черный фосфор', { note: 'white phosphorus is P4' }),
      S('P', 'красный фосфор', 'simple', 'studied', 57, 'Модификации фосфора: Белый фосфор Красный фосфор Черный фосфор'),
      S('P', 'черный фосфор', 'simple', 'studied', 57, 'Модификации фосфора: Белый фосфор Красный фосфор Черный фосфор'),
      S('P', 'металлический фосфор', 'simple', 'studied', 57, 'Металлический фосфор'),
      S('S', 'ромбическая сера', 'simple', 'studied', 57, 'Ромбическая сера Пластическая сера Моноклинная сера'),
      S('S', 'пластическая сера', 'simple', 'studied', 57, 'Ромбическая сера Пластическая сера Моноклинная сера'),
      S('S', 'моноклинная сера', 'simple', 'studied', 57, 'Ромбическая сера Пластическая сера Моноклинная сера'),
      S('C2H5OH', 'этиловый спирт', 'organic', 'reagent', 58, 'Необходимые оборудования и вещества: 2 стакана, молоко, этиловый спирт.', { note: 'formula inferred' }),
      S(null, 'казеиновое вещество (казеин)', 'organic', 'obtained', 58, 'казеиновое вещество в молоке отделяется от спиртовой сыворотки', { note: 'protein; no formula' }),
      S('=H3PO4', 'H3PO4', 'acid', 'mentioned', 58, 'Знак водорода Знак фосфора Знак кислорода H3PO4 3 атома водорода 1 aтом фосфора 4 aтома кислорода'),
      S('FeS', 'соединение железа с серой', 'salt', 'obtained', 59, 'Смесь железа с серой ... Соединение железа с серой', { note: 'figure; formula inferred (iron(II) sulfide)' }),
      S('=CaCO3', 'карбонат кальция', 'salt', 'mentioned', 59, 'Формула карбоната кальция – CaCO3.', EX),
      S('NaCl', 'хлорид натрия', 'salt', 'mentioned', 59, 'Ответьте на вопросы, основываясь на изображении хлорида натрия с водой ниже.', EX),
      S('=CO2', 'углекислый газ', 'oxide', 'mentioned', 59, 'растения с зелеными листьями поглощают углекислый газ (CO2) из воздуха и воду (H2O) из почвы', EX),
      S('=C6H12O6', 'глюкоза', 'organic', 'obtained', 59, 'под воздействием света, образуются глюкоза (C6H12O6) и кислород (O2)', EX),
      S('=O2', 'кислород', 'simple', 'obtained', 59, 'образуются глюкоза (C6H12O6) и кислород (O2)', EX),
      S('=N2', 'азот', 'simple', 'mentioned', 59, 'Азот (N2), содержащийся в воздухе, способен усваиваться кишечными бактериями', EX),
      S('=(NH2)2CO', 'мочевина', 'organic', 'mentioned', 59, 'образуются различные органические вещества, мочевина (NH2) 2CO), а иногда и аммиак (NH3)', ex('book prints "(NH2) 2CO)"')),
      S('=NH3', 'аммиак', 'other', 'mentioned', 59, 'мочевина (NH2) 2CO), а иногда и аммиак (NH3)', EX),
    ],
    reactions: [
      R(null, '3O2 → 2O3', 'other', 56, 'Образование озона из кислорода в природе', { conditions: 'электрический разряд / УФ (в природе)', note: 'figure caption only; equation reconstructed (allotropic transformation)' }),
      R(null, 'C + O2 → CO2', 'combustion', 57, 'На воздухе углерод сгорает в кислороде и образует одно вещество – углекислый газ.', { conditions: 't°', note: 'described in words; equation printed later on p69' }),
      R(null, 'Fe + S → FeS', 'combination', 59, 'Разложить сложное вещество на составные части ... Соединение железа с серой', { conditions: 't°', note: 'figure contrasting mixture Fe+S with compound; equation reconstructed' }),
      R(null, '6CO2 + 6H2O → C6H12O6 + 6O2', 'redox', 59, 'растения с зелеными листьями поглощают углекислый газ (CO2) из воздуха и воду (H2O) из почвы под воздействием света, образуются глюкоза', ex('photosynthesis described in words with formulas; coefficients added (equation printed on p91)', { conditions: 'hν (свет), хлорофилл' })),
    ],
    labWorks: [
      L('Опыт. Определение содержания воды в молоке', 58, ['молоко', 'этиловый спирт (C2H5OH)'], { kind: 'experiment' }),
      L('Опыт. Определение качества сливочного масла', 58, ['сливочное масло', 'кипяченая вода'], { kind: 'experiment' }),
    ],
  },
  'c2-s09': {
    substances: [
      S('=H2', 'H2', 'simple', 'studied', 60, '1 моль H2 весит 2 г (Mr(H2) = 2)'),
      S('=O2', 'O2', 'simple', 'studied', 60, '1 моль O2 весит 32 г (Mr(O2) = 32)'),
      S('=H2O', 'вода', 'oxide', 'studied', 60, '1 моль H2O весит 18 г (Mr (H2O) = 18)'),
      S('NH3', 'аммиак', 'other', 'mentioned', 60, 'установил точный количественный атомный состав молекул многих веществ (воды, водорода, кислорода, азота, аммиака, хлора, закиси азота)', { note: 'formula inferred' }),
      S('Cl2', 'хлор', 'simple', 'mentioned', 60, '(воды, водорода, кислорода, азота, аммиака, хлора, закиси азота)', { note: 'formula inferred' }),
      S('N2O', 'закись азота', 'oxide', 'mentioned', 60, '(воды, водорода, кислорода, азота, аммиака, хлора, закиси азота)', { note: 'formula inferred' }),
      S('=Na', 'натрий', 'simple', 'studied', 61, '1 моль натрия – 6,02 • 1023 атомов Na'),
      S('=N2', 'азот', 'simple', 'studied', 61, '1 моль азота – 6,02 • 1023 молекулы N2.'),
      S('=Fe', 'железо', 'simple', 'studied', 61, 'Вычислить массу (г) железа, содержащего 0,5 моль вещества?'),
      S('=CaO', 'оксид кальция', 'oxide', 'studied', 61, 'Решение: химическая формула оксида кальция CaO.'),
      S('=C', 'углерод', 'simple', 'studied', 62, 'Найти число атомов в 2 молях углерода.'),
      S('=H2SO4', 'серная кислота', 'acid', 'studied', 62, '10H2SO4 N = 6,02∙1023∙ 10= 60,2 ∙ 1023 M (H2SO4) = 98 г/моль'),
      S('=FeCl2', 'FeCl2', 'salt', 'studied', 62, '2FeCl2 N = 6,02∙1023∙ 2 = 12,04 ∙ 1023 M (FeCl2) = 127 г/моль'),
      S('NaCl', 'поваренная соль', 'salt', 'mentioned', 62, 'попросила у продавца 5 молей поваренной соли', EX),
      S('H2O', 'вода', 'oxide', 'mentioned', 62, 'Сколько молекул содержится в 180 граммах воды?', EX),
      S('CO2', 'углекислый газ', 'oxide', 'mentioned', 62, 'Сколько молекул содержится в 80 г углекислого газа?', EX),
      S('Zn', 'цинк', 'simple', 'mentioned', 62, 'Когда кусок цинка взвесили на весах, определили, что он имеет массу 26 г.', EX),
    ],
    reactions: [],
    labWorks: [],
  },
  'c2-s10': {
    substances: [
      S('=HCl', 'HCl', 'acid', 'studied', 63, 'HCl – хлор (I) H2O – кислород (II); NH3 – азот (III); CH4 – углерод (IV).'),
      S('=H2O', 'H2O', 'oxide', 'studied', 63, 'HCl – хлор (I) H2O – кислород (II); NH3 – азот (III); CH4 – углерод (IV).'),
      S('=NH3', 'NH3', 'other', 'studied', 63, 'HCl – хлор (I) H2O – кислород (II); NH3 – азот (III); CH4 – углерод (IV).'),
      S('=CH4', 'CH4', 'organic', 'studied', 63, 'HCl – хлор (I) H2O – кислород (II); NH3 – азот (III); CH4 – углерод (IV).'),
      ...['H2S', 'CaH2', 'NaH', 'PH3', 'H2Se', 'HBr', 'SiH4'].map((f) =>
        S('=' + f, f, f === 'H2S' || f === 'H2Se' || f === 'HBr' ? 'acid' : 'other', 'mentioned', 63, 'Определите валентность элементов в следующих веществах: H2S, CaH2, NaH, NH3, CH4, PH3, HCl, H2Se, HBr, SiH4', EX),
      ),
      ...['Au2O3', 'CuO', 'MnO', 'Fe2O3', 'CrO3', 'Cu2O', 'K2O', 'N2O', 'NO', 'N2O3'].map((f) =>
        S('=' + f, f, 'oxide', 'mentioned', 63, 'Определите валентности атомов ... по формулам: Au2O3, CuO, MnO, Fe2O3, CrO3, Cu2O, K2O, N2O, NO, N2O3.', EX),
      ),
      ...['CO', 'SiO2', 'SO3'].map((f) =>
        S('=' + f, f, 'oxide', 'mentioned', 63, 'В соединениях K2O, CO, N2O3, SiO2, SO3 чтобы найти валентность элементов, нужно умножить число атомов О на два'),
      ),
      S('=P2O5', 'P2O5', 'oxide', 'mentioned', 63, 'Например, P2O5 валентность фосфора x: x= (5·2)÷2=5 P(V)'),
      S('=Cl2O5', 'Cl2O5', 'oxide', 'mentioned', 63, '2-пример. Определите валентности элементов в соединенииCl2O5 .'),
      ...['MgO', 'CaO', 'Al2O3', 'SO2', 'CO2', 'Na2O', 'Mn2O7', 'Cl2O3', 'ZnO'].map((f) =>
        S('=' + f, f, 'oxide', 'mentioned', 63, 'Определите валентность элементов в следующих веществах: MgO, CaO, Al2O3, SO2, P2O5, CO2, Na2O, Mn2O7, Cl2O3, ZnO', EX),
      ),
      S('=CaH2', 'CaH2', 'other', 'studied', 64, 'В нижней части химического элемента записывается индекс – CaH2'),
      S('=NaCl', 'NaCl', 'salt', 'mentioned', 64, 'Соединения, состоящие из двух элементов, называются бинарными соединениями, например: CaO, H2O, NaCl, HCl.'),
      S('=CO', 'монооксид углерода', 'oxide', 'mentioned', 64, 'Монооксид углерода – CO, диоксид углерода – CO2, трихлорид железа – FeCl3'),
      S('=CO2', 'диоксид углерода', 'oxide', 'mentioned', 64, 'Монооксид углерода – CO, диоксид углерода – CO2, трихлорид железа – FeCl3'),
      S('=FeCl3', 'трихлорид железа', 'salt', 'mentioned', 64, 'Монооксид углерода – CO, диоксид углерода – CO2, трихлорид железа – FeCl3'),
      S('FeO', 'кислородное соединение железа (II)', 'oxide', 'mentioned', 64, 'Составьте химическую формулу кислородных соединений следующих элементов: а) железа (II); б) азот (IV).', ex('exercise answer, not written in book')),
      S('NO2', 'кислородное соединение азота (IV)', 'oxide', 'mentioned', 64, 'а) железа (II); б) азот (IV).', ex('exercise answer, not written in book')),
      S('AlCl3', 'соединение хлора с алюминием', 'salt', 'mentioned', 64, 'Составьте химическую формулу соединений хлора следующих элементов ... а) алюминий; б) кальций.', ex('exercise answer, not written in book')),
      S('CaCl2', 'соединение хлора с кальцием', 'salt', 'mentioned', 64, 'а) алюминий; б) кальций.', ex('exercise answer, not written in book')),
      S('=NO', 'NO', 'oxide', 'mentioned', 64, 'Составьте химическую формулу следующих соединений: NO, BaO, SiO, KO.', EX),
      S('=BaO', 'BaO', 'oxide', 'mentioned', 64, 'Составьте химическую формулу следующих соединений: NO, BaO, SiO, KO.', EX),
      S('=CaC2', 'CaC2 (кальций : углерод 1:2)', 'other', 'mentioned', 64, 'Kaльций: углерод 1:2 ... CaC2', ex('carbide; table')),
      S('KCl', 'калий : хлор 1:1', 'salt', 'mentioned', 64, 'Kaлий: xлор 1:1', ex('table answer, not written in book')),
      S('Na2S', 'натрий : сера (I и II)', 'salt', 'mentioned', 64, 'Натрий: сера I va II', ex('table answer, not written in book')),
    ],
    reactions: [],
    labWorks: [
      L('Практическое занятие. Определение валентности элементов в соединениях (упражнения)', 63, [], { kind: 'practical' }),
    ],
    notes: [
      'p64 exercise 3 lists "SiO" and "KO" as items to write formulas for: KO is not a valid formula (K2O intended), SiO is exotic — both omitted from substances.',
      'p64 table row "Марганец: кислород 2:7" = Mn2O7 (already listed on p63).',
    ],
  },
  'c2-s11': {
    substances: [
      S('=CO2', 'оксид углерода (IV)', 'oxide', 'studied', 65, 'Задача. Определите валентность углерода в оксиде углерода (IV) (СО2).'),
      S('=NaCl', 'поваренная соль (хлорид натрия)', 'salt', 'studied', 65, 'сколько стоит 1 моль поваренной соли (хлорида натрия NaCl)?'),
      S('C', 'алмаз', 'simple', 'mentioned', 65, 'масса углерода в крупнейшем в мире алмазе весом 3106 карат (аллотропная модификация углерода)', EX),
      S('H2O', 'минеральная вода', 'oxide', 'mentioned', 65, 'В стакане содержится 54 г минеральной воды.', EX),
      S('Hg', 'ртуть', 'simple', 'mentioned', 65, 'Если 20,1 г ртути составляют 0,1 моль, рассчитайте ее молекулярную массу.', EX),
      S('H2SO4', 'серная кислота', 'acid', 'mentioned', 65, 'Напишите химические формулы воды, хлорида натрия, углекислого газа, серной кислоты'),
      S('C12H22O11', 'сахар', 'organic', 'mentioned', 65, 'Взвесьте на весах 1 кусок сахара, подсчитайте, сколько молей это составляет.', ex('formula inferred (sucrose)')),
      S('=Al(OH)3', 'гидроксид алюминия', 'base', 'studied', 66, 'Вычислите массовое соотношение алюминия, кислорода и водорода в составе гидроксида алюминия Al(OH)3'),
      ...['H2O', 'CaO', 'Ca(OH)2', 'SO2', 'SO3', 'CuSO4'].map((f) =>
        S('=' + f, f, f === 'Ca(OH)2' ? 'base' : f === 'CuSO4' ? 'salt' : 'oxide', 'mentioned', 66, 'Рассчитайте массовые соотношения элементов, входящих в состав следующих соединений: H2O, CaO, Ca(OH)2,SO2,SO3, CuSO4.', EX),
      ),
      S('=H2O', 'вода', 'oxide', 'studied', 66, 'Химическая формула вещества H2O CO2 Название вещества Вода Углекислый газ'),
      S('=CO2', 'углекислый газ', 'oxide', 'studied', 66, 'Химическая формула вещества H2O CO2 Название вещества Вода Углекислый газ'),
    ],
    reactions: [],
    labWorks: [
      L('Практическое занятие. Решение расчётных задач на основе химических формул (в т.ч. опыт: столовая ложка воды, кусок сахара)', 65, ['вода', 'сахар'], { kind: 'practical' }),
    ],
    elementsMentioned: ['H', 'S', 'O', 'Na', 'Cl', 'C', 'Cu', 'Ar'],
  },
  'c2-s12': {
    substances: [
      S('=NaOH', 'гидроксид натрия', 'base', 'reagent', 67, 'Изменение цвета: NaОН (гидроксид натрия – бесцветный) + фенолфталеин (бесцветный) – малиновый цвет.'),
      S(null, 'фенолфталеин', 'organic', 'reagent', 67, 'NaОН (гидроксид натрия – бесцветный) + фенолфталеин (бесцветный) – малиновый цвет.', { note: 'indicator; no formula in book' }),
      S('=HCl', 'HCl', 'acid', 'reagent', 67, 'NaOH HCl признак не наблюдается'),
      S('=MgCl2', 'MgCl2', 'salt', 'reagent', 67, 'NaOH MgCl2 белый осадок'),
      S('=BaCl2', 'BaCl2', 'salt', 'reagent', 67, 'Образование осадка: BaCl2 +H2SO4→ BaSO4↓+2HCl'),
      S('=H2SO4', 'H2SO4', 'acid', 'reagent', 67, 'Образование осадка: BaCl2 +H2SO4→ BaSO4↓+2HCl'),
      S('=BaSO4', 'BaSO4', 'salt', 'obtained', 67, 'Образование осадка: BaCl2 +H2SO4→ BaSO4↓+2HCl'),
      S('=CH4', 'CH4', 'organic', 'reagent', 67, 'Выделение тепла CH4 + 2O2 → CO2 + + 2H2O+ Q'),
      S('=O2', 'кислород', 'simple', 'reagent', 67, 'Выделение тепла CH4 + 2O2 → CO2 + + 2H2O+ Q'),
      S('=CO2', 'углекислый газ', 'oxide', 'obtained', 67, 'Выделение тепла CH4 + 2O2 → CO2 + + 2H2O+ Q'),
      S('=H2O', 'вода', 'oxide', 'obtained', 67, 'Выделение тепла CH4 + 2O2 → CO2 + + 2H2O+ Q'),
      S('=Zn', 'цинк', 'simple', 'reagent', 67, 'Выделение газообразных веществ: Zn + 2HCl →ZnCl2 + H2↑'),
      S('=ZnCl2', 'хлорид цинка', 'salt', 'obtained', 67, 'Выделение газообразных веществ: Zn + 2HCl →ZnCl2 + H2↑'),
      S('=H2', 'водород', 'simple', 'obtained', 67, 'Выделение газообразных веществ: Zn + 2HCl →ZnCl2 + H2↑'),
      S('Cu', 'медь (медная проволока)', 'simple', 'reagent', 67, 'Медь не вступает в реакцию с кислородом воздуха при комнатной температуре'),
      S('C12H22O11', 'сахар', 'organic', 'reagent', 67, 'Чтобы разложить сахар, необходимо непрерывно подводить тепло', { note: 'formula inferred (sucrose)' }),
      S('=C', 'углерод', 'simple', 'reagent', 69, 'Химическое уравнение: C + O2 → CO2'),
      S('=Mg', 'магний', 'simple', 'reagent', 69, '2-шаг: Mg + O2 → MgO (уравнение реакции)'),
      S('=MgO', 'оксид магния', 'oxide', 'obtained', 69, '1-шаг: магний + кислород → оксид магния (выражается словами)'),
      S('=CO', 'оксид углерода', 'oxide', 'obtained', 70, '2C + O2 → 2CO (уравнилась).'),
      S('=HCl', 'соляная кислота', 'acid', 'reagent', 69, 'цинк + соляная кислота → хлорид цинка + водород.'),
      S('Cl2', 'хлор', 'simple', 'mentioned', 69, 'составьте уравнения реакции между следующими элементами: магнием и хлором, алюминием и бромом, углеродом и фтором', EX),
      S('Al', 'алюминий', 'simple', 'mentioned', 69, 'магнием и хлором, алюминием и бромом, углеродом и фтором', EX),
      S('Br2', 'бром', 'simple', 'mentioned', 69, 'магнием и хлором, алюминием и бромом, углеродом и фтором', EX),
      S('F2', 'фтор', 'simple', 'mentioned', 69, 'магнием и хлором, алюминием и бромом, углеродом и фтором', EX),
      S('I2', 'йод', 'simple', 'mentioned', 70, 'A) Алюминий + йод → йодид алюминия', EX),
      S('AlI3', 'йодид алюминия', 'salt', 'mentioned', 70, 'A) Алюминий + йод → йодид алюминия', ex('formula inferred')),
      S('Na', 'натрий', 'simple', 'mentioned', 70, 'Б) Натрий + кислород → оксид натрия', EX),
      S('Na2O', 'оксид натрия', 'oxide', 'mentioned', 70, 'Б) Натрий + кислород → оксид натрия', ex('formula inferred')),
      S('K', 'калий', 'simple', 'mentioned', 70, 'В) Калий + вода → гидроксид калия + водород', EX),
      S('KOH', 'гидроксид калия', 'base', 'mentioned', 70, 'В) Калий + вода → гидроксид калия + водород', ex('formula inferred')),
      S('S', 'сера', 'simple', 'mentioned', 70, 'a) Сера и кислород образуют оксид серы (IV); б) Железо и сера образуют сульфид железа (II).', EX),
      S('SO2', 'оксид серы (IV)', 'oxide', 'mentioned', 70, 'a) Сера и кислород образуют оксид серы (IV)', ex('formula inferred')),
      S('Fe', 'железо', 'simple', 'mentioned', 70, 'б) Железо и сера образуют сульфид железа (II).', EX),
      S('FeS', 'сульфид железа (II)', 'salt', 'mentioned', 70, 'б) Железо и сера образуют сульфид железа (II).', ex('formula inferred')),
      S('=H2S', 'H2S', 'acid', 'mentioned', 70, '1) … + … → H2S + NaCl', EX),
      S('=NaCl', 'NaCl', 'salt', 'mentioned', 70, '1) … + … → H2S + NaCl', EX),
      S('=K2CO3', 'K2CO3', 'salt', 'mentioned', 70, '3) CO2 + ... → K2CO3', EX),
      S('=N2', 'N2', 'simple', 'mentioned', 70, '4) N2 + ... →NO', EX),
      S('=NO', 'NO', 'oxide', 'mentioned', 70, '4) N2 + ... →NO', EX),
      S('Li', 'литий', 'simple', 'mentioned', 70, 'D) литий + водород →?', EX),
    ],
    reactions: [
      R('NaОН (гидроксид натрия – бесцветный) + фенолфталеин (бесцветный) – малиновый цвет.', 'NaOH + фенолфталеин → малиновое окрашивание', 'other', 67, 'Изменение цвета: NaОН (гидроксид натрия – бесцветный) + фенолфталеин (бесцветный) – малиновый цвет.', {
        reactants: [{ formula: 'NaOH', coeff: 1 }, { formula: null, name: 'фенолфталеин', coeff: 1 }],
        products: [],
        note: 'indicator colour change; not a stoichiometric equation',
      }),
      R('NaOH HCl признак не наблюдается', 'NaOH + HCl → NaCl + H2O', 'neutralization', 67, 'NaOH HCl признак не наблюдается', { note: 'book lists only the reactants ("no visible sign"); products reconstructed' }),
      R('NaOH MgCl2 белый осадок', '2NaOH + MgCl2 → Mg(OH)2↓ + 2NaCl', 'exchange', 67, 'NaOH MgCl2 белый осадок', { note: 'book lists only the reactants and "white precipitate"; products/coefficients reconstructed' }),
      R('BaCl2 +H2SO4→ BaSO4↓+2HCl', 'BaCl2 + H2SO4 → BaSO4↓ + 2HCl', 'exchange', 67, 'Образование осадка: BaCl2 +H2SO4→ BaSO4↓+2HCl'),
      R('CH4 + 2O2 → CO2 + + 2H2O+ Q', 'CH4 + 2O2 → CO2 + 2H2O + Q', 'combustion', 67, 'Выделение тепла CH4 + 2O2 → CO2 + + 2H2O+ Q', { note: 'book has a stray double "+ +"' }),
      R('Zn + 2HCl →ZnCl2 + H2↑', 'Zn + 2HCl → ZnCl2 + H2↑', 'substitution', 67, 'Выделение газообразных веществ: Zn + 2HCl →ZnCl2 + H2↑', { note: 'also worked example on p69–70 (Zn + HCl → ZnCl2 + H2, then balanced)' }),
      R(null, '2Cu + O2 → 2CuO', 'combination', 67, 'Медь не вступает в реакцию с кислородом воздуха при комнатной температуре ... необходимо нагреть медь.', { conditions: 't°', note: 'described in words (also "Нагревание медной проволоки" p68, student asked to write the equation); equation reconstructed' }),
      R(null, 'C12H22O11 → 12C + 11H2O', 'decomposition', 67, 'Чтобы разложить сахар, необходимо непрерывно подводить тепло, если прекратить нагревание то реакция также прекратится.', { conditions: 't°', note: 'described in words; equation reconstructed (charring of sugar)' }),
      R('C + O2 → CO2', 'C + O2 → CO2', 'combustion', 69, 'Химическое уравнение: C + O2 → CO2', { conditions: 't°', note: 'word form on p68: Углерод + Кислород → Углекислый газ' }),
      R('2 Mg + O2 → 2 MgO', '2Mg + O2 → 2MgO', 'combination', 69, '3-шаг: 2 Mg + O2 → 2 MgO (уравненная химическая реакция)', { conditions: 't°', note: 'unbalanced step also printed: Mg + O2 → MgO' }),
      R(null, 'Mg + Cl2 → MgCl2', 'combination', 69, 'составьте уравнения реакции между следующими элементами: магнием и хлором', ex('exercise; equation not printed')),
      R(null, '2Al + 3Br2 → 2AlBr3', 'combination', 69, 'алюминием и бромом', ex('exercise; equation not printed')),
      R(null, 'C + 2F2 → CF4', 'combination', 69, 'углеродом и фтором', ex('exercise; equation not printed')),
      R('2C + O2 → 2CO (уравнилась)', '2C + O2 → 2CO', 'combination', 70, '1. Составьте уравнение реакции углерода с ограниченным количеством кислорода. ... 2C + O2 → 2CO (уравнилась).', { conditions: 'недостаток O2, t°' }),
      R('Алюминий + йод → йодид алюминия', '2Al + 3I2 → 2AlI3', 'combination', 70, 'A) Алюминий + йод → йодид алюминия', ex('word equation only; formulas/coefficients added')),
      R('Натрий + кислород → оксид натрия', '4Na + O2 → 2Na2O', 'combination', 70, 'Б) Натрий + кислород → оксид натрия', ex('word equation only; formulas/coefficients added')),
      R('Калий + вода → гидроксид калия + водород', '2K + 2H2O → 2KOH + H2↑', 'substitution', 70, 'В) Калий + вода → гидроксид калия + водород', ex('word equation only; formulas/coefficients added')),
      R('Сера и кислород образуют оксид серы (IV)', 'S + O2 → SO2', 'combustion', 70, 'a) Сера и кислород образуют оксид серы (IV)', ex('word description; equation added', { conditions: 't°' })),
      R('Железо и сера образуют сульфид железа (II)', 'Fe + S → FeS', 'combination', 70, 'б) Железо и сера образуют сульфид железа (II).', ex('word description; equation added', { conditions: 't°' })),
      R('… + … → H2S + NaCl', 'Na2S + 2HCl → H2S↑ + 2NaCl', 'exchange', 70, '1) … + … → H2S + NaCl', ex('fill-in exercise; reactants reconstructed (one of possible answers)')),
      R('ZnCl2 + Cu→ … + …', 'ZnCl2 + Cu → (реакция не идёт)', 'substitution', 70, '2) ZnCl2 + Cu→ … + …', ex('fill-in exercise; chemically Cu does not displace Zn (Cu is less active) — likely a book error; no products', { reactants: [{ formula: 'ZnCl2', coeff: 1 }, { formula: 'Cu', coeff: 1 }], products: [] })),
      R('CO2 + ... → K2CO3', 'CO2 + K2O → K2CO3', 'combination', 70, '3) CO2 + ... → K2CO3', ex('fill-in exercise; missing reactant reconstructed')),
      R('N2 + ... →NO', 'N2 + O2 → 2NO', 'combination', 70, '4) N2 + ... →NO', ex('fill-in exercise; completed and balanced', { conditions: 'электрический разряд' })),
      R('магний + кислород → ?', '2Mg + O2 → 2MgO', 'combination', 70, '6. Составьте уравнения химических реакций. A) магний + кислород → ?', ex('word exercise; equation added')),
      R('азот + водород → ?', 'N2 + 3H2 ⇌ 2NH3', 'combination', 70, 'Б) азот + водород → ?', ex('word exercise; equation added', { conditions: 't°, p, kat' })),
      R('углерод + кислород →?', 'C + O2 → CO2', 'combustion', 70, 'В) углерод + кислород →?', ex('word exercise; equation added')),
      R('литий + водород →?', '2Li + H2 → 2LiH', 'combination', 70, 'D) литий + водород →?', ex('word exercise; equation added', { conditions: 't°' })),
    ],
    labWorks: [
      L('Нагревание медной проволоки в пламени спиртовой лампы', 68, ['медная проволока (Cu)'], { kind: 'experiment' }),
    ],
  },
  'c2-s13': {
    substances: [
      ...[
        ['Fe', 'simple'], ['HCl', 'acid'], ['FeCl2', 'salt'], ['H2', 'simple'], ['NH3', 'other'], ['N2', 'simple'], ['Cl2', 'simple'], ['FeCl3', 'salt'],
        ['O2', 'simple'], ['NO', 'oxide'], ['Mg', 'simple'], ['MgO', 'oxide'], ['CH4', 'organic'], ['CO2', 'oxide'], ['H2O', 'oxide'], ['Al', 'simple'],
        ['AlCl3', 'salt'], ['Zn', 'simple'], ['ZnO', 'oxide'], ['P', 'simple'], ['P2O5', 'oxide'],
      ].map(([f, k]) => S('=' + f, f, k, 'mentioned', 71, '1) Fe+HCl→FeCl2 + H2 2) NH3→N2 + H2 3) Fe + Cl2→FeCl3 4) N2+O2 →NO 5) Mg+O2→MgO', EX)),
      S('=Na', 'Na', 'simple', 'mentioned', 71, '1) Na и O2 2) Na и Cl2 3) Al и S 4) Fe и O2 5) N2 и H2', EX),
      S('S', 'S', 'simple', 'mentioned', 71, '1) Na и O2 2) Na и Cl2 3) Al и S 4) Fe и O2 5) N2 и H2', EX),
      S('=Ca', 'Ca', 'simple', 'mentioned', 71, '1) Ca + 2HCl → Ca "?" + H2 ↑', EX),
      S('CaCl2', 'CaCl2', 'salt', 'mentioned', 71, '1) Ca + 2HCl → Ca "?" + H2 ↑', ex('completed from fill-in')),
      S('H2S', 'H2S', 'acid', 'mentioned', 71, '3) 2H2"?" + 3O2 → 2H2O + 2SO2', ex('completed from fill-in')),
      S('=SO2', 'SO2', 'oxide', 'mentioned', 71, '3) 2H2"?" + 3O2 → 2H2O + 2SO2', EX),
      S('=Fe2O3', 'Fe2O3', 'oxide', 'mentioned', 71, '4) Fe2O3 + 3H2 →2Fe + 3 "?"O', EX),
      S('=CaCl2', 'CaCl2', 'salt', 'mentioned', 71, '5) CaCl2 + 2NaOH → Ca(OH)2 + 2Na"?"', EX),
      S('=NaOH', 'NaOH', 'base', 'mentioned', 71, '5) CaCl2 + 2NaOH → Ca(OH)2 + 2Na"?"', EX),
      S('=Ca(OH)2', 'Ca(OH)2', 'base', 'mentioned', 71, '5) CaCl2 + 2NaOH → Ca(OH)2 + 2Na"?"', EX),
      S('NaCl', 'NaCl', 'salt', 'mentioned', 71, '5) CaCl2 + 2NaOH → Ca(OH)2 + 2Na"?"', ex('completed from fill-in')),
      S('Cu', 'красный порошок меди', 'simple', 'reagent', 71, 'Красный порошок меди (6,4 г) смешали с желтым порошком серы (3,2 г) и нагрели. Образовался черный порошок.', EX),
      S('S', 'желтый порошок серы', 'simple', 'reagent', 71, 'Красный порошок меди (6,4 г) смешали с желтым порошком серы (3,2 г) и нагрели.', EX),
      S('CuS', 'черный порошок (сульфид меди)', 'salt', 'obtained', 71, 'Образовался черный порошок. Какова масса полученного черного порошка?', ex('formula inferred; masses 6.4 g Cu + 3.2 g S match CuS (1:1)')),
      S('=NO2', 'NO2', 'oxide', 'obtained', 71, 'N2 + O2 → 2NO; 2NO + O2→ 2NO2', EX),
    ],
    reactions: [
      ...[
        ['Fe+HCl→FeCl2 + H2', 'Fe + 2HCl → FeCl2 + H2↑', 'substitution'],
        ['NH3→N2 + H2', '2NH3 → N2 + 3H2', 'decomposition'],
        ['Fe + Cl2→FeCl3', '2Fe + 3Cl2 → 2FeCl3', 'combination'],
        ['N2+O2 →NO', 'N2 + O2 → 2NO', 'combination'],
        ['Mg+O2→MgO', '2Mg + O2 → 2MgO', 'combination'],
        ['H2+N2→NH3', '3H2 + N2 → 2NH3', 'combination'],
        ['CH4+O2→CO2 + H2O', 'CH4 + 2O2 → CO2 + 2H2O', 'combustion'],
        ['Al+Cl2→AlCl3', '2Al + 3Cl2 → 2AlCl3', 'combination'],
        ['Zn+O2→ZnO', '2Zn + O2 → 2ZnO', 'combination'],
        ['P+O2→P2O5', '4P + 5O2 → 2P2O5', 'combustion'],
      ].map(([b, e, t]) => R(b, e, t, 71, '1. Поставьте коэффициенты химических реакций. ' + b, ex('exercise: skeleton printed without coefficients; coefficients added'))),
      R('Na и O2', '4Na + O2 → 2Na2O', 'combination', 71, '2. ... составьте уравнения реакций между следующими парами веществ. 1) Na и O2', ex('exercise pair only; product chosen as Na2O (in reality Na burns to Na2O2, see p95)')),
      R('Na и Cl2', '2Na + Cl2 → 2NaCl', 'combination', 71, '2) Na и Cl2', ex('exercise pair only; equation added')),
      R('Al и S', '2Al + 3S → Al2S3', 'combination', 71, '3) Al и S', ex('exercise pair only; equation added', { conditions: 't°' })),
      R('Fe и O2', '3Fe + 2O2 → Fe3O4', 'combustion', 71, '4) Fe и O2', ex('exercise pair only; product chosen as Fe3O4 (as on p95)', { conditions: 't°' })),
      R('N2 и H2', 'N2 + 3H2 ⇌ 2NH3', 'combination', 71, '5) N2 и H2', ex('exercise pair only; equation added', { conditions: 't°, p, kat' })),
      R('Ca + 2HCl → Ca “?” + H2 ↑', 'Ca + 2HCl → CaCl2 + H2↑', 'substitution', 71, '1) Ca + 2HCl → Ca "?" + H2 ↑', ex('fill-in completed')),
      R('2Mg + “?”→ 2MgO', '2Mg + O2 → 2MgO', 'combination', 71, '2) 2Mg + "?"→ 2MgO', ex('fill-in completed')),
      R('2H2“?” + 3O2 → 2H2O + 2SO2', '2H2S + 3O2 → 2H2O + 2SO2', 'combustion', 71, '3) 2H2"?" + 3O2 → 2H2O + 2SO2', ex('fill-in completed')),
      R('Fe2O3 + 3H2 →2Fe + 3 “?”O', 'Fe2O3 + 3H2 → 2Fe + 3H2O', 'redox', 71, '4) Fe2O3 + 3H2 →2Fe + 3 "?"O', ex('fill-in completed', { conditions: 't°' })),
      R('CaCl2 + 2NaOH → Ca(OH)2 + 2Na“?”', 'CaCl2 + 2NaOH → Ca(OH)2↓ + 2NaCl', 'exchange', 71, '5) CaCl2 + 2NaOH → Ca(OH)2 + 2Na"?"', ex('fill-in completed')),
      R(null, 'Cu + S → CuS', 'combination', 71, 'Красный порошок меди (6,4 г) смешали с желтым порошком серы (3,2 г) и нагрели. Образовался черный порошок.', ex('described in words; equation reconstructed (1:1 molar ratio from given masses)', { conditions: 't°' })),
      R('N2 + O2 → 2NO', 'N2 + O2 → 2NO', 'combination', 71, 'При грозовых токах в атмосфере происходит следующая реакция: N2 + O2 → 2NO; 2NO + O2→ 2NO2', { conditions: 'электрический разряд (гроза)' }),
      R('2NO + O2→ 2NO2', '2NO + O2 → 2NO2', 'combination', 71, 'N2 + O2 → 2NO; 2NO + O2→ 2NO2'),
    ],
    labWorks: [],
    notes: ['p71 also lists reaction notation signs: →, ↔, ↑, ↓, hν, t°, Q, (g), (конц.), (водный).'],
  },
  'c2-s14': {
    substances: [
      S('O2', 'кислород', 'simple', 'mentioned', 72, 'Б) кислород в озон', EX),
      S('O3', 'озон', 'simple', 'mentioned', 72, 'Найдите простые вещества: воздух, вода, озон, мед, морская вода, кислород, азот.', EX),
      S('H2O', 'вода (пар, лед)', 'oxide', 'mentioned', 72, 'В) Пар в лед', EX),
      S('N2', 'азот', 'simple', 'mentioned', 72, 'воздух, вода, озон, мед, морская вода, кислород, азот', EX),
      S('NaCl', 'поваренная соль', 'salt', 'mentioned', 72, 'кислород, озон, речная вода, поваренная соль, воздух, сахар', EX),
      S('C12H22O11', 'сахар', 'organic', 'mentioned', 72, 'кислород, озон, речная вода, поваренная соль, воздух, сахар', ex('formula inferred (sucrose)')),
      S('Cr', 'хром', 'simple', 'mentioned', 72, 'Вычислите количество ещества 20,8 г элемента хрома?', EX),
      S('=CH4', 'метан', 'organic', 'mentioned', 72, 'Какова масса 6,02 ∙1023 молекул метана CH4?', EX),
      S('=Fe2O3', 'оксид железа (III)', 'oxide', 'mentioned', 72, 'Какова масса 0,25 моль оксида железа (III) – Fe2O3?', EX),
      S('Mg', 'магний', 'simple', 'mentioned', 72, 'Химику потребовался 1 моль магния для реакции.', EX),
      S('KF', 'фтор с калием', 'salt', 'mentioned', 72, 'A) фтор с калием', ex('exercise answer, not written in book')),
      S('MgO', 'магний с кислородом', 'oxide', 'mentioned', 72, 'Б) магний с кислородом', ex('exercise answer, not written in book')),
      S('CaH2', 'кальций с водородом', 'other', 'mentioned', 72, 'В) кальций с водородом', ex('exercise answer, not written in book')),
      S('AlF3', 'фтор с алюминием', 'salt', 'mentioned', 72, 'Г) фтор с алюминием', ex('exercise answer, not written in book')),
      S('Al2O3', 'алюминий с кислородом', 'oxide', 'mentioned', 72, 'Д) алюминий с кислородом', ex('exercise answer, not written in book')),
      S('=HCl', 'HCl', 'acid', 'mentioned', 72, 'A) HCl; Б) BeCl2; В) AlBr3; Г) PH3; Д) TiCl4.', EX),
      S('=BeCl2', 'BeCl2', 'salt', 'mentioned', 72, 'A) HCl; Б) BeCl2; В) AlBr3; Г) PH3; Д) TiCl4.', EX),
      S('=AlBr3', 'AlBr3', 'salt', 'mentioned', 72, 'A) HCl; Б) BeCl2; В) AlBr3; Г) PH3; Д) TiCl4.', EX),
      S('=PH3', 'PH3', 'other', 'mentioned', 72, 'A) HCl; Б) BeCl2; В) AlBr3; Г) PH3; Д) TiCl4.', EX),
      S('=TiCl4', 'TiCl4', 'salt', 'mentioned', 72, 'A) HCl; Б) BeCl2; В) AlBr3; Г) PH3; Д) TiCl4.', EX),
      S('Cr2O3', 'соединение хрома (III) с кислородом', 'oxide', 'mentioned', 72, 'Напишите формулы соединений хрома (III) и хрома (VI) с кислородом.', ex('exercise answer, not written in book')),
      S('CrO3', 'соединение хрома (VI) с кислородом', 'oxide', 'mentioned', 72, 'Напишите формулы соединений хрома (III) и хрома (VI) с кислородом.', ex('exercise answer, not written in book')),
      S('=SiO2', 'белый песок', 'oxide', 'mentioned', 72, 'Какова массовая доля кислорода в белом песке SiO2?', EX),
      ...[['Ca', 'simple'], ['CaH2', 'other'], ['Ca(OH)2', 'base']].map(([f, k]) => S('=' + f, f, k, 'mentioned', 72, 'Напишите уравнения реакций для следующих превращений. Ca → CaH2 → Ca(OH)2', EX)),
      ...[['S', 'simple'], ['SO2', 'oxide'], ['SO3', 'oxide'], ['H2SO4', 'acid'], ['CaSO4', 'salt']].map(([f, k]) => S('=' + f, f, k, 'mentioned', 72, 'S → SO2 → SO3 → H2SO4 → CaSO4', EX)),
      ...[['Fe', 'simple'], ['Cl2', 'simple'], ['FeCl3', 'salt'], ['Al', 'simple'], ['Al2S3', 'salt'], ['Cu', 'simple'], ['CuO', 'oxide']].map(([f, k]) =>
        S('=' + f, f, k, 'mentioned', 72, '1) ? Mg + O2 = 2MgO 2) ? Fe + 3Cl2 = ? FeCl3 3) ? Al + ? S = Al2S3 4) ? Cu + ?O2 = ? CuO', EX),
      ),
      S('=P2O5', 'P2O5', 'oxide', 'mentioned', 73, 'Сколько P2O5 необходимо для получения 392 кг H3PO4? фосфорной кислоты?', EX),
      S('=H3PO4', 'фосфорная кислота', 'acid', 'mentioned', 73, 'Сколько P2O5 необходимо для получения 392 кг H3PO4? фосфорной кислоты?', EX),
      S('=BaBr2', 'бромид бария', 'salt', 'mentioned', 73, 'Какое из следующих названий является правильным для BaBr2?', EX),
      S('=Al2S3', 'сульфид алюминия', 'salt', 'mentioned', 73, 'Найдите химическую формулу сульфида алюминия? ... Г) Al2S3', EX),
      S('=N2', 'азот (3N2)', 'simple', 'mentioned', 73, 'Как формула для 3N2 выражается количественно?', EX),
      S('=FeO', 'FeO', 'oxide', 'mentioned', 73, 'A) 2Fe + O2→ 2FeO', EX),
      S('=Fe3O4', 'Fe3O4', 'oxide', 'mentioned', 73, 'Б) 3Fe + 2O2→ Fe3O4', EX),
      S('=SiH4', 'SiH4', 'other', 'mentioned', 73, 'Найдите валентность кремния в SiH4.', EX),
      S('H2', 'водород', 'simple', 'mentioned', 73, 'Все перечисленные ниже элементы, кроме ..., могут существовать в виде двухатомных молекул. A) Водород Б) Кислород В) Натрий Г) Хлор', EX),
      S('=Ag', 'серебро', 'simple', 'mentioned', 73, 'Ag + S → Ag2S Какой коэффициент перед серебром (Ag) в уравнении реакции?', EX),
      S('=Ag2S', 'Ag2S', 'salt', 'mentioned', 73, 'Ag + S → Ag2S', EX),
      S('=C2H6', 'C2H6', 'organic', 'mentioned', 73, 'B) С2Н6 + O2 →', EX),
      S('=Al(OH)3', 'Al(OH)3', 'base', 'mentioned', 73, 'C) Al(OH)3 + H2SO4 →', EX),
      S('=Al2(SO4)3', 'Al2(SO4)3', 'salt', 'mentioned', 73, '4) Al2(SO4)3 + Н2О', EX),
      S('=Ca(NO3)2', 'Ca(NO3)2', 'salt', 'mentioned', 73, 'D) Ca(NO3)2 + Na3PO4 →', EX),
      S('=Na3PO4', 'Na3PO4', 'salt', 'mentioned', 73, 'D) Ca(NO3)2 + Na3PO4 →', EX),
      S('=Ca3(PO4)2', 'Са3(РО4)2', 'salt', 'mentioned', 73, '3) Са3(РО4)2 + NaNO3', EX),
      S('=NaNO3', 'NaNO3', 'salt', 'mentioned', 73, '3) Са3(РО4)2 + NaNO3', EX),
    ],
    reactions: [
      R('кислород в озон', '3O2 → 2O3', 'other', 72, 'Представьте, что у вас в руке волшебная палочка, и вы превращаете: ... Б) кислород в озон', ex('word exercise; equation reconstructed', { conditions: 'электрический разряд' })),
      R('Ca → CaH2', 'Ca + H2 → CaH2', 'combination', 72, 'Ca → CaH2 → Ca(OH)2', ex('transformation chain step; equation reconstructed', { conditions: 't°' })),
      R('CaH2 → Ca(OH)2', 'CaH2 + 2H2O → Ca(OH)2 + 2H2↑', 'redox', 72, 'Ca → CaH2 → Ca(OH)2', ex('transformation chain step; equation reconstructed')),
      R('S → SO2', 'S + O2 → SO2', 'combustion', 72, 'S → SO2 → SO3 → H2SO4 → CaSO4', ex('transformation chain step; equation reconstructed', { conditions: 't°' })),
      R('SO2 → SO3', '2SO2 + O2 ⇌ 2SO3', 'combination', 72, 'S → SO2 → SO3 → H2SO4 → CaSO4', ex('transformation chain step; equation reconstructed', { conditions: 't°, kat (V2O5)' })),
      R('SO3 → H2SO4', 'SO3 + H2O → H2SO4', 'combination', 72, 'S → SO2 → SO3 → H2SO4 → CaSO4', ex('transformation chain step; equation reconstructed')),
      R('H2SO4 → CaSO4', 'H2SO4 + Ca(OH)2 → CaSO4 + 2H2O', 'neutralization', 72, 'S → SO2 → SO3 → H2SO4 → CaSO4', ex('transformation chain step; one possible reagent (Ca(OH)2) chosen')),
      R('? Mg + O2 = 2MgO', '2Mg + O2 → 2MgO', 'combination', 72, '1) ? Mg + O2 = 2MgO', ex('coefficients to fill in; completed')),
      R('? Fe + 3Cl2 = ? FeCl3', '2Fe + 3Cl2 → 2FeCl3', 'combination', 72, '2) ? Fe + 3Cl2 = ? FeCl3', ex('coefficients to fill in; completed')),
      R('? Al + ? S = Al2S3', '2Al + 3S → Al2S3', 'combination', 72, '3) ? Al + ? S = Al2S3', ex('coefficients to fill in; completed')),
      R('? Cu + ?O2 = ? CuO', '2Cu + O2 → 2CuO', 'combination', 72, '4) ? Cu + ?O2 = ? CuO', ex('coefficients to fill in; completed')),
      R(null, 'P2O5 + 3H2O → 2H3PO4', 'combination', 73, 'Сколько P2O5 необходимо для получения 392 кг H3PO4? фосфорной кислоты?', ex('calculation problem implies this reaction; equation not printed')),
      R('2Fe + O2→ 2FeO', '2Fe + O2 → 2FeO', 'combination', 73, 'Определите правильно уравненное химическое уравнение образования оксида железа (III)? A) 2Fe + O2→ 2FeO', ex('test distractor (forms FeO, not Fe2O3); option Г "Fe + O2→ FeO" is the unbalanced version')),
      R('3Fe + 2O2→ Fe3O4', '3Fe + 2O2 → Fe3O4', 'combustion', 73, 'Б) 3Fe + 2O2→ Fe3O4', ex('test distractor')),
      R('4Fe + 3O2 → 2Fe2O3', '4Fe + 3O2 → 2Fe2O3', 'combination', 73, 'В) 4Fe + 3O2 → 2Fe2O3', ex('test: correct answer')),
      R('Ag + S → Ag2S', '2Ag + S → Ag2S', 'combination', 73, '9. Ag + S → Ag2S Какой коэффициент перед серебром (Ag) в уравнении реакции?', ex('skeleton; coefficient 2 added (answer A)')),
      R('Н2 + O2 → ... 2) Н2О', '2H2 + O2 → 2H2O', 'combination', 73, 'A) Н2 + O2 → ... 2) Н2О', ex('matching test; completed and balanced')),
      R('С2Н6 + O2 → ... 1) СО2 + Н2О', '2C2H6 + 7O2 → 4CO2 + 6H2O', 'combustion', 73, 'B) С2Н6 + O2 → ... 1) СО2 + Н2О', ex('matching test; completed and balanced')),
      R('Al(OH)3 + H2SO4 → ... 4) Al2(SO4)3 + Н2О', '2Al(OH)3 + 3H2SO4 → Al2(SO4)3 + 6H2O', 'neutralization', 73, 'C) Al(OH)3 + H2SO4 → ... 4) Al2(SO4)3 + Н2О', ex('matching test; completed and balanced')),
      R('Ca(NO3)2 + Na3PO4 → ... 3) Са3(РО4)2 + NaNO3', '3Ca(NO3)2 + 2Na3PO4 → Ca3(PO4)2↓ + 6NaNO3', 'exchange', 73, 'D) Ca(NO3)2 + Na3PO4 → ... 3) Са3(РО4)2 + NaNO3', ex('matching test; completed and balanced')),
    ],
    labWorks: [],
    elementsMentioned: ['P', 'Na', 'Si', 'N', 'H', 'O', 'Cl', 'Ag', 'K', 'Cu'],
    notes: ['p74 chapter III opener: pictures captioned ВОДОРОД, БОР, СЕРЕБРО, МАГНИЙ, ЛИТИЙ, УГЛЕРОД (elements).'],
  },
}
