// Hand-authored inventory data, grade 9 textbook (ru), §38–§41 + «Практические и лабораторные работы».
// S: [formula|null, nameRu (as in book), role, page, quoteHint, extra?]
// R: [bookTextHint|null, cleanedAsciiEquation, type, conditions, page, extra?]
// Described reactions (no equation printed in the book) carry { described: true, noEquationInBook: true }.
const D = { described: true, noEquationInBook: true }
export const DATA = {
  '38': {
    S: [
      ['H2S', 'сероводород', 'mentioned', 179, 'до 40 % сероводорода', { formulaInBook: false }],
      ['C3H8', 'пропан', 'obtained', 179, 'не только пропан и бутан', { kind: 'organic', formulaInBook: false }],
      ['C4H10', 'бутан', 'obtained', 179, 'не только пропан и бутан', { kind: 'organic', formulaInBook: false }],
      ['C2H6', 'этан', 'obtained', 179, 'а также этан', { kind: 'organic', formulaInBook: false }],
      ['S', 'сера', 'obtained', 179, 'такие элементы, как сера и гелий', { formulaInBook: false }],
      ['He', 'гелий', 'obtained', 179, 'такие элементы, как сера и гелий', { formulaInBook: false }],
      [null, 'полимеры (пластмассы, синтетические волокна, синтетические каучуки)', 'mentioned', 176, 'полимеры', { kind: 'organic', note: 'классы материалов, формулы не даны' }],
    ],
    R: [],
    L: [],
  },
  '39': {
    S: [
      ['NO', 'оксид азота(II)', 'mentioned', 181, 'такие ядовитые вещества, как NO', { note: 'загрязнитель воздуха' }],
      ['NO2', 'оксид азота(IV)', 'mentioned', 181, 'NO2, CO, SO2'],
      ['CO', 'оксид углерода(II)', 'mentioned', 181, 'NO2, CO, SO2'],
      ['SO2', 'оксид серы(IV)', 'mentioned', 181, 'NO2, CO, SO2', { aliases: ['оксиды серы'] }],
      ['Cl2', 'хлор', 'mentioned', 181, 'SO2, Cl2, H2S'],
      ['H2S', 'сероводород (сульфид водорода)', 'mentioned', 181, 'Cl2, H2S, HCl'],
      ['HCl', 'хлороводород', 'mentioned', 181, 'H2S, HCl, HCN'],
      ['HCN', 'циановодород', 'mentioned', 181, 'HCl, HCN, F2', { kind: 'acid' }],
      ['F2', 'фтор', 'mentioned', 181, 'HCN, F2, HF'],
      ['HF', 'фтороводород', 'mentioned', 181, 'F2, HF и др'],
      ['As', 'мышьяк', 'mentioned', 181, '1,5 млн т мышьяка', { formulaInBook: false }],
      ['Zn', 'цинк', 'mentioned', 181, '1,2 млн т цинка', { formulaInBook: false }],
      ['H2O', 'вода', 'studied', 181, 'Вода – самое распространенное вещество'],
      ['CaO', 'негашеная известь', 'reagent', 181, 'негашеную известь (CaO)'],
      ['Al2(SO4)3', 'сульфат алюминия', 'reagent', 181, 'затем добавляют Al2(SO4)3'],
      ['Al(OH)3', 'гидроксид алюминия (осадок)', 'obtained', 181, 'образующимся осадком Al(OH)3'],
      ['CaOCl2', 'хлорная известь', 'reagent', 181, 'обрабатывают хлорной известью', { formulaInBook: false, kind: 'salt' }],
      [null, 'полиэтилен (полиэтиленовые пленки)', 'mentioned', 181, 'полиэтиленовые пленки', { kind: 'organic' }],
      ['Na2SiO3', 'силикат натрия', 'reagent', 182, 'количество силиката натрия', { formulaInBook: false }],
      [null, 'пестициды (инсектициды, фунгициды, гербициды и др.)', 'mentioned', 182, 'Пестициды', { kind: 'other', note: 'класс веществ' }],
      ['S', 'сера', 'reagent', 183, 'обрабатывают серой', { inExercise: true, formulaInBook: false }],
      ['NaCl', 'поваренная соль', 'reagent', 183, 'с использованием поваренной соли', { inExercise: true, formulaInBook: false }],
      ['H2SO4', 'серная кислота (конц.)', 'reagent', 183, 'концентрированной серной кислоты', { inExercise: true, formulaInBook: false }],
      ['Na2SO4', 'сульфат натрия', 'obtained', 183, 'вырабатывающего сульфат натрия', { inExercise: true, formulaInBook: false }],
      ['C', 'углерод (природный уголь)', 'reagent', 184, 'содержащего 80 % углерода', { inExercise: true, formulaInBook: false }],
    ],
    R: [
      ['склад для хранения зерна обрабатывают серой, которую сжигают', 'S + O2 -> SO2', 'combustion', null, 183, { ...D, inExercise: true }],
      ['с использованием поваренной соли и концентрированной серной кислоты', '2NaCl + H2SO4 -> Na2SO4 + 2HCl', 'exchange', 't°', 183, { ...D, inExercise: true, note: 'продукт HCl в тексте не назван (отходы предприятия)' }],
      ['для сжигания 2 т природного угля', 'C + O2 -> CO2', 'combustion', null, 184, { ...D, inExercise: true }],
      ['добавляют негашеную известь (CaO), тем самым создавая щелочную среду, затем добавляют Al2(SO4)3', 'Al2(SO4)3 + 3Ca(OH)2 -> 2Al(OH)3 + 3CaSO4', 'exchange', null, 181, { ...D, note: 'очистка сточных вод: CaO + H2O → Ca(OH)2, затем осадок Al(OH)3; уравнение в книге не записано' }],
    ],
    L: [],
  },
  '40': {
    S: [
      ['Be', 'бериллий', 'mentioned', 185, 'это бериллий Be', { inWorkedExample: true }],
      ['Cl', 'хлор (элемент)', 'mentioned', 185, '3s2 — хлор Cl', { inWorkedExample: true, kind: 'simple', note: 'элемент, не простое вещество Cl2' }],
      ['Ca', 'кальций', 'mentioned', 185, '4s2 кальций Ca', { inWorkedExample: true }],
      ['B', 'бор', 'mentioned', 186, 'Природный бор', { inExercise: true, note: 'изотопы 10B и 11B' }],
      ['K', 'калий', 'mentioned', 186, 'на примере K и Ar', { inExercise: true }],
      ['Ar', 'аргон', 'mentioned', 186, 'на примере K и Ar', { inExercise: true }],
      ['CH3COOC2H5', 'уксусный этиловый эфир', 'obtained', 187, 'уксусного этило', { inExercise: true, kind: 'organic', formulaInBook: false }],
      ['C6H6Cl6', 'гексахлорциклогексан', 'obtained', 187, 'гексахлоратциклогексана', { inExercise: true, kind: 'organic', formulaInBook: false, note: 'в книге «гексахлоратциклогексан»' }],
      ['CaCO3', 'известняк', 'reagent', 187, 'с помощью извест', { inExercise: true, formulaInBook: false }],
      ['P', 'белый и красный фосфор', 'mentioned', 187, 'белый и красный фосфор', { inExercise: true, formulaInBook: false }],
      ['C6H5CH3', 'толуол (метилбензол)', 'obtained', 187, '(метилбензола)', { inExercise: true, kind: 'organic', formulaInBook: false }],
      ['C6H6', 'бензол', 'mentioned', 187, 'бензол, стирол', { inExercise: true, kind: 'organic', formulaInBook: false }],
      ['C6H5CHCH2', 'стирол', 'mentioned', 187, 'бензол, стирол', { inExercise: true, kind: 'organic', formulaInBook: false }],
      ['CH3CHO', 'уксусный альдегид', 'mentioned', 187, 'уксусный альдегид', { inExercise: true, kind: 'organic', formulaInBook: false }],
      ['CH3COOH', 'уксусная кислота', 'mentioned', 187, 'уксусная кислота, толуол', { inExercise: true, kind: 'organic', formulaInBook: false }],
      [null, 'простое стекло', 'obtained', 187, 'простого стекла', { inExercise: true, kind: 'other' }],
      ['Na', 'натрий', 'reagent', 187, 'Na K Ca Mg Al', { inExercise: true, note: 'таблица 20 (металлы × реактивы)' }],
      ['K', 'калий', 'reagent', 187, 'Na K Ca Mg Al', { inExercise: true }],
      ['Ca', 'кальций', 'reagent', 187, 'Na K Ca Mg Al', { inExercise: true }],
      ['Mg', 'магний', 'reagent', 187, 'Na K Ca Mg Al', { inExercise: true }],
      ['Al', 'алюминий', 'reagent', 187, 'Na K Ca Mg Al', { inExercise: true }],
      ['Fe', 'железо', 'reagent', 187, 'почему в реакциях 18 и 36 железо', { inExercise: true }],
      ['O2', 'кислород', 'reagent', 187, 'O2', { inExercise: true }],
      ['H2O', 'вода', 'reagent', 187, 'H2O', { inExercise: true }],
      ['HCl', 'соляная кислота', 'reagent', 187, 'HCl', { inExercise: true }],
      ['H2SO4', 'серная кислота (разб. или конц.)', 'reagent', 187, 'H2SO4', { inExercise: true }],
      ['ZnCl2', 'хлорид цинка (раствор)', 'reagent', 187, 'ZnCl2 (растворы)', { inExercise: true }],
      ['Cl2', 'хлор', 'reagent', 187, 'Cl2', { inExercise: true }],
    ],
    R: [],
    L: [],
    extraNotes: [
      'Таблица 20 (с.187): задание написать 36 уравнений «металл (Na, K, Ca, Mg, Al, Fe) × реактив (O2, H2O, HCl, H2SO4, ZnCl2 (растворы), Cl2)», реакции пронумерованы 1–36 (строки реактивов, столбцы металлов). Уравнения в книге не приведены, поэтому в reactions не включены.',
    ],
  },
  '41': {
    S: [
      ['HNO3', 'азотная кислота', 'obtained', 188, 'азотная, фосфорная и серная кислоты', { formulaInBook: false, note: 'продукция химических предприятий' }],
      ['H3PO4', 'фосфорная кислота', 'obtained', 188, 'фосфорная и серная кислоты', { formulaInBook: false }],
      ['H2SO4', 'серная кислота', 'obtained', 188, 'фосфорная и серная кислоты', { formulaInBook: false }],
      [null, 'азотные, фосфорные и калийные минеральные удобрения', 'obtained', 188, 'азотные, фо сфорные и калийные', { kind: 'salt', note: 'классы удобрений' }],
      ['C', 'уголь', 'reagent', 188, 'реакций горения угля', { formulaInBook: false }],
      ['S', 'сера', 'reagent', 188, 'горения угля, серы, колчедана', { formulaInBook: false }],
      ['FeS2', 'колчедан', 'reagent', 188, 'горения угля, серы, колчедана', { formulaInBook: false, mineral: true }],
      ['SO2', 'оксид серы(IV)', 'reagent', 189, 'окисления оксида серы(IV)', { formulaInBook: false }],
      ['N2', 'азот', 'reagent', 189, 'связывания азота с водородом', { formulaInBook: false }],
      ['H2', 'водород', 'reagent', 189, 'связывания азота с водородом', { formulaInBook: false }],
      ['NH3', 'аммиак', 'reagent', 189, 'окисления аммиака', { formulaInBook: false }],
      ['C3H6O', 'ацетон', 'mentioned', 190, 'паров ацетона', { kind: 'organic', formulaInBook: false }],
      ['F2', 'фтор', 'reagent', 190, 'H2 + F2', { inExercise: true }],
      ['HF', 'фтороводород', 'obtained', 190, '= 2HF', { inExercise: true }],
      ['NO', 'оксид азота(II)', 'reagent', 190, '2NO + O2', { inExercise: true }],
      ['O2', 'кислород', 'reagent', 190, '2NO + O2', { inExercise: true }],
      ['NO2', 'оксид азота(IV)', 'obtained', 190, '= 2NO2', { inExercise: true }],
      ['C2H4', 'этилен', 'reagent', 190, 'горения этилена', { inExercise: true, kind: 'organic' }],
      ['CO2', 'углекислый газ', 'obtained', 190, '= 2CO2', { inExercise: true }],
      ['H2O', 'вода', 'obtained', 190, '+ 2H2O', { inExercise: true }],
    ],
    R: [
      ['необратимых реакций горения угля', 'C + O2 -> CO2', 'combustion', null, 188, { ...D }],
      ['горения угля, серы', 'S + O2 -> SO2', 'combustion', null, 188, { ...D }],
      ['серы, колчедана', '4FeS2 + 11O2 -> 2Fe2O3 + 8SO2', 'combustion', 't°', 188, { ...D, note: 'обжиг колчедана' }],
      ['окисления оксида серы(IV)', '2SO2 + O2 <=> 2SO3', 'redox', 'kat, t°', 189, { ...D, note: 'обратимая реакция' }],
      ['связывания азота с водородом', 'N2 + 3H2 <=> 2NH3', 'combination', 'kat, t°, p', 189, { ...D, note: 'обратимая реакция' }],
      ['окисления аммиака', '4NH3 + 5O2 -> 4NO + 6H2O', 'redox', 'kat (Pt), t°', 189, { ...D, note: 'в тексте названа обратимой; продукт (NO) не назван' }],
      ['H2 + F2 = 2HF', 'H2 + F2 -> 2HF', 'combination', null, 190, { inExercise: true }],
      ['2NO + O2 = 2NO2', '2NO + O2 -> 2NO2', 'combination', null, 190, { inExercise: true }],
      ['C2H4 + 3O2 = 2CO2 + 2H2O', 'C2H4 + 3O2 -> 2CO2 + 2H2O', 'combustion', null, 190, { inExercise: true }],
    ],
    L: [],
  },
  lab: {
    S: [
      // Практическая работа 1
      ['CO2', 'оксид углерода(IV)', 'obtained', 191, 'Получение оксида углерода(IV)'],
      ['CaCO3', 'мел или мрамор', 'reagent', 191, 'кусочков мела или мрамора', { formulaInBook: false }],
      ['HCl', 'соляная кислота', 'reagent', 191, 'налейте немного соляной кислоты', { formulaInBook: false }],
      ['Ca(OH)2', 'известковая вода', 'reagent', 191, 'известковой воды', { formulaInBook: false }],
      ['H2O', 'дистиллированная вода', 'reagent', 191, 'дистиллированной водой'],
      [null, 'лакмус (синий)', 'reagent', 191, 'синего лакмуса', { kind: 'organic', note: 'индикатор' }],
      ['NaOH', 'едкий натр (гидроксид натрия)', 'reagent', 191, 'едкого натрия', { formulaInBook: false }],
      [null, 'фенолфталеин', 'reagent', 191, 'фенолфталеина', { kind: 'organic', note: 'индикатор' }],
      ['AgNO3', 'нитрат серебра', 'reagent', 191, 'раствора нитрата серебра', { formulaInBook: false }],
      ['AgCl', 'хлорид серебра (белый осадок)', 'obtained', 191, 'белый осадок', { formulaInBook: false, note: 'по смыслу опыта (хлориды почвы)' }],
      ['NH3', 'аммиак (раствор)', 'reagent', 191, 'или аммиака', { formulaInBook: false }],
      // Практическая работа 2
      ['NaCl', 'хлорид натрия', 'reagent', 192, 'a) хлорид натрия', { formulaInBook: false }],
      ['Na2CO3', 'карбонат натрия', 'reagent', 192, 'в) карбонат натрия', { formulaInBook: false }],
      ['NaNO3', 'нитрат натрия', 'reagent', 192, 'г) нитрат натрия', { formulaInBook: false }],
      ['K2CO3', 'карбонат калия', 'reagent', 192, 'a) карбонат калия', { formulaInBook: false }],
      ['KCl', 'хлорид калия', 'reagent', 192, 'в) хлорид калия', { formulaInBook: false }],
      ['CaCl2', 'хлорид кальция', 'reagent', 192, 'г) хлорид кальция', { formulaInBook: false }],
      ['KOH', 'гидроксид калия', 'reagent', 192, 'раствор гидроксида калия', { formulaInBook: false }],
      ['Ca(HCO3)2', 'гидрокарбонат кальция', 'obtained', 192, 'CaCO3  Ca(HCO3)2'],
      // Практическая работа 3
      ['Al2(SO4)3', 'сульфат алюминия', 'reagent', 193, 'в) сульфат алюминия', { formulaInBook: false }],
      ['FeCl3', 'хлорид железа(III)', 'reagent', 193, 'г) хлорид железа(III)', { formulaInBook: false }],
      ['CuO', 'оксид меди(II)', 'obtained', 193, 'получить оксид меди(II)', { formulaInBook: false }],
      ['ZnCl2', 'хлорид цинка', 'obtained', 193, 'Получите соль хлорид цинка', { formulaInBook: false }],
      // Лабораторная работа 1
      ['MgCO3', 'карбонат магния', 'reagent', 194, 'другую карбонат магния', { formulaInBook: false }],
      ['H2SO4', 'серная кислота (разб.)', 'reagent', 194, 'разбавленной серной кислоты', { formulaInBook: false }],
      ['CO3^2-', 'карбонат-ион', 'studied', 194, 'характерная для карбонат-иона', { kind: 'other' }],
      // Лабораторные работы 2–5
      [null, 'природные силикаты', 'studied', 195, 'образцами природных силикатов', { kind: 'salt' }],
      [null, 'стекла', 'studied', 195, 'видами и составом стекол', { kind: 'other' }],
      ['Fe', 'железо (пластинка)', 'reagent', 195, 'пластинки из железа и меди', { formulaInBook: false }],
      ['Cu', 'медь (пластинка, проволока, опилки)', 'reagent', 195, 'пластинки из железа и меди', { formulaInBook: false }],
      [null, 'парафин', 'reagent', 196, 'кусок парафина', { kind: 'organic' }],
      // Лабораторная работа 6
      ['CuSO4', 'сульфат меди(II)', 'reagent', 196, 'во вторую – сульфата меди(II)', { formulaInBook: false }],
      ['Pb(NO3)2', 'нитрат свинца(II)', 'reagent', 196, 'в третью – нитрата свинца(II)', { formulaInBook: false }],
      // Лабораторная работа 7
      ['CuCl2', 'хлорид меди(II)', 'reagent', 197, 'раствор хлорида меди(II)', { formulaInBook: false }],
      ['C', 'графит (электрод)', 'reagent', 197, 'графитовый электроды', { formulaInBook: false }],
      ['Cl2', 'хлор', 'obtained', 197, 'Какой газ выделяется', { formulaInBook: false, note: 'газ на аноде (по смыслу)' }],
      ['KI', 'йодид калия', 'reagent', 197, 'раствор йодида калия', { formulaInBook: false }],
      ['H2', 'водород', 'obtained', 197, 'водородные пузырьки', { formulaInBook: false }],
      ['I2', 'йод', 'obtained', 197, 'на аноде выделяется йод', { formulaInBook: false }],
      [null, 'крахмал (раствор)', 'reagent', 197, 'раствора крахмала', { kind: 'organic' }],
      // Лабораторные работы 8–11
      ['Al', 'алюминий', 'reagent', 197, 'кусочки алюминия', { formulaInBook: false }],
      ['Al(NO3)3', 'нитрат алюминия', 'reagent', 198, 'раствора нитрата алюминия', { formulaInBook: false }],
      ['Al(OH)3', 'гидроксид алюминия', 'obtained', 198, 'осадок гидроксида алюминия', { formulaInBook: false }],
      ['AlCl3', 'хлорид алюминия', 'reagent', 199, 'раствора хлорида алюминия', { formulaInBook: false }],
      // Лабораторная работа 12
      ['Cu(OH)2', 'гидроксид меди(II)', 'obtained', 199, 'Получение гидроксида меди(II)', { formulaInBook: false }],
      // Лабораторная работа 13
      ['ZnSO4', 'сульфат цинка', 'reagent', 200, 'соли сульфат цинка', { note: 'в схеме «ZnSO4→» с NaOH и H2SO4' }],
      ['Zn(OH)2', 'гидроксид цинка', 'obtained', 200, 'Получение гидроксида цинка', { formulaInBook: false }],
      // Лабораторная работа 14
      ['CrCl2', 'хлорид хрома(II)', 'reagent', 201, 'раствора хлорида хрома(II)', { formulaInBook: false }],
      ['Cr(OH)2', 'гидроксид хрома(II) (желтый осадок)', 'obtained', 201, 'желтый осадок', { formulaInBook: false }],
      ['Cr2O3', 'оксид хрома(III)', 'reagent', 201, 'Оксид хрома(III) – вещество зеленого цвета', { formulaInBook: false }],
      ['K2Cr2O7', 'бихромат калия', 'reagent', 201, 'раствору бихромата калия', { formulaInBook: false }],
      ['Na2SO3', 'сульфит натрия', 'reagent', 201, 'сульфита натрия (Na2SO3)'],
      // Лабораторные работы 15–16
      ['FeSO4', 'сульфат железа(II)', 'reagent', 201, 'соли сульфат железа(II)'],
      ['Fe(OH)2', 'гидроксид железа(II)', 'obtained', 202, 'гидроксиды железа Fe(OH)2 и Fe(OH)3'],
      ['Fe(OH)3', 'гидроксид железа(III)', 'obtained', 202, 'Fe(OH)2 и Fe(OH)3'],
      ['K3[Fe(CN)6]', 'красная кровяная соль', 'reagent', 202, 'красной кровяной соли K3[Fe(CN)6]', { kind: 'salt' }],
      ['Fe3[Fe(CN)6]2', 'турнбулева синь', 'obtained', 202, 'турнбулевой сини Fe3[Fe(CN)6]2', { kind: 'salt' }],
      ['K4[Fe(CN)6]', 'желтая кровяная соль', 'reagent', 202, 'желтой кровяной соли K4[Fe(CN)6]', { kind: 'salt' }],
      ['Fe4[Fe(CN)6]3', 'берлинская лазурь', 'obtained', 202, 'берлинской лазури Fe4[Fe(CN)6]3', { kind: 'salt' }],
      ['NH4SCN', 'роданид аммония', 'reagent', 202, 'роданида аммония или ка лия', { formulaInBook: false }],
      ['KSCN', 'роданид калия', 'reagent', 202, 'роданида аммония или ка лия', { formulaInBook: false }],
      ['Fe(SCN)3', 'роданид железа(III)', 'obtained', 202, 'роданида железа(III)Fe(SCN)3'],
      ['Fe^2+', 'ионы Fe2+', 'mentioned', 202, 'Fe2+ ионов', { kind: 'other' }],
      ['Fe^3+', 'ион Fe3+', 'mentioned', 202, 'на ион Fe3+', { kind: 'other' }],
      // Лабораторная работа 17
      [null, 'чугун', 'studied', 203, 'образцами чугуна и стали', { kind: 'other', note: 'сплав' }],
      [null, 'сталь', 'studied', 203, 'образцами чугуна и стали', { kind: 'other', note: 'сплав' }],
      ['FeCl2', 'хлорид железа(II)', 'obtained', 203, 'разбавленной соляной кислоты', { formulaInBook: false, note: 'по смыслу опыта ЛР17' }],
    ],
    R: [
      // ПР1
      ['кусочков мела или мрамора и налейте немного соляной кислоты', 'CaCO3 + 2HCl -> CaCl2 + H2O + CO2', 'exchange', null, 191, { ...D, labWork: 'ПР1' }],
      ['пробирку с 2–3 мл известковой воды', 'Ca(OH)2 + CO2 -> CaCO3 + H2O', 'exchange', null, 191, { ...D, labWork: 'ПР1' }],
      ['газ проходит через дистиллированную воду', 'CO2 + H2O <=> H2CO3', 'combination', null, 191, { ...D, labWork: 'ПР1', note: 'проверка лакмусом' }],
      ['разбавленного раствора едкого натрия и несколько капель фенолфталеина', 'CO2 + 2NaOH -> Na2CO3 + H2O', 'neutralization', null, 191, { ...D, labWork: 'ПР1' }],
      // ПР2 / ЛР1
      ['Ca(OH)2  CaCO3  Ca(HCO3)2  CaCO3  CaCl2', 'CaCO3 + CO2 + H2O -> Ca(HCO3)2', 'combination', null, 192, { ...D, labWork: 'ПР2, ЛР1', note: 'цепочка превращений и опыт 5; то же в ЛР1 (с.194)' }],
      ['долейте в первую пробирку известковую воду', 'Ca(HCO3)2 + Ca(OH)2 -> 2CaCO3 + 2H2O', 'exchange', null, 192, { ...D, labWork: 'ПР2' }],
      ['долейте во вторую пробирку раствор карбоната натрия', 'Ca(HCO3)2 + Na2CO3 -> CaCO3 + 2NaHCO3', 'exchange', null, 192, { ...D, labWork: 'ПР2' }],
      ['третью пробирку нагрейте', 'Ca(HCO3)2 -> CaCO3 + H2O + CO2', 'decomposition', 't°', 192, { ...D, labWork: 'ПР2, ЛР1' }],
      ['CaCO3  CaCl2', 'CaCO3 + 2HCl -> CaCl2 + H2O + CO2', 'exchange', null, 192, { ...D, labWork: 'ПР2', note: 'последнее звено цепочки' }],
      // ЛР1 II
      ['Налейте в первую пробирку 1–2 мл разбавленной соляной кислоты, а во вторую – такое же количество разбавленной серной кислоты', 'MgCO3 + H2SO4 -> MgSO4 + H2O + CO2', 'exchange', null, 194, { ...D, labWork: 'ЛР1' }],
      ['какая из реакций характерна для карбонат-иона', 'CO3^2- + 2H^+ -> H2O + CO2', 'exchange', null, 194, { ...D, isIonic: true, labWork: 'ЛР1', note: 'качественная реакция на карбонат-ион' }],
      // ЛР6
      ['Положите в первую пробирку медную проволоку', 'Cu + 2AgNO3 -> Cu(NO3)2 + 2Ag', 'substitution', null, 196, { ...D, labWork: 'ЛР6' }],
      ['во вторую – железные опилки', 'Fe + CuSO4 -> FeSO4 + Cu', 'substitution', null, 196, { ...D, labWork: 'ЛР6', note: 'третья пробирка: Pb(NO3)2 + медные опилки — реакции не ожидается (Cu правее Pb в ряду активности)' }],
      // ЛР7
      ['Проследите, как на катоде выделяется медь', 'CuCl2 -> Cu + Cl2', 'redox', 'электролиз раствора', 197, { ...D, labWork: 'ЛР7', note: 'с инертным анодом; с медным анодом медь растворяется: Cu − 2e → Cu2+' }],
      ['на катоде образуются водородные пузырьки, а на аноде выделяется йод', '2KI + 2H2O -> H2 + I2 + 2KOH', 'redox', 'электролиз раствора', 197, { ...D, labWork: 'ЛР7' }],
      // ЛР8
      ['В первую пробирку налейте раствор соляной кислоты', '2Al + 6HCl -> 2AlCl3 + 3H2', 'substitution', null, 197, { ...D, labWork: 'ЛР8' }],
      ['Во вторую пробирку налейте раствор едкого натрия', '2Al + 2NaOH + 6H2O -> 2Na[Al(OH)4] + 3H2', 'redox', null, 197, { ...D, labWork: 'ЛР8' }],
      // ЛР10
      ['При этом образуется осадок гидроксида алюминия', 'Al(NO3)3 + 3NaOH -> Al(OH)3 + 3NaNO3', 'exchange', null, 198, { ...D, labWork: 'ЛР10' }],
      ['налейте в одну 6 капель 1 M раствора соляной кислоты', 'Al(OH)3 + 3HCl -> AlCl3 + 3H2O', 'neutralization', null, 198, { ...D, labWork: 'ЛР10' }],
      ['такое же количество 1 M раствора едкого натрия', 'Al(OH)3 + NaOH -> Na[Al(OH)4]', 'combination', null, 198, { ...D, labWork: 'ЛР10' }],
      // ЛР11
      ['поэтапное уравнение гидролиза раствора хлорида алюминия', 'AlCl3 + H2O <=> AlOHCl2 + HCl', 'hydrolysis', null, 199, { ...D, labWork: 'ЛР11', note: '1-я ступень; далее AlOHCl2 → Al(OH)2Cl → Al(OH)3' }],
      // ЛР12
      ['постепенно долейте 1–2 мл раствора гидроксида натрия', 'CuSO4 + 2NaOH -> Cu(OH)2 + Na2SO4', 'exchange', null, 199, { ...D, labWork: 'ЛР12' }],
      ['воздействуйте на осадок соляной кислотой', 'Cu(OH)2 + 2HCl -> CuCl2 + 2H2O', 'neutralization', null, 199, { ...D, labWork: 'ЛР12' }],
      ['медленно нагрейте его', 'Cu(OH)2 -> CuO + H2O', 'decomposition', 't°', 199, { ...D, labWork: 'ЛР12' }],
      // ЛР13
      ['добавьте к нему 5 мл 10%-ного раствора гидроксида натрия', 'ZnSO4 + 2NaOH -> Zn(OH)2 + Na2SO4', 'exchange', null, 200, { ...D, labWork: 'ЛР13' }],
      ['В одну из пробирок налейте раствор серной кислоты', 'Zn(OH)2 + H2SO4 -> ZnSO4 + 2H2O', 'neutralization', null, 200, { ...D, labWork: 'ЛР13' }],
      ['в другую – раствор гидроксида натрия', 'Zn(OH)2 + 2NaOH -> Na2[Zn(OH)4]', 'combination', null, 200, { ...D, labWork: 'ЛР13' }],
      // ЛР14
      ['добавьте к нему такое же количество раствора едкого натрия', 'CrCl2 + 2NaOH -> Cr(OH)2 + 2NaCl', 'exchange', null, 201, { ...D, labWork: 'ЛР14' }],
      ['Прилейте к осадку раствор серной кислоты', 'Cr(OH)2 + H2SO4 -> CrSO4 + 2H2O', 'neutralization', null, 201, { ...D, labWork: 'ЛР14' }],
      ['добавьте к нему раствор серной кислоты (до полного растворения оксида)', 'Cr2O3 + 3H2SO4 -> Cr2(SO4)3 + 3H2O', 'exchange', null, 201, { ...D, labWork: 'ЛР14' }],
      ['трехвалентной соли хрома понемногу приливайте раствор едкого натрия', 'Cr2(SO4)3 + 6NaOH -> 2Cr(OH)3 + 3Na2SO4', 'exchange', null, 201, { ...D, labWork: 'ЛР14', note: 'в избытке щелочи — Na3[Cr(OH)6]' }],
      ['добавьте к этой смеси раствор сульфита натрия (Na2SO3)', 'K2Cr2O7 + 3Na2SO3 + 4H2SO4 -> Cr2(SO4)3 + 3Na2SO4 + K2SO4 + 4H2O', 'redox', null, 201, { ...D, labWork: 'ЛР14', note: 'уравнение приведено в §32 (с.149)' }],
      // ЛР15
      ['раствора соли сульфат железа(II) и добавьте к нему небольшое количество раствора едкого натрия', 'FeSO4 + 2NaOH -> Fe(OH)2 + Na2SO4', 'exchange', null, 201, { ...D, labWork: 'ЛР15' }],
      ['К образовавшемуся осадку понемногу добавляйте раствор соляной кислоты', 'Fe(OH)2 + 2HCl -> FeCl2 + 2H2O', 'neutralization', null, 202, { ...D, labWork: 'ЛР15' }],
      ['раствора хлорида железа(III) и добавьте к нему небольшое количество раствора едкого натрия', 'FeCl3 + 3NaOH -> Fe(OH)3 + 3NaCl', 'exchange', null, 202, { ...D, labWork: 'ЛР15' }],
      ['добавляйте раствор серной кислоты', '2Fe(OH)3 + 3H2SO4 -> Fe2(SO4)3 + 6H2O', 'neutralization', null, 202, { ...D, labWork: 'ЛР15' }],
      // ЛР16
      ['турнбулевой сини Fe3[Fe(CN)6]2', '3FeSO4 + 2K3[Fe(CN)6] -> Fe3[Fe(CN)6]2 + 3K2SO4', 'exchange', null, 202, { ...D, labWork: 'ЛР16', note: 'в книге «Эта реакция не считается качественной…» — вероятно, ошибка перевода' }],
      ['берлинской лазури Fe4[Fe(CN)6]3', '4FeCl3 + 3K4[Fe(CN)6] -> Fe4[Fe(CN)6]3 + 12KCl', 'exchange', null, 202, { ...D, labWork: 'ЛР16' }],
      ['роданида железа(III)Fe(SCN)3', 'FeCl3 + 3NH4SCN -> Fe(SCN)3 + 3NH4Cl', 'exchange', null, 202, { ...D, labWork: 'ЛР16', note: 'или с KSCN' }],
      // ЛР17
      ['Добавьте в пробирки по 2–4 мл разбавленной соляной кислоты и медленно нагрейте', 'Fe + 2HCl -> FeCl2 + H2', 'substitution', 't°', 203, { ...D, labWork: 'ЛР17' }],
    ],
    L: [
      { title: 'Практическая работа 1. Получение оксида углерода(IV) и знакомство с его свойствами', page: 191, substances: ['CaCO3', 'HCl', 'CO2', 'Ca(OH)2', 'H2O', 'NaOH', 'AgNO3', 'NH3'], indicators: ['лакмус', 'фенолфталеин'] },
      { title: 'Практическая работа 2. Решение опытных задач по темам «Щелочные металлы» и «Кальций»', page: 192, substances: ['NaCl', 'NaOH', 'Na2CO3', 'NaNO3', 'K2CO3', 'CaCO3', 'KCl', 'CaCl2', 'KOH', 'Ca(OH)2', 'Ca(HCO3)2', 'CO2'] },
      { title: 'Практическая работа 3. Решение опытных задач по теме «Металлы»', page: 193, substances: ['NaOH', 'CaCO3', 'Al2(SO4)3', 'FeCl3', 'CuO', 'ZnCl2'] },
      { title: 'Лабораторная работа 1. Знакомство со свойствами карбонатов и гидрокарбонатов и их взаимопревращениями; качественная реакция на карбонат-ион', page: 194, substances: ['CO2', 'Ca(OH)2', 'Ca(HCO3)2', 'CaCO3', 'MgCO3', 'HCl', 'H2SO4'] },
      { title: 'Лабораторная работа 2. Знакомство с образцами природных силикатов', page: 195, substances: [] },
      { title: 'Лабораторная работа 3. Знакомство с видами и составом стекол. Знакомство и работа со сборником «Стекло и изделия из него»', page: 195, substances: [] },
      { title: 'Лабораторная работа 4. Знакомство с образцами металлов', page: 195, substances: ['Fe', 'Cu'], other: ['парафин'] },
      { title: 'Лабораторная работа 5. Знакомство с образцами сплавов', page: 196, substances: [] },
      { title: 'Лабораторная работа 6. Взаимодействие растворов солей и металлов', page: 196, substances: ['AgNO3', 'CuSO4', 'Pb(NO3)2', 'Cu', 'Fe'] },
      { title: 'Лабораторная работа 7. Электролиз растворов хлорида меди(II) и йодида калия', page: 197, substances: ['CuCl2', 'Cu', 'C', 'Cl2', 'KI', 'H2', 'I2'], other: ['крахмал'] },
      { title: 'Лабораторная работа 8. Взаимодействие алюминия с растворами кислот и оснований', page: 197, substances: ['Al', 'HCl', 'NaOH'] },
      { title: 'Лабораторная работа 9. Знакомство с алюминием и образцами его сплавов', page: 198, substances: ['Al'] },
      { title: 'Лабораторная работа 10. Получение гидроксида алюминия, изучение его взаимодействия с кислотами и щелочами', page: 198, substances: ['Al(NO3)3', 'NaOH', 'Al(OH)3', 'HCl'] },
      { title: 'Лабораторная работа 11. Изучение воздействия растворов солей алюминия на индикаторы', page: 199, substances: ['AlCl3', 'H2O'], indicators: ['лакмус'] },
      { title: 'Лабораторная работа 12. Получение гидроксида меди(II) из двухвалентных солей меди и проведение опытов с его участием', page: 199, substances: ['CuSO4', 'NaOH', 'Cu(OH)2', 'HCl', 'CuO'] },
      { title: 'Лабораторная работа 13. Получение гидроксида цинка из водорастворимых солей цинка и доказательство его амфотерных свойств', page: 200, substances: ['ZnSO4', 'NaOH', 'Zn(OH)2', 'H2SO4'] },
      { title: 'Лабораторная работа 14. Двух-, трех- и шестивалентные соединения хрома', page: 201, substances: ['CrCl2', 'NaOH', 'Cr(OH)2', 'H2SO4', 'Cr2O3', 'K2Cr2O7', 'Na2SO3'] },
      { title: 'Лабораторная работа 15. Получение гидроксидов железа(II) и (III)', page: 201, substances: ['FeSO4', 'NaOH', 'Fe(OH)2', 'HCl', 'FeCl3', 'Fe(OH)3', 'H2SO4'] },
      { title: 'Лабораторная работа 16. Определение солей двух- и трехвалентного железа', page: 202, substances: ['FeSO4', 'K3[Fe(CN)6]', 'Fe3[Fe(CN)6]2', 'FeCl3', 'K4[Fe(CN)6]', 'Fe4[Fe(CN)6]3', 'NH4SCN', 'KSCN', 'Fe(SCN)3'] },
      { title: 'Лабораторная работа 17. Знакомство с образцами чугуна и стали', page: 203, substances: ['Fe', 'HCl'], other: ['чугун', 'сталь'] },
    ],
  },
}
