// Hand-authored inventory data, grade 9 textbook (ru), §25–§27 (aluminium).
// S: [formula|null, nameRu (as in book), role, page, quoteHint, extra?]
// R: [bookTextHint|null, cleanedAsciiEquation, type, conditions, page, extra?]
export const DATA = {
  '25': {
    S: [
      ['Al', 'алюминий', 'studied', 121, 'Химический символ – Al'],
      ['Al2O3*2SiO2*2H2O', 'каолин (белая глина)', 'mentioned', 122, 'Kaoлин Al2O3.2SiO2.2H2O', { mineral: true }],
      ['Al2O3', 'корунд (оксид алюминия)', 'studied', 122, 'кoрунд Al2O3', { mineral: true, aliases: ['оксид алюминия'] }],
      ['Al2O3*nH2O', 'боксит', 'mentioned', 122, 'бокситы — Al2O3. nH2O', { mineral: true, kind: 'oxide', note: 'переменный состав (n)' }],
      ['AlCl3', 'хлорид алюминия', 'mentioned', 122, 'AlCl3', { note: 'в инфографике как сырье для получения Al' }],
      ['K2O*Al2O3*6SiO2', 'ортоклаз (полевой шпат)', 'mentioned', 122, 'полевой шпат K2O.Al2O3.6SiO2', { mineral: true, kind: 'salt', aliases: ['полевой шпат'], note: 'в книге также KAl2[Al2Si3O10]2·(OH)4 (так в тексте)' }],
      ['Na2O*Al2O3*2SiO2', 'нефелин', 'mentioned', 122, 'нефелин Na2O.Al2O3. 2SiO2', { mineral: true, kind: 'salt', note: 'в тексте также (Na,K)2O·Al2O3·2SiO2 или (K,Na)[AlSiO4]' }],
      ['K2O*2H2O*3Al2O3*6SiO2', 'слюда', 'mentioned', 122, 'слюды K2O .2H2O. 3Al2O3. 6SiO2', { mineral: true, kind: 'salt', note: 'в книге также KAl2(AlSi3O10)(OH)2' }],
      ['AlH3', 'гидрид алюминия', 'mentioned', 122, 'AlH3', { note: 'в инфографике только формула' }],
      ['Na[Al(OH)4]', 'тетрагидроксоалюминат натрия', 'mentioned', 122, 'Na[Al(OH)4]', { kind: 'salt', note: 'в инфографике только формула' }],
      ['Al(OH)3', 'гидроксид алюминия', 'mentioned', 122, 'Al(OH)3', { note: 'в инфографике только формула' }],
      ['Al2S3', 'сульфид алюминия', 'mentioned', 122, 'Al2S3', { note: 'в инфографике только формула' }],
      ['AlN', 'нитрид алюминия', 'mentioned', 122, 'AlN', { note: 'в инфографике только формула' }],
      ['Al2(SO4)3', 'сульфат алюминия', 'mentioned', 122, 'Al2(SO4)3', { note: 'в инфографике только формула' }],
      ['Na3AlF6', 'криолит', 'reagent', 123, 'криолите (Na3AlF6)', { mineral: true }],
      ['AlF3', 'фторид алюминия', 'reagent', 123, 'фторида алюминия', { formulaInBook: false }],
      ['Al^3+', 'ион алюминия', 'mentioned', 123, 'Al3+ + 3ē', { kind: 'other' }],
      ['O^2-', 'оксид-ион', 'mentioned', 123, '2O2– – 4ē', { kind: 'other' }],
      ['O2', 'кислород', 'obtained', 123, 'на аноде – кислород'],
      ['C', 'углерод (угольный анод)', 'reagent', 123, 'изготовленным из углерода'],
      ['CO', 'оксид углерода(II)', 'obtained', 123, 'O2 + 2C → CO', { note: 'только формула в уравнении' }],
      ['F2', 'фтор', 'mentioned', 124, 'выделяются фтор и его соединения', { formulaInBook: false }],
    ],
    R: [
      ['Al3+ + 3ē → Al0', 'Al^3+ + 3e^- -> Al', 'redox', 'электролиз, катод', 123, { isIonic: true, note: 'катодный процесс при электролизе Al2O3 в расплаве криолита' }],
      ['2O2– – 4ē → O20', '2O^2- -> O2 + 4e^-', 'redox', 'электролиз, анод', 123, { isIonic: true, note: 'в книге: 2O2– – 4ē → O2⁰' }],
      ['O2 + 2C → CO', 'O2 + 2C -> 2CO', 'redox', '800–1000 °C', 123, { note: 'в книге «O2 + 2C → CO» без коэффициента 2 перед CO (не уравнено); исправлено' }],
    ],
    L: [],
  },
  '26': {
    S: [
      ['Al', 'алюминий', 'studied', 124, 'Свойства алюминия'],
      ['O2', 'кислород', 'reagent', 124, '4Al + 3O2'],
      ['Al2O3', 'оксид алюминия (оксидная пленка)', 'obtained', 124, '4Al + 3O2 → 2Al2O3'],
      ['H2O', 'вода', 'reagent', 125, 'взаимодействует с водой'],
      ['Al(OH)3', 'гидроксид алюминия', 'obtained', 125, '2Al(OH)3 + 3H2'],
      ['H2', 'водород', 'obtained', 125, 'выделяется водород'],
      ['HCl', 'соляная кислота', 'reagent', 125, 'с соляной и разбавленной серной кислотами'],
      ['H2SO4', 'серная кислота (разбавленная)', 'reagent', 125, 'разбавленной серной кислотами', { formulaInBook: false }],
      ['AlCl3', 'хлорид алюминия', 'obtained', 125, '2AlCl3 (хлорид алюминия)'],
      ['HNO3', 'азотная кислота', 'reagent', 125, 'концентрированной азотной кислотой'],
      ['Al(NO3)3', 'нитрат алюминия', 'obtained', 125, 'Al(NO3)3 + NO'],
      ['NO', 'оксид азота(II)', 'obtained', 125, 'Al(NO3)3 + NO'],
      ['NH4NO3', 'нитрат аммония', 'obtained', 125, '3NH4NO3'],
      ['NaOH', 'щелочь (гидроксид натрия)', 'reagent', 125, 'с растворами щелочей', { aliases: ['едкий натрий'] }],
      ['Na[Al(OH)4]', 'тетрагидроксоалюминат натрия', 'obtained', 125, 'тeтрaгидроксоалюминат натрия', { kind: 'salt' }],
      ['N2', 'азот', 'reagent', 125, '2Al + N2'],
      ['AlN', 'нитрид алюминия', 'obtained', 125, 'нитрид алюминия'],
      ['P', 'фосфор', 'reagent', 125, 'Al + P'],
      ['AlP', 'фосфид алюминия', 'obtained', 125, 'фосфид алюминия'],
      ['S', 'сера', 'reagent', 125, '2Al + 3S'],
      ['Al2S3', 'сульфид алюминия', 'obtained', 125, 'сульфид алюминия'],
      ['C', 'углерод', 'reagent', 125, '4Al + 3C'],
      ['Al4C3', 'карбид алюминия', 'obtained', 125, 'карбид алюминия'],
      ['Cl2', 'хлор', 'reagent', 125, '2Al + 3Cl2'],
      ['Fe3O4', 'оксид железа(II, III) (железная окалина)', 'reagent', 125, 'оксидами железа(II, III)', { aliases: ['угар железа'] }],
      ['Fe', 'железо', 'obtained', 125, '4Al2O3 + 9Fe'],
      [null, 'термит (смесь алюминия с угаром железа)', 'mentioned', 126, 'называемая термитом', { kind: 'other', note: 'смесь Al + Fe3O4' }],
      [null, 'хром, марганец, ванадий, цирконий, титан (алюминотермия)', 'mentioned', 126, 'для получения хрома, марганца, ванадия', { kind: 'simple', note: 'металлы, получаемые алюминотермией (Cr, Mn, V, Zr, Ti), формулы не даны' }],
      ['Cr2O3', 'оксид хрома (III)', 'mentioned', 126, 'оксида хрома (III)', { inExercise: true, formulaInBook: false }],
      ['Cu', 'медь', 'mentioned', 126, 'сплава алюминия и меди', { inExercise: true }],
      ['K', 'калий (металлический)', 'reagent', 126, 'AlCl3 + 3K', { inExercise: true }],
      ['KCl', 'хлорид калия', 'obtained', 126, '3KCl + Al', { inExercise: true }],
      ['NaCl', 'хлорид натрия', 'obtained', 127, 'NaCl + AlCl3', { inWorkedExample: true }],
      ['NaAlO2', 'алюминат натрия', 'obtained', 127, 'алюминат натрия', { inWorkedExample: true }],
      ['Na2SO4', 'сульфат натрия', 'obtained', 127, 'Na2SO4 + Al2(SO4)3', { inWorkedExample: true }],
      ['Al2(SO4)3', 'сульфат алюминия', 'obtained', 127, 'сульфат алюминия', { inWorkedExample: true }],
      ['Al2(SO4)3*18H2O', 'кристаллогидрат сульфата алюминия', 'mentioned', 128, 'Ответ: Al2(SO4)3 ∙ 18H2O', { inWorkedExample: true }],
      ['Al2O3*2SiO2*2H2O', 'каолин', 'mentioned', 129, 'каолина: Al2O3∙ 2SiO2∙ 2H2O', { inExercise: true, mineral: true }],
    ],
    R: [
      ['4Al + 3O2 → 2Al2O3', '4Al + 3O2 -> 2Al2O3', 'combination', null, 124],
      ['2Al + 6H2O → 2Al(OH)3 + 3H2', '2Al + 6H2O -> 2Al(OH)3 + 3H2', 'substitution', null, 125, { note: 'после удаления оксидной пленки' }],
      ['2Al + 6HCl → 2AlCl3 + 3H2', '2Al + 6HCl -> 2AlCl3 + 3H2', 'substitution', 't°', 125, { note: '«при нагревании»' }],
      ['Al + 4HNO3 = Al(NO3)3 + NO + 2H2O', 'Al + 4HNO3 -> Al(NO3)3 + NO + 2H2O', 'redox', null, 125, { note: 'разбавленная HNO3' }],
      ['8Al + 30HNO3 = 8Al(NO3)3 + 3NH4NO3 + 9H2O', '8Al + 30HNO3 -> 8Al(NO3)3 + 3NH4NO3 + 9H2O', 'redox', null, 125, { note: 'очень разбавленная HNO3' }],
      ['2Al + 2NaOH + 6H2O → 2Na[Al(OH)4] + 3H2', '2Al + 2NaOH + 6H2O -> 2Na[Al(OH)4] + 3H2', 'redox', null, 125],
      ['2Al + N2 → 2AlN', '2Al + N2 -> 2AlN', 'combination', 't°', 125],
      ['Al + P → AlP', 'Al + P -> AlP', 'combination', 't°', 125],
      ['2Al + 3S → Al2S3', '2Al + 3S -> Al2S3', 'combination', 't°', 125],
      ['4Al + 3C → Al4C3', '4Al + 3C -> Al4C3', 'combination', 't°', 125],
      ['2Al + 3Cl2 → 2AlCl3', '2Al + 3Cl2 -> 2AlCl3', 'combination', 't°', 125],
      ['8Al + 3Fe3O4 → 4Al2O3 + 9Fe + 3300 кДж', '8Al + 3Fe3O4 -> 4Al2O3 + 9Fe', 'redox', 't°', 125, { note: 'алюминотермия (термит), +3300 кДж' }],
      ['AlCl3 + 3K → 3KCl + Al', 'AlCl3 + 3K -> 3KCl + Al', 'substitution', null, 126, { inExercise: true, note: 'способ Ф. Велера (1827)' }],
      ['4Me + 3O2 = 2Me2O3', '4Me + 3O2 -> 2Me2O3', 'combination', null, 127, { isGeneralScheme: true, inWorkedExample: true }],
      ['2Al + 2NaOH + 6H2O = 2Na[Al(OH)4] + H2', '2Al + 2NaOH + 6H2O -> 2Na[Al(OH)4] + 3H2', 'redox', null, 127, { inWorkedExample: true, note: 'в книге «+ H2» без коэффициента 3 (не уравнено); исправлено' }],
      ['Na[Al(OH)4] + 4HCl = NaCl + AlCl3+ 4H2O', 'Na[Al(OH)4] + 4HCl -> NaCl + AlCl3 + 4H2O', 'exchange', null, 127, { inWorkedExample: true }],
      ['AlCl3 + 3NaOH = Al(OH)3 + 3NaCl', 'AlCl3 + 3NaOH -> Al(OH)3 + 3NaCl', 'exchange', null, 127, { inWorkedExample: true }],
      ['2Al(OH)3 → Al2O3 + 3H2O', '2Al(OH)3 -> Al2O3 + 3H2O', 'decomposition', 't°', 127, { inWorkedExample: true }],
      ['Al2O3 + 2NaOH = 2NaAlO2 + H2O', 'Al2O3 + 2NaOH -> 2NaAlO2 + H2O', 'exchange', 't°', 127, { inWorkedExample: true, note: 'сплавление' }],
      ['2NaAlO2 + 4H2SO4 = Na2SO4 + Al2(SO4)3 + 4H2O', '2NaAlO2 + 4H2SO4 -> Na2SO4 + Al2(SO4)3 + 4H2O', 'exchange', null, 127, { inWorkedExample: true }],
      ['2Al + 2NaOH + 2H2O = 2NaAlO2 + 3H2', '2Al + 2NaOH + 2H2O -> 2NaAlO2 + 3H2', 'redox', null, 128, { inWorkedExample: true }],
    ],
    L: [],
  },
  '27': {
    S: [
      ['Al2O3', 'оксид алюминия', 'studied', 129, 'Оксид алюминия Al2O3', { aliases: ['боксит', 'корунд', 'рубин', 'сапфир'] }],
      ['Al(OH)3', 'гидроксид алюминия', 'studied', 129, 'Гидроксид алюминия получают'],
      ['HCl', 'соляная кислота', 'reagent', 129, 'Al2O3 + 6HCl'],
      ['AlCl3', 'хлорид алюминия', 'obtained', 129, '2AlCl3 + 3H2O', { aliases: ['безводный хлорид алюминия (катализатор)'] }],
      ['NaOH', 'гидроксид натрия (щелочь)', 'reagent', 129, 'Al2O3 + 2NaOH + 3H2O'],
      ['Na[Al(OH)4]', 'тетрагидроксоалюминат натрия', 'obtained', 129, '2Na[Al(OH)4]', { kind: 'salt', note: 'в книге только формула' }],
      ['NaAlO2', 'алюминат натрия', 'obtained', 129, 'образует NaAlO2', { note: 'в реакции с безводной щелочью' }],
      ['H2O', 'вода', 'obtained', 129, '2Al(OH)3→ Al2O3 + 3H2O'],
      ['NaCl', 'хлорид натрия', 'obtained', 129, 'Al(OH)3 + 3NaCl', { note: 'только формула' }],
      ['Al^3+', 'ион алюминия', 'mentioned', 130, 'Al3+ + 3OH– = Al(OH)3', { kind: 'other' }],
      ['OH^-', 'гидроксид-ион', 'mentioned', 130, 'Al3+ + 3OH– = Al(OH)3', { kind: 'other' }],
      ['Cl^-', 'хлорид-ион', 'mentioned', 130, '3Cl–', { kind: 'other' }],
      ['Na^+', 'ион натрия', 'mentioned', 130, '3Na+', { kind: 'other' }],
      ['H2SO4', 'серная кислота', 'reagent', 130, '3H2SO4', { note: 'только формула' }],
      ['Al2(SO4)3', 'сульфат алюминия', 'obtained', 130, 'сульфат а люмини я'],
      ['KOH', 'гидроксид калия', 'reagent', 130, '2KOH', { note: 'только формула' }],
      ['KAlO2', 'алюминат калия', 'obtained', 130, 'KAlO2', { note: 'только формула' }],
      ['Al', 'алюминий', 'mentioned', 130, 'дюралюминий (95 % Al', { note: 'применение; дюралюминий — сплав 95% Al, 4% Cu, 0,5% Mg, 0,5% Mn' }],
      ['KAl(SO4)2*12H2O', 'алюминиевые квасцы', 'mentioned', 130, 'квасцы KAl(SO4)2.12H2O'],
      ['Al2O3*2SiO2*2H2O', 'каолин', 'mentioned', 130, 'Каолин используется', { formulaInBook: false, mineral: true }],
      ['Cr^3+', 'ионы хрома(III)', 'mentioned', 131, 'ионов Cr3+', { kind: 'other', note: 'окраска рубина' }],
    ],
    R: [
      ['2Al(OH)3→ Al2O3 + 3H2O', '2Al(OH)3 -> Al2O3 + 3H2O', 'decomposition', 't°', 129, { note: '«путем накаливания его гидроксида»' }],
      ['Al2O3 + 6HCl = 2AlCl3 + 3H2O', 'Al2O3 + 6HCl -> 2AlCl3 + 3H2O', 'exchange', null, 129, { note: 'амфотерный оксид + кислота' }],
      ['Al2O3 + 2NaOH + 3H2O = 2Na[Al(OH)4]', 'Al2O3 + 2NaOH + 3H2O -> 2Na[Al(OH)4]', 'combination', null, 129, { note: 'амфотерный оксид + раствор щелочи' }],
      ['Al2O3 + 2NaOH → 2NaAlO2 + H2O', 'Al2O3 + 2NaOH -> 2NaAlO2 + H2O', 'exchange', 't°', 129, { note: 'с безводной щелочью (сплавление)' }],
      ['AlCl3 + 3NaOH = Al(OH)3 + 3NaCl', 'AlCl3 + 3NaOH -> Al(OH)3 + 3NaCl', 'exchange', null, 129],
      ['Al3+ + 3Cl– + 3Na+ + 3OH– = Al(OH)3 + 3Na+ + 3Cl–', 'Al^3+ + 3Cl^- + 3Na^+ + 3OH^- -> Al(OH)3 + 3Na^+ + 3Cl^-', 'exchange', null, 130, { isIonic: true, note: 'полное ионное уравнение' }],
      ['Al3+ + 3OH– = Al(OH)3', 'Al^3+ + 3OH^- -> Al(OH)3', 'exchange', null, 130, { isIonic: true, note: 'сокращенное ионное уравнение' }],
      ['2Al(OH)3 + 3H2SO4 = Al2(SO4)3 + 6H2O', '2Al(OH)3 + 3H2SO4 -> Al2(SO4)3 + 6H2O', 'neutralization', null, 130],
      ['Al(OH)3 + 2KOH = KAlO2 + 2H2O', 'Al(OH)3 + KOH -> KAlO2 + 2H2O', 'neutralization', 't°', 130, { note: 'в книге «Al(OH)3 + 2KOH = KAlO2 + 2H2O» (не уравнено: лишний коэффициент 2 перед KOH); исправлено; KAlO2 образуется при сплавлении' }],
    ],
    L: [],
  },
}
