// Hand-authored inventory data, grade 9 textbook (ru), §22–§24.
// S: [formula|null, nameRu (as in book), role, page, quoteHint, extra?]
// R: [bookTextHint|null, cleanedAsciiEquation, type, conditions, page, extra?]
// L: [{ title, page, substances: [formula] }]
export const DATA = {
  '22': {
    S: [
      ['Na2CO3', 'сода', 'studied', 105, 'Сода Na2CO3', { aliases: ['безводная сода', 'кальцинированная (обезвоженная) сода'] }],
      ['Na2CO3*10H2O', 'кристаллическая сода (кристаллогидрат)', 'studied', 107, 'Na2CO3.10H2O'],
      ['NaHCO3', 'гидрокарбонат натрия (пищевая сода)', 'obtained', 106, 'гидрокарбонат натрия', { aliases: ['питьевая сода', 'пищевая сода'] }],
      ['NaOH', 'каустическая сода', 'mentioned', 105, 'каустическая сода', { formulaInBook: true, aliases: ['гидроксид'] }],
      ['NaCl', 'поваренная соль', 'reagent', 106, 'поваренная соль, взаимодействуя с серной кислотой'],
      ['H2SO4', 'серная кислота', 'reagent', 106, 'взаимодействуя с серной кислотой'],
      ['Na2SO4', 'сульфат натрия', 'obtained', 106, 'переходит в сульфат натрия'],
      ['C', 'уголь', 'reagent', 106, 'при нагревании с углем'],
      ['Na2S', 'сульфид натрия', 'obtained', 106, 'переходит в сульфид натрия'],
      ['CaCO3', 'известняк', 'reagent', 106, 'Na2S + CaCO3'],
      ['HCl', 'хлороводород', 'obtained', 106, '2NaCl + H2SO4', { formulaInBook: true, note: 'только в уравнении (2HCl)' }],
      ['CO2', 'углекислый газ', 'reagent', 106, 'обработке углекислым газом'],
      ['CaS', 'сульфид кальция', 'obtained', 106, 'CaS плохо растворяется в воде'],
      ['NH3', 'аммиак', 'reagent', 106, 'поваренной соли аммиаком'],
      ['NH4Cl', 'хлорид аммония', 'reagent', 106, 'обработке хлорида аммония'],
      ['Ca(OH)2', 'гашеная известь', 'reagent', 106, 'гашеной известью'],
      ['CaCl2', 'хлорид кальция', 'obtained', 106, '2NH3 + CaCl2', { note: 'только в уравнении' }],
      ['H2O', 'вода', 'reagent', 106, 'NH3 + CO2 + H2O'],
      ['NH4HCO3', 'гидрокарбонат аммония', 'obtained', 106, 'NH3 + CO2 + H2O → NH4HCO3', { note: 'в книге только формула' }],
      ['Na', 'натрий (металлический)', 'reagent', 107, '3,45 г металлического натрия', { inWorkedExample: true }],
      ['H2', 'водород', 'obtained', 107, 'выделяется водород', { inWorkedExample: true }],
      ['KH', 'гидрид калия', 'mentioned', 108, 'гидрид калия KH', { inWorkedExample: true }],
      ['Li', 'литий', 'mentioned', 108, 'Li → X → LiOH', { inExercise: true }],
      ['LiOH', 'гидроксид лития', 'mentioned', 108, 'LiOH → LiCl', { inExercise: true, note: 'в книге только формула' }],
      ['LiCl', 'хлорид лития', 'mentioned', 108, 'LiOH → LiCl', { inExercise: true, note: 'в книге только формула' }],
      ['O2', 'кислород', 'mentioned', 108, '+O2', { inExercise: true, note: 'над стрелкой в цепочке превращений' }],
      ['Na2O2', 'пероксид натрия', 'mentioned', 108, 'Na → Na2O2', { inExercise: true, note: 'в книге только формула' }],
      ['Na2O', 'оксид натрия', 'mentioned', 108, 'Na2O2→ Na2O', { inExercise: true, note: 'в книге только формула' }],
      ['Na3PO4', 'фосфат натрия', 'mentioned', 108, 'NaOH → Na3PO4', { inExercise: true, note: 'в книге только формула' }],
    ],
    R: [
      ['2NaCl + H2SO4 → Na2SO4 + 2HCl', '2NaCl + H2SO4 -> Na2SO4 + 2HCl', 'exchange', null, 106, { note: 'способ Леблана, стадия 1' }],
      ['Na2SO4 + 2C → Na2S + 2CO2', 'Na2SO4 + 2C -> Na2S + 2CO2', 'redox', 't°', 106, { note: 'способ Леблана, стадия 2; «при нагревании с углем»' }],
      ['Na2S + CaCO3 → Na2CO3 + CaS', 'Na2S + CaCO3 -> Na2CO3 + CaS', 'exchange', 't°', 106, { note: 'способ Леблана, стадия 3; «при нагревании»' }],
      ['2NH4Cl + Ca(OH)2 → 2NH3 + CaCl2 + 2H2O', '2NH4Cl + Ca(OH)2 -> 2NH3 + CaCl2 + 2H2O', 'exchange', null, 106, { note: 'аммиачный способ Сольве, стадия 1' }],
      ['NH3 + CO2 + H2O → NH4HCO3', 'NH3 + CO2 + H2O -> NH4HCO3', 'combination', null, 106, { note: 'способ Сольве, стадия 2 (под давлением)' }],
      ['NH4HCO3 + NaCl → NaHCO3 + NH4Cl', 'NH4HCO3 + NaCl -> NaHCO3 + NH4Cl', 'exchange', null, 106, { note: 'способ Сольве, стадия 3; NaHCO3 выпадает в осадок' }],
      ['2NaHCO3 → Na2CO3 + CO2 + H2O', '2NaHCO3 -> Na2CO3 + CO2 + H2O', 'decomposition', 't°', 106, { note: 'способ Сольве, стадия 4; «при нагревании образует соду»' }],
      ['2Na + 2H2O = 2NaOH + H2', '2Na + 2H2O -> 2NaOH + H2', 'substitution', null, 107, { inWorkedExample: true }],
      ['MeHn + nH2O = Me(OH)n + nH2', 'MeHn + nH2O -> Me(OH)n + nH2', 'other', null, 108, { isGeneralScheme: true, inWorkedExample: true, note: 'гидрид металла + вода; ответ примера — KH' }],
    ],
    L: [],
  },
  '23': {
    S: [
      ['Mg', 'магний', 'studied', 109, 'Магний Mg'],
      ['Ca', 'кальций', 'studied', 109, 'кальций Ca'],
      ['Sr', 'стронций', 'mentioned', 109, 'Ca, Sr, Ba называются', { note: 'только символ, как щелочноземельный металл' }],
      ['Ba', 'барий', 'mentioned', 109, 'Ca, Sr, Ba называются', { note: 'только символ, как щелочноземельный металл' }],
      ['MgCO3', 'магнезит', 'mentioned', 109, 'магнезит MgCO3', { mineral: true }],
      ['CaCO3', 'кальцит', 'studied', 109, 'кальцит CaCO3', { mineral: true, aliases: ['известняк', 'мел', 'мрамор', 'исландский шпат'] }],
      ['CaCO3*MgCO3', 'доломит', 'mentioned', 109, 'доломит CaCO3 . MgCO3', { mineral: true }],
      ['CaSO4*2H2O', 'гипс', 'studied', 109, 'гипс CaSO4 . 2H2O', { mineral: true, aliases: ['природный гипс'] }],
      ['MgSO4*7H2O', 'горькая соль', 'mentioned', 109, 'горькая соль', { mineral: true }],
      ['CaO*3MgO*4SiO2', 'асбест', 'mentioned', 109, 'aсбест CaO . 3MgO . 4SiO2', { mineral: true, kind: 'salt', note: 'силикат, записан в оксидной форме' }],
      ['CaSO4*H2O', 'гипс, алебастр (схема)', 'mentioned', 110, 'гипс, алебастр CaSO4 . H2O', { mineral: true, note: 'так в инфографике; в §23 на с.115 алебастр = (CaSO4)2·H2O' }],
      ['Ca3(PO4)2', 'апатит / фосфат кальция', 'studied', 110, 'апатит Ca3(PO4)2', { aliases: ['фосфат кальция', 'фосфорит'] }],
      ['Ca5(PO4)3F', 'фторапатит', 'mentioned', 110, 'фторапатит Ca5(PO4)3F', { mineral: true }],
      ['CaCl2', 'хлорид кальция', 'reagent', 110, 'CaCl2', { note: 'электролиз расплава CaCl2 → Ca (схема); применяется в медицине' }],
      ['CaH2', 'гидрид кальция', 'obtained', 110, 'Ca H2', { note: 'схема соединений кальция; уравнение на с.112' }],
      ['Ca(NO3)2', 'нитрат кальция', 'mentioned', 110, 'Ca(NO3)2', { note: 'в инфографике только формула' }],
      ['CaO', 'оксид кальция (негашеная известь)', 'studied', 110, 'CaO', { aliases: ['негашеная известь', 'известь'] }],
      ['Ca(OH)2', 'гидроксид кальция (гашеная известь)', 'studied', 110, 'Ca(OH)2', { aliases: ['гашеная известь', 'известковая вода', 'известковое молоко'] }],
      ['Ca3N2', 'нитрид кальция', 'obtained', 110, 'Ca3N2'],
      ['CaS', 'сульфид кальция', 'obtained', 110, 'CaS'],
      ['CaSO4', 'сульфат кальция (безводный гипс)', 'mentioned', 110, 'CaSO4', { aliases: ['безводный гипс'] }],
      ['KCl*MgCl2*6H2O', 'карналлит', 'mentioned', 111, 'карналлит', { mineral: true }],
      ['MgSiO3', 'олевин (оливин)', 'mentioned', 111, 'олевин', { mineral: true, note: 'так в книге; минерал оливин обычно (Mg,Fe)2SiO4' }],
      ['MgO*CaO', 'MgO·CaO (обожжённый доломит)', 'mentioned', 111, 'MgO∙CaO', { kind: 'oxide', note: 'в инфографике как сырье для получения Mg; название в книге не дано' }],
      ['MgO', 'оксид магния', 'obtained', 111, 'MgO', { aliases: ['жженая магнезия'] }],
      ['MgCl2', 'хлорид магния', 'reagent', 111, 'MgCl2', { note: 'сырье для получения Mg (схема)' }],
      ['MgH2', 'гидрид магния', 'mentioned', 111, 'MgH2', { note: 'в инфографике только формула' }],
      ['Mg(NO3)2', 'нитрат магния', 'mentioned', 111, 'Mg(NO3)2', { note: 'в инфографике только формула' }],
      ['Mg(OH)2', 'гидроксид магния', 'mentioned', 111, 'Mg(OH)2', { note: 'в инфографике только формула' }],
      ['Mg3N2', 'нитрид магния', 'obtained', 111, '3Mg + N2'],
      ['MgS', 'сульфид магния', 'mentioned', 111, 'MgS', { note: 'в инфографике только формула' }],
      ['MgSO4', 'сульфат магния', 'mentioned', 111, 'MgSO4', { note: 'в инфографике только формула' }],
      ['O2', 'кислород', 'reagent', 111, '2Mg + O2'],
      ['N2', 'азот', 'reagent', 111, 'с галогенами и азотом'],
      ['Br2', 'бром', 'reagent', 111, 'Mg + Br2'],
      ['MgBr2', 'бромид магния', 'obtained', 111, 'Mg + Br2'],
      ['CO2', 'углекислый газ', 'reagent', 111, 'с углекислым газом'],
      ['C', 'углерод', 'obtained', 111, '2MgO + C'],
      ['H2O', 'вода (водяные пары)', 'reagent', 111, 'водяными парами'],
      ['H2', 'водород', 'obtained', 111, 'MgO + H2'],
      ['Cl2', 'хлор', 'reagent', 112, 'Ca + Cl2'],
      ['P', 'фосфор', 'reagent', 112, 'с азотом, фосфором'],
      ['Ca3P2', 'фосфид кальция', 'obtained', 112, 'фосфид кальция'],
      ['S', 'сера', 'reagent', 112, 'Ca + S'],
      ['CaC2', 'карбид кальция', 'obtained', 112, 'карбид кальция'],
      ['HCl', 'соляная кислота', 'reagent', 112, 'Ca + 2HCl'],
      [null, 'глюконат кальция', 'mentioned', 112, 'глюконат кальция', { kind: 'organic' }],
      [null, 'тальк', 'mentioned', 112, 'тальк', { kind: 'other', mineral: true, note: 'формула в книге не дана' }],
      [null, 'хлорофилл', 'mentioned', 113, 'хлорофилловые зерна, содержащие магний', { kind: 'organic', note: 'пигмент, содержит магний (3%)' }],
      ['CaOCl2', 'хлорная известь', 'studied', 115, 'Хлорная известь CaOCl2', { kind: 'salt' }],
      ['Ca(OCl)2', 'гипохлорит кальция', 'obtained', 115, 'Ca(OCl)2 + CaCl2', { kind: 'salt', note: 'в книге только формула в уравнении' }],
      ['(CaSO4)2*H2O', 'обожженный гипс (алебастр)', 'studied', 115, 'обожженный гипс', { aliases: ['алебастр'] }],
      ['Ca(HCO3)2', 'гидрокарбонат кальция', 'obtained', 115, 'водорастворимую соль Ca(HCO3)2'],
    ],
    R: [
      ['электролиз CaCl2 Ca', 'CaCl2 -> Ca + Cl2', 'decomposition', 'электролиз расплава', 110, { note: 'в инфографике: «CaCl2 —электролиз→ Ca»; Cl2 в схеме не указан, дописан', described: true }],
      ['2Mg + O2 2MgO', '2Mg + O2 -> 2MgO', 'combustion', null, 111, { note: 'знак стрелки потерян в текстовом слое PDF' }],
      ['3Mg + N2 Mg3N2', '3Mg + N2 -> Mg3N2', 'combination', null, 111],
      ['Mg + Br2 MgBr2', 'Mg + Br2 -> MgBr2', 'combination', null, 111],
      ['2Mg + CO2 2MgO + C', '2Mg + CO2 -> 2MgO + C', 'redox', null, 111],
      ['Mg + H2O MgO + H2', 'Mg + H2O -> MgO + H2', 'substitution', 't°', 111, { note: 'с водяными парами' }],
      ['2Ca + O2 → 2CaO', '2Ca + O2 -> 2CaO', 'combination', null, 112],
      ['Ca + Cl2 → CaCl2', 'Ca + Cl2 -> CaCl2', 'combination', null, 112],
      ['3Ca + N2 → Ca3N2', '3Ca + N2 -> Ca3N2', 'combination', 't°', 112, { note: '«при нагревании»' }],
      ['3Ca + 2P → Ca 3P2', '3Ca + 2P -> Ca3P2', 'combination', 't°', 112],
      ['Ca + S → CaS', 'Ca + S -> CaS', 'combination', 't°', 112],
      ['Ca + 2C → CaC2', 'Ca + 2C -> CaC2', 'combination', 't°', 112],
      ['Ca + H2 → CaH2', 'Ca + H2 -> CaH2', 'combination', 't°', 112],
      ['Ca + 2HCl → CaCl2 + H2', 'Ca + 2HCl -> CaCl2 + H2', 'substitution', null, 112],
      ['Ca + 2H2O → Ca(OH)2 + H2', 'Ca + 2H2O -> Ca(OH)2 + H2', 'substitution', null, 112],
      ['CaCO3 t CaO + CO2', 'CaCO3 -> CaO + CO2', 'decomposition', 't°', 114, { note: 'обжиг известняка' }],
      ['CaO + CO2 = CaCO3', 'CaO + CO2 -> CaCO3', 'combination', null, 114],
      ['CaO + H2O = Ca(OH)2 + Q', 'CaO + H2O -> Ca(OH)2 + Q', 'combination', null, 114, { note: 'гашение извести, экзотермическая' }],
      ['Ca(OH)2 + CO2 = CaCO3 + H2O', 'Ca(OH)2 + CO2 -> CaCO3 + H2O', 'exchange', null, 115, { note: 'помутнение известковой воды' }],
      ['CaCO3 + CO2 + H2O → Ca(HCO3)2', 'CaCO3 + CO2 + H2O -> Ca(HCO3)2', 'combination', null, 115],
      ['2Ca(OH)2 + 2Cl2 = Ca(OCl)2 + CaCl2 + 2H2O', '2Ca(OH)2 + 2Cl2 -> Ca(OCl)2 + CaCl2 + 2H2O', 'redox', null, 115, { note: 'получение хлорной извести' }],
      ['2CaSO4.2H2O 150—170oC (CaSO4)2.H2O + 3H2O', '2CaSO4*2H2O -> (CaSO4)2*H2O + 3H2O', 'decomposition', '150–170 °C', 115],
      ['(CaSO4)2.H2O + 3H2O → 2[CaSO4.2H2O]', '(CaSO4)2*H2O + 3H2O -> 2CaSO4*2H2O', 'combination', null, 115, { note: 'в книге продукт записан как 2[CaSO4·2H2O]' }],
    ],
    L: [],
  },
  '24': {
    S: [
      ['H2O', 'вода (жесткая, мягкая)', 'studied', 116, 'Жесткость воды'],
      ['Ca^2+', 'ионы кальция', 'studied', 117, 'ионов Ca2+ и Mg2+', { kind: 'other' }],
      ['Mg^2+', 'ионы магния', 'studied', 117, 'ионов Ca2+ и Mg2+', { kind: 'other' }],
      ['Ca(HCO3)2', 'гидрокарбонат кальция', 'studied', 117, 'гидрокарбонатов кальция и магния'],
      ['Mg(HCO3)2', 'гидрокарбонат магния', 'studied', 117, 'Mg(HCO3)2'],
      ['CaSO4', 'сульфат кальция', 'studied', 117, 'сульфатов и хлоридов кальция и магния'],
      ['CaCl2', 'хлорид кальция', 'studied', 117, 'CaSO4, CaCl2'],
      ['MgSO4', 'сульфат магния', 'studied', 117, 'MgSO4, MgCl2'],
      ['MgCl2', 'хлорид магния', 'studied', 117, 'хлориды магния и кальция'],
      ['CaCO3', 'карбонат кальция (накипь)', 'obtained', 118, 'соли CaCO3 и MgCO3'],
      ['MgCO3', 'карбонат магния (накипь)', 'obtained', 118, 'соли CaCO3 и MgCO3'],
      ['CO2', 'углекислый газ', 'obtained', 118, 'CaCO3 + H2O + CO2'],
      ['Ca(OH)2', 'известковая вода', 'reagent', 118, 'Добавлением известковой воды'],
      ['CaCO3*MgCO3', 'CaCO3·MgCO3', 'obtained', 118, 'CaCO3.MgCO3', { note: 'в книге только формула (доломит)' }],
      ['NaOH', 'щелочь', 'reagent', 118, 'Воздействием щелочи'],
      ['Na2CO3', 'сода', 'reagent', 118, 'Добавлением соды (Na2CO3)'],
      ['NaHCO3', 'гидрокарбонат натрия', 'obtained', 118, '2NaHCO3', { note: 'в книге только формула' }],
      ['Na3PO4', 'фосфат натрия', 'reagent', 118, 'фосфата натрия'],
      ['Na2SO4', 'сульфат натрия', 'obtained', 118, '3Na2SO4', { note: 'в книге только формула' }],
      ['Mg3(PO4)2', 'фосфат магния', 'obtained', 118, 'Mg3(PO4)2', { note: 'в книге только формула' }],
      ['Na^+', 'ионы натрия', 'mentioned', 119, 'подвижные катионы (Na+)', { kind: 'other' }],
      ['SO4^2-', 'сульфат-ионы', 'mentioned', 119, 'внешней среды', { kind: 'other', note: 'в тексте «(SO4 2-, Cl–)» — анионы для анионитов' }],
      ['Cl^-', 'хлорид-ионы', 'mentioned', 119, 'Cl–', { kind: 'other' }],
      [null, 'катиониты (Na2R, R — органический радикал)', 'mentioned', 119, 'R в катионитах', { kind: 'other', note: 'ионообменные смолы' }],
      [null, 'мыло', 'mentioned', 117, 'плохо пенится мыло', { kind: 'organic' }],
      ['Ca3(PO4)2', 'фосфат кальция', 'mentioned', 120, 'фосфат кальция', { inWorkedExample: true }],
    ],
    R: [
      ['Ca(HCO3)2 → CaCO3 + H2O + CO2', 'Ca(HCO3)2 -> CaCO3 + H2O + CO2', 'decomposition', 't°', 118, { note: 'устранение временной жесткости кипячением' }],
      ['Mg(HCO3)2 → MgCO3 + H2O + CO2', 'Mg(HCO3)2 -> MgCO3 + H2O + CO2', 'decomposition', 't°', 118, { note: 'кипячение' }],
      ['Ca(HCO3)2 + Ca(OH)2 → 2CaCO3 + 2H2O', 'Ca(HCO3)2 + Ca(OH)2 -> 2CaCO3 + 2H2O', 'exchange', null, 118, { note: 'добавление известковой воды' }],
      ['Mg(HCO3)2 + Ca(OH)2 → CaCO3.MgCO3 + 2H2O', 'Mg(HCO3)2 + Ca(OH)2 -> CaCO3*MgCO3 + 2H2O', 'exchange', null, 118],
      ['Ca(HCO3)2 + 2NaOH → CaCO3 + Na2CO3 + 2H2O', 'Ca(HCO3)2 + 2NaOH -> CaCO3 + Na2CO3 + 2H2O', 'exchange', null, 118],
      ['Mg(HCO3)2 + 2NaOH → MgCO3 + Na2CO3 + 2H2O', 'Mg(HCO3)2 + 2NaOH -> MgCO3 + Na2CO3 + 2H2O', 'exchange', null, 118],
      ['Ca(HCO3)2 + Na2CO3 → CaCO3 + 2NaHCO3', 'Ca(HCO3)2 + Na2CO3 -> CaCO3 + 2NaHCO3', 'exchange', null, 118],
      ['Mg(HCO3)2 + Na2CO3 → MgCO3 + 2NaHCO3', 'Mg(HCO3)2 + Na2CO3 -> MgCO3 + 2NaHCO3', 'exchange', null, 118],
      ['CaSO4 + Na2CO3 → CaCO3 + Na2SO4', 'CaSO4 + Na2CO3 -> CaCO3 + Na2SO4', 'exchange', null, 118, { note: 'устранение постоянной жесткости' }],
      ['3MgSO4 + 2Na3PO4 → Mg3(PO4)2 + 3Na2SO4', '3MgSO4 + 2Na3PO4 -> Mg3(PO4)2 + 3Na2SO4', 'exchange', null, 118],
      ['Na2R+Ca2+→ 2Na++CaR', 'Na2R + Ca^2+ -> 2Na^+ + CaR', 'exchange', null, 119, { isIonic: true, note: 'ионный обмен на катионите; R — органический радикал' }],
    ],
    L: [],
  },
}
