// Hand-authored inventory data, grade 9 textbook (ru), §28–§33 (Cu, Ag, Au, Zn, Cr, Mn).
// S: [formula|null, nameRu (as in book), role, page, quoteHint, extra?]
// R: [bookTextHint|null, cleanedAsciiEquation, type, conditions, page, extra?]
export const DATA = {
  '28': {
    S: [
      ['Cu', 'медь', 'studied', 132, 'Медь расположена в побочной подгруппе'],
      ['Ag', 'серебро', 'mentioned', 132, 'Серебро расположено в побочной подгруппе'],
      ['Au', 'золото', 'mentioned', 132, 'Золото расположено в побочной подгруппе'],
      ['Sn', 'олово', 'mentioned', 133, 'Сплав меди с оловом', { formulaInBook: false, note: 'бронза — сплав меди с оловом' }],
      ['Cu2S', 'медный блеск (халькозин)', 'reagent', 133, 'медный блеск Cu2S', { mineral: true, aliases: ['халькозин'] }],
      ['O2', 'кислород', 'reagent', 133, '2Cu2S + 3O2'],
      ['Cu2O', 'куприт (оксид меди(I))', 'obtained', 133, 'Куприт меди Cu2O', { mineral: true }],
      ['SO2', 'оксид серы(IV)', 'obtained', 133, 'серы(IV), образующийся в результате реакции'],
      ['CuFeS2', 'медный колчедан', 'mentioned', 133, 'медный колчедан CuFeS2', { mineral: true }],
      ['(CuOH)2CO3', 'малахит', 'studied', 133, 'малахит (CuOH)2CO3', { kind: 'salt', mineral: true, aliases: ['CuCO3·Cu(OH)2'] }],
      ['Ag2S', 'серебряный блеск (аргентит)', 'mentioned', 133, 'Серебряный блеск Ag2S', { mineral: true }],
      ['Ni', 'никель', 'mentioned', 133, 'примеси Ni, Ag, Au', { note: 'примесь в черновой меди' }],
      ['Cl2', 'хлор', 'reagent', 134, 'Cu + Cl2'],
      ['CuCl2', 'хлорид меди(II)', 'obtained', 134, 'Cu + Cl2 → CuCl2'],
      ['CuO', 'оксид меди(II)', 'studied', 134, 'Оксид меди(II) CuO'],
      ['S', 'сера', 'reagent', 134, 'Cu + S → CuS'],
      ['CuS', 'сульфид меди(II)', 'obtained', 134, 'Cu + S → CuS', { note: 'только формула' }],
      ['H2O', 'вода (водяные пары)', 'reagent', 134, 'водяными парами и углекислым газом'],
      ['CO2', 'углекислый газ', 'reagent', 134, 'водяными парами и углекислым газом'],
      ['CuCO3*Cu(OH)2', 'малахит', 'obtained', 134, 'CuCO3.Cu(OH)2', { mineral: true, note: 'то же, что (CuOH)2CO3; зеленая пленка на меди' }],
      ['H2', 'водород', 'reagent', 134, 'не взаимодействует с водородом'],
      ['HCl', 'соляная кислота', 'reagent', 134, 'не реагирует с соляной', { note: 'медь не реагирует; с CuO реагирует (с.135)' }],
      ['H2SO4', 'серная кислота (конц., разб.)', 'reagent', 134, 'концентрированной серной кислотой'],
      ['CuSO4', 'сульфат меди(II)', 'studied', 134, 'CuSO4 + SO2'],
      ['HNO3', 'азотная кислота', 'reagent', 134, 'С азотной кислотой медь'],
      ['Cu(NO3)2', 'нитрат меди(II)', 'obtained', 134, 'Cu(NO3)2 + 2NO2'],
      ['NO2', 'оксид азота(IV)', 'obtained', 134, '2NO2 + 2H2O', { note: 'только формула' }],
      ['NO', 'оксид азота(II)', 'obtained', 134, '2NO + 4H2O', { note: 'только формула' }],
      ['CO', 'угарный газ', 'reagent', 135, 'CuO + CO', { aliases: ['угарный газ'] }],
      ['Cu(OH)2', 'гидроксид меди(II)', 'studied', 135, 'Гидроксид меди(II) Cu(OH)2'],
      ['NaOH', 'щелочь (NaOH)', 'reagent', 135, 'CuSO4 + 2NaOH'],
      ['Na2SO4', 'сульфат натрия', 'obtained', 135, 'Cu(OH)2 + Na2SO4', { note: 'только формула' }],
      ['CuSO4*5H2O', 'медный купорос', 'studied', 135, 'называется медным купоросом'],
      ['CuCl2*2H2O', 'хлорид меди(II) (кристаллогидрат)', 'mentioned', 135, 'CuCl', { note: 'в тексте «CuCl2 . 2H2O — вещество зеленого цвета»' }],
      ['Cu(NO3)2*3H2O', 'нитрат меди(II) (кристаллогидрат)', 'mentioned', 135, 'Cu(NO3)2.3H2O'],
      ['Ca(OH)2', 'гашеная известь', 'reagent', 136, 'медного купороса (CuSO4.5H2O) и гашеной извести', { formulaInBook: false, note: 'бордоская смесь (название не дано)' }],
      ['KCl', 'хлорид калия', 'mentioned', 136, 'с хлоридом калия', { formulaInBook: false, note: 'микроудобрение' }],
      ['CO(NH2)2', 'мочевина', 'mentioned', 136, 'мочевиной', { kind: 'organic', formulaInBook: false }],
      [null, 'крахмал', 'mentioned', 136, 'крахмал', { kind: 'organic' }],
    ],
    R: [
      ['2Cu2S + 3O2 → 2Cu2O + 2SO2', '2Cu2S + 3O2 -> 2Cu2O + 2SO2', 'redox', 't°', 133, { note: 'обжиг медного блеска' }],
      ['2Cu2O + Cu2S → 6Cu + SO2', '2Cu2O + Cu2S -> 6Cu + SO2', 'redox', 't°', 133],
      ['Cu + Cl2 → CuCl2', 'Cu + Cl2 -> CuCl2', 'combination', 't°', 134, { note: '«при высоких температурах»' }],
      ['2Cu + O2 → 2CuO', '2Cu + O2 -> 2CuO', 'combination', 't°', 134],
      ['Cu + S → CuS', 'Cu + S -> CuS', 'combination', 't°', 134],
      ['2Cu + O2 + H2O + CO2 = CuCO3.Cu(OH)2', '2Cu + O2 + H2O + CO2 -> CuCO3*Cu(OH)2', 'redox', null, 134, { note: 'образование малахита во влажном воздухе' }],
      ['Cu + 2H2SO4 → CuSO4 + SO2 + 2H2O. (конц.)', 'Cu + 2H2SO4 -> CuSO4 + SO2 + 2H2O', 'redox', 'H2SO4 конц.', 134],
      ['Cu + 4HNO3 → Cu(NO3)2 + 2NO2 + 2H2O, (конц.)', 'Cu + 4HNO3 -> Cu(NO3)2 + 2NO2 + 2H2O', 'redox', 'HNO3 конц.', 134],
      ['3Cu + 8HNO3 → 3Cu(NO3)2 + 2NO + 4H2O. (разб.)', '3Cu + 8HNO3 -> 3Cu(NO3)2 + 2NO + 4H2O', 'redox', 'HNO3 разб.', 134],
      ['(CuOH)2CO3 → 2CuO + CO2 + H2O', '(CuOH)2CO3 -> 2CuO + CO2 + H2O', 'decomposition', 't°', 135],
      ['CuO + H2= Cu + H2O', 'CuO + H2 -> Cu + H2O', 'redox', 't°', 135],
      ['CuO + CO = Cu + CO2', 'CuO + CO -> Cu + CO2', 'redox', 't°', 135],
      ['CuO + H2SO4 = CuSO4 + H2O', 'CuO + H2SO4 -> CuSO4 + H2O', 'exchange', null, 135],
      ['CuO + 2HCl = CuCl2 + H2O', 'CuO + 2HCl -> CuCl2 + H2O', 'exchange', null, 135],
      ['Cu(OH)2 + H2SO4 = CuSO4 + 2H2O', 'Cu(OH)2 + H2SO4 -> CuSO4 + 2H2O', 'neutralization', null, 135],
      ['CuSO4 + 2NaOH = Cu(OH)2 + Na2SO4', 'CuSO4 + 2NaOH -> Cu(OH)2 + Na2SO4', 'exchange', null, 135],
      ['Cu(OH)2 → CuO + H2O', 'Cu(OH)2 -> CuO + H2O', 'decomposition', 't°', 135],
    ],
    L: [],
  },
  '29': {
    S: [
      ['Ag', 'серебро', 'studied', 137, 'Серебро (Ag)'],
      ['Ag^+', 'ионы серебра', 'mentioned', 137, 'ионы серебра [Ag+]', { kind: 'other' }],
      ['HNO3', 'азотная кислота (конц.)', 'reagent', 137, 'концентрированной азотной кислоте'],
      ['AgNO3', 'нитрат серебра', 'studied', 137, 'серебро образует нитрат серебра'],
      ['NO2', 'оксид азота(IV)', 'obtained', 137, 'AgNO3 + NO2', { note: 'только формула' }],
      ['H2O', 'вода', 'obtained', 137, 'NO2 + H2O'],
      ['Cl2', 'хлор', 'reagent', 137, 'вступает в реакцию с хлором', { aliases: ['хлорная вода'] }],
      ['Br2', 'бром', 'reagent', 137, 'бромом, йодом и серой', { formulaInBook: false }],
      ['I2', 'йод', 'reagent', 137, 'бромом, йодом и серой', { formulaInBook: false }],
      ['S', 'сера', 'reagent', 137, 'бромом, йодом и серой', { formulaInBook: false }],
      ['AgBr', 'бромид серебра', 'mentioned', 138, 'бромид серебра (AgBr)'],
      ['Au', 'золото', 'studied', 138, 'Золото (Au)'],
      ['KCN', 'цианид калия', 'reagent', 138, '4Au + 8KCN', { note: 'в книге только формула (способ цианизации)' }],
      ['O2', 'кислород', 'reagent', 138, '8KCN + O2'],
      ['K[Au(CN)2]', 'комплексная соль цианида золота (дицианоаурат калия)', 'obtained', 138, 'комплексную соль K[Au(CN)2]', { kind: 'salt' }],
      ['KOH', 'гидроксид калия', 'obtained', 138, '4KOH', { note: 'только формула' }],
      ['Zn', 'цинк', 'reagent', 138, 'воздействуют цинком'],
      ['K2[Zn(CN)4]', 'тетрацианоцинкат калия', 'obtained', 138, 'K2[Zn(CN)4]', { kind: 'salt', note: 'только формула' }],
      [null, 'царская водка (смесь HNO3 и HCl 1:3)', 'reagent', 138, 'царской водкой', { kind: 'other' }],
      ['HCl', 'соляная кислота', 'reagent', 138, 'азотной и соляной'],
      ['AuCl3', 'хлорид золота(III)', 'obtained', 138, 'Образовавшийся AuCl3'],
      ['NO', 'оксид азота(II)', 'obtained', 138, 'AuCl3 + NO', { note: 'только формула' }],
      ['H[AuCl4]', 'тетрахлорозолотая кислота (комплексное соединение)', 'obtained', 138, 'комплексное соединение', { kind: 'acid' }],
    ],
    R: [
      ['Ag + 2HNO3 = AgNO3 + NO2 + H2O', 'Ag + 2HNO3 -> AgNO3 + NO2 + H2O', 'redox', 'HNO3 конц.', 137],
      ['4Au + 8KCN + O2 + 2H2O = 4K[Au(CN)2] + 4KOH', '4Au + 8KCN + O2 + 2H2O -> 4K[Au(CN)2] + 4KOH', 'redox', null, 138, { note: 'цианизация' }],
      ['2K[Au(CN)2] + Zn = K2[Zn(CN)4] + 2Au', '2K[Au(CN)2] + Zn -> K2[Zn(CN)4] + 2Au', 'substitution', null, 138],
      ['Au + HNO3 + 3HCl = AuCl3 + NO + 2H2O', 'Au + HNO3 + 3HCl -> AuCl3 + NO + 2H2O', 'redox', null, 138, { note: 'царская водка, реакция (1)' }],
      ['AuCl3 + HCl = H[AuCl4]', 'AuCl3 + HCl -> H[AuCl4]', 'combination', null, 138, { note: 'реакция (2)' }],
      ['Au + HNO3 + 4HCl = H[AuCl4] + NO + 2H2O', 'Au + HNO3 + 4HCl -> H[AuCl4] + NO + 2H2O', 'redox', null, 139, { note: 'итоговое уравнение (1)+(2)' }],
      ['При накаливании серебро вступает в реакцию с хлором', '2Ag + Cl2 -> 2AgCl', 'combination', 't°', 137, { described: true, noEquationInBook: true }],
      ['бромом, йодом и серой', '2Ag + Br2 -> 2AgBr', 'combination', 't°', 137, { described: true, noEquationInBook: true }],
      ['бромом, йодом и серой', '2Ag + I2 -> 2AgI', 'combination', 't°', 137, { described: true, noEquationInBook: true }],
      ['бромом, йодом и серой', '2Ag + S -> Ag2S', 'combination', 't°', 137, { described: true, noEquationInBook: true }],
      ['2Au + 3Cl2 = 2AuCl3', '2Au + 3Cl2 -> 2AuCl3', 'combination', '150 °C', 139],
    ],
    L: [],
  },
  '30': {
    S: [
      ['Zn', 'цинк', 'studied', 139, 'цинк, кадмий и ртуть'],
      ['Cd', 'кадмий', 'studied', 139, 'цинк, кадмий и ртуть'],
      ['Hg', 'ртуть', 'studied', 139, 'цинк, кадмий и ртуть'],
      ['ZnS', 'цинковая обманка', 'reagent', 140, 'цинковой обманки', { mineral: true }],
      ['O2', 'кислород', 'reagent', 140, '2ZnS + 3O2'],
      ['ZnO', 'оксид цинка', 'studied', 140, 'получается оксид цинка'],
      ['SO2', 'оксид серы(IV)', 'obtained', 140, '2ZnO + 2SO2', { note: 'только формула' }],
      ['C', 'углерод (восстановитель)', 'reagent', 140, 'ZnO + C'],
      ['CO', 'оксид углерода(II)', 'reagent', 140, 'ZnO + CO'],
      ['CO2', 'оксид углерода(IV)', 'obtained', 140, 'Zn + CO2'],
      ['Cl2', 'хлор', 'reagent', 140, 'Zn + Cl2'],
      ['ZnCl2', 'хлорид цинка', 'obtained', 140, 'Zn + Cl2 → ZnCl2'],
      ['S', 'сера', 'reagent', 140, 'Zn + S'],
      ['ZnCO3', 'цинковый шпат', 'mentioned', 141, 'Цинковый шпат ZnCO3', { mineral: true }],
      ['CdS', 'гринокит (сульфид кадмия)', 'mentioned', 141, 'Гринокит CdS', { mineral: true }],
      ['HgS', 'киноварь', 'mentioned', 141, 'Киноварь HgS', { mineral: true }],
      ['H2O', 'вода', 'mentioned', 141, 'цинк не реагирует с водой'],
      ['HCl', 'соляная кислота', 'reagent', 141, 'Zn + 2HCl'],
      ['H2', 'водород', 'obtained', 141, 'ZnCl2 + H2'],
      ['H2SO4', 'серная кислота (разб., конц.)', 'reagent', 141, 'разбавленной серной кислотой'],
      ['ZnSO4', 'сульфат цинка', 'obtained', 141, 'ZnSO4 + H2'],
      ['H2S', 'сероводород', 'obtained', 141, 'образуются H2S, S, SO2'],
      ['HNO3', 'азотная кислота', 'reagent', 141, 'цинка с азотной кислотой'],
      ['Zn(NO3)2', 'нитрат цинка', 'obtained', 141, '3Zn(NO3)2 + 2NO'],
      ['NO', 'оксид азота(II)', 'obtained', 141, '2NO + 4H2O', { note: 'только формула' }],
      ['N2O', 'оксид азота(I)', 'obtained', 141, 'N2O + 5H2O', { note: 'только формула' }],
      ['NH4NO3', 'нитрат аммония', 'obtained', 141, 'NH4NO3 + 3H2O', { note: 'только формула' }],
      ['NaOH', 'щелочь (NaOH)', 'reagent', 142, 'Zn + 2NaOH'],
      ['Na2[Zn(OH)4]', 'тетрагидроксоцинкат натрия (комплексная соль)', 'obtained', 142, 'Na2[Zn(OH)4] — соль', { kind: 'salt' }],
      ['Na2ZnO2', 'цинкат натрия', 'mentioned', 142, 'цинката натрия Na2ZnO2'],
      ['NO2', 'оксид азота(IV)', 'obtained', 142, '4NO2 + O2'],
      ['Zn(OH)2', 'гидроксид цинка', 'studied', 142, 'обжиг гидроксида цинка'],
      ['KOH', 'гидроксид калия', 'reagent', 142, 'ZnO + 2KOH'],
      ['K2[Zn(OH)4]', 'тетрагидроксоцинкат калия', 'obtained', 142, 'K2[Zn(OH)4]', { kind: 'salt', note: 'только формула' }],
      ['Na2SO4', 'сульфат натрия', 'obtained', 142, 'Zn(OH)2 + Na2SO4'],
      ['CdSO4', 'сульфат кадмия', 'reagent', 142, 'CdSO4 + 2NaOH'],
      ['Cd(OH)2', 'гидроксид кадмия', 'obtained', 142, 'Cd(OH)2 — обладает основными'],
      ['Hg(OH)2', 'гидроксид ртути(II)', 'mentioned', 142, 'Hg(OH)2 — очень неустойчивое'],
      ['ZnSO4*7H2O', 'цинковый купорос', 'studied', 142, 'цинкового купороса — ZnSO4. 7H2O'],
      ['HgO', 'оксид ртути(II)', 'obtained', 143, 'оксид ртути(II) красного цвета'],
      ['Hg2O', 'оксид ртути(I)', 'mentioned', 143, 'черного цвета (Hg2O)'],
      ['Hg(NO3)2', 'нитрат ртути(II)', 'studied', 143, 'нитрата ртути(II)'],
      ['NaNO3', 'нитрат натрия', 'obtained', 143, '2NaNO3 + H2O', { note: 'только формула' }],
      ['(NH4)2HPO4', 'аммофос', 'mentioned', 143, 'аммофоса', { note: 'в книге «аммофос ((NH4)2HPO4)»; обычно диаммофос' }],
      ['BaSO4', 'сульфат бария', 'mentioned', 144, 'Смесь ZnS и BaSO4', { note: 'в составе белых красок (литопон) и кадмопона' }],
      [null, 'кадмопон (смесь CdS и BaSO4)', 'mentioned', 144, 'именуемая кадмопоном', { kind: 'other' }],
      [null, 'амальгама (ртутный раствор металлов)', 'mentioned', 144, 'называются амальгамой', { kind: 'other' }],
    ],
    R: [
      ['2ZnS + 3O2 → 2ZnO + 2SO2', '2ZnS + 3O2 -> 2ZnO + 2SO2', 'redox', 't°', 140, { note: 'обжиг цинковой обманки' }],
      ['ZnO + C → Zn + CO', 'ZnO + C -> Zn + CO', 'redox', 't°', 140],
      ['ZnO + CO → Zn + CO2', 'ZnO + CO -> Zn + CO2', 'redox', 't°', 140],
      ['2Zn + O2 → 2ZnO', '2Zn + O2 -> 2ZnO', 'combination', 't°', 140, { note: '«только при высокой температуре»' }],
      ['Zn + Cl2 → ZnCl2', 'Zn + Cl2 -> ZnCl2', 'combination', 't°', 140],
      ['Zn + S ZnS', 'Zn + S -> ZnS', 'combination', 't°', 140, { note: 'знак стрелки потерян в текстовом слое PDF' }],
      ['Zn + 2HCl → ZnCl2 + H2', 'Zn + 2HCl -> ZnCl2 + H2', 'substitution', null, 141],
      ['Zn + H2SO4 → ZnSO4 + H2', 'Zn + H2SO4 -> ZnSO4 + H2', 'substitution', 'H2SO4 разб.', 141],
      ['Zn + 2H2SO4 → ZnSO4 + SO2 + 2H2O. (кoнц.)', 'Zn + 2H2SO4 -> ZnSO4 + SO2 + 2H2O', 'redox', 'H2SO4 конц.', 141],
      ['3Zn + 8HNO3 → 3Zn(NO3)2 + 2NO + 4H2O, (конц.)', '3Zn + 8HNO3 -> 3Zn(NO3)2 + 2NO + 4H2O', 'redox', 'HNO3 (в книге «конц.»)', 141, { note: 'в книге помечено «(конц.)»; обычно NO образуется с разбавленной HNO3 — проверить' }],
      ['4Zn + 10HNO3 → 4Zn(NO3)2 + N2O + 5H2O, (разб.)', '4Zn + 10HNO3 -> 4Zn(NO3)2 + N2O + 5H2O', 'redox', 'HNO3 разб.', 141],
      ['4Zn + 10HNO3 → 4Zn(NO3)2 + NH4NO3 + 3H2O. (сильно разб.)', '4Zn + 10HNO3 -> 4Zn(NO3)2 + NH4NO3 + 3H2O', 'redox', 'HNO3 сильно разб.', 141],
      ['Zn + 2NaOH + 2H2O = Na2[Zn(OH)4] + H2', 'Zn + 2NaOH + 2H2O -> Na2[Zn(OH)4] + H2', 'redox', null, 142, { note: 'амфотерность цинка' }],
      ['ZnCO3 = ZnO + CO2', 'ZnCO3 -> ZnO + CO2', 'decomposition', 't°', 142, { note: 'обжиг солей' }],
      ['2Zn(NO3)2 = 2ZnO + 4NO2 + O2', '2Zn(NO3)2 -> 2ZnO + 4NO2 + O2', 'decomposition', 't°', 142],
      ['Zn(OH)2 = ZnO + H2O', 'Zn(OH)2 -> ZnO + H2O', 'decomposition', 't°', 142],
      ['ZnO + H2SO4 = ZnSO4 + H2O', 'ZnO + H2SO4 -> ZnSO4 + H2O', 'exchange', null, 142],
      ['ZnO + 2KOH + H2O = K2[Zn(OH)4]', 'ZnO + 2KOH + H2O -> K2[Zn(OH)4]', 'combination', null, 142],
      ['ZnSO4 + 2NaOH = Zn(OH)2 + Na2SO4', 'ZnSO4 + 2NaOH -> Zn(OH)2 + Na2SO4', 'exchange', null, 142],
      ['CdSO4 + 2NaOH = Cd(OH)2 + Na2SO4', 'CdSO4 + 2NaOH -> Cd(OH)2 + Na2SO4', 'exchange', null, 142],
      ['Zn(OH)2 + H2SO4 = ZnSO4 + H2O', 'Zn(OH)2 + H2SO4 -> ZnSO4 + 2H2O', 'neutralization', null, 142, { note: 'в книге «+ H2O» без коэффициента 2 (не уравнено); исправлено' }],
      ['Zn(OH)2 + 2NaOH = Na2[Zn(OH)4]', 'Zn(OH)2 + 2NaOH -> Na2[Zn(OH)4]', 'combination', null, 143],
      ['2Hg + O2 = 2HgO', '2Hg + O2 -> 2HgO', 'combination', '≈357 °C', 143],
      ['Hg(NO3)2 = Hg + 2NO2 + O2', 'Hg(NO3)2 -> Hg + 2NO2 + O2', 'decomposition', 't°', 143],
      ['Hg(NO3)2 + 2NaOH = HgO + 2NaNO3 + H2O', 'Hg(NO3)2 + 2NaOH -> HgO + 2NaNO3 + H2O', 'exchange', null, 143],
      ['Hg + 4HNO3 = Hg(NO3)2 + 2NO2 + 2H2O', 'Hg + 4HNO3 -> Hg(NO3)2 + 2NO2 + 2H2O', 'redox', null, 143, { note: 'в книге «на разбавленную азотную кислоту»; NO2 характерен для конц. HNO3' }],
    ],
    L: [],
  },
  '31': {
    S: [
      ['Cr', 'хром', 'studied', 144, 'Чистый хром получают'],
      ['Cr2O3', 'оксид хрома(III)', 'reagent', 144, 'оксида хрома(III) металлом алюминием'],
      ['Al', 'алюминий', 'reagent', 144, 'металлом алюминием'],
      ['Al2O3', 'оксид алюминия', 'obtained', 144, 'Al2O3 + 2Cr', { note: 'только формула' }],
      ['FeO*Cr2O3', 'хромистый железняк', 'reagent', 144, 'хромистого железняка', { mineral: true, aliases: ['Fe(CrO2)2'] }],
      ['C', 'кокс', 'reagent', 144, 'железняка коксом'],
      ['Fe', 'железо', 'obtained', 144, 'смесь хрома и железа'],
      ['CO', 'оксид углерода(II)', 'obtained', 144, '4CO', { note: 'только формула' }],
      ['H2SO4', 'серная кислота (разб.)', 'reagent', 145, 'разбавленными серной и соляной'],
      ['Cr2(SO4)3', 'сульфат хрома(III)', 'obtained', 145, 'Cr2(SO4)3 + 3H2', { note: 'только формула' }],
      ['H2', 'водород', 'obtained', 145, 'CrCl2 + H2'],
      ['HCl', 'соляная кислота', 'reagent', 145, 'Cr + 2HCl'],
      ['CrCl2', 'хлорид хрома(II)', 'obtained', 145, 'CrCl2 + H2', { note: 'только формула' }],
      ['CrCl3', 'хлорид хрома(III)', 'obtained', 145, 'соли CrCl3'],
      ['HNO3', 'азотная кислота (конц.)', 'mentioned', 145, 'концентрированной азотной', { formulaInBook: false, note: 'хром не взаимодействует (пассивация)' }],
      ['O2', 'кислород', 'reagent', 145, 'взаимодействуя с кислородом'],
      ['N2', 'азот', 'reagent', 146, '2Cr + N2'],
      ['CrN', 'нитрид хрома', 'obtained', 146, '2CrN', { note: 'только формула' }],
      ['S', 'сера', 'reagent', 146, '2Cr + 3S'],
      ['Cr2S3', 'сульфид хрома(III)', 'obtained', 146, 'Cr2S3', { note: 'только формула' }],
      ['Cl2', 'хлор', 'reagent', 146, '2Cr + 3Cl2'],
      ['H2O', 'вода (водяные пары)', 'reagent', 146, 'с водяными парами'],
    ],
    R: [
      ['Cr2O3 + 2Al → Al2O3 + 2Cr', 'Cr2O3 + 2Al -> Al2O3 + 2Cr', 'redox', 't°', 144, { note: 'алюминотермия' }],
      ['FeO.Cr2O3 + 4C→ 2Cr + Fe + 4CO', 'FeO*Cr2O3 + 4C -> 2Cr + Fe + 4CO', 'redox', 't°', 144, { note: 'восстановление хромистого железняка коксом (феррохром)' }],
      ['2Cr + 3H2SO4 → Cr2(SO4)3 + 3H2', '2Cr + 3H2SO4 -> Cr2(SO4)3 + 3H2', 'substitution', 't°', 145, { note: '«при нагревании», разб. H2SO4' }],
      ['Cr + 2HCl → CrCl2 + H2', 'Cr + 2HCl -> CrCl2 + H2', 'substitution', 't°', 145],
      ['4Cr + 3O2 → 2Cr2O3', '4Cr + 3O2 -> 2Cr2O3', 'combination', 't°', 146],
      ['2Cr + N2 = 2CrN', '2Cr + N2 -> 2CrN', 'combination', 't°', 146],
      ['2Cr + 3S = Cr2S3', '2Cr + 3S -> Cr2S3', 'combination', 't°', 146],
      ['2Cr + 3Cl2 = 2CrCl3', '2Cr + 3Cl2 -> 2CrCl3', 'combination', 't°', 146],
      ['2Cr + 3H2O = Cr2O3 + 3H2', '2Cr + 3H2O -> Cr2O3 + 3H2', 'substitution', 't°', 146, { note: '«при накаливании» с водяными парами' }],
    ],
    L: [],
  },
  '32': {
    S: [
      ['CrO', 'оксид хрома(II)', 'studied', 146, 'Оксид хрома(II) – основный оксид'],
      ['Cr2O3', 'оксид хрома(III)', 'studied', 147, 'Оксид хрома(III) – устойчивое соединение'],
      ['CrO3', 'оксид хрома(VI)', 'studied', 148, 'Оксид хрома(VI) — кислотный оксид'],
      ['Cr', 'хром (ртутная амальгама хрома)', 'reagent', 146, 'амальгамы хрома'],
      ['O2', 'кислород', 'reagent', 146, '2Cr + O2'],
      ['CrCl2', 'хлорид хрома(II)', 'obtained', 146, 'Cr → CrCl2'],
      ['Cr(OH)2', 'гидроксид хрома(II)', 'studied', 147, 'Гидроксид хрома(II) Cr(OH)2'],
      ['HCl', 'соляная кислота', 'reagent', 147, 'CrO + 2HCl'],
      ['H2O', 'вода', 'obtained', 147, 'CrCl2 + H2O'],
      ['NaOH', 'щелочь (NaOH)', 'reagent', 147, 'CrCl2 + 2NaOH'],
      ['NaCl', 'хлорид натрия', 'obtained', 147, 'Cr(OH)2 + 2NaCl', { note: 'только формула' }],
      ['Cr(OH)3', 'гидроксид хрома(III)', 'studied', 147, 'Гидроксид хрома(III) также обладает'],
      ['CrCl3', 'хлорид хрома(III)', 'obtained', 147, '2CrCl3 + H2'],
      ['H2', 'водород', 'obtained', 147, '2CrCl3 + H2'],
      ['HNO3', 'азотная кислота', 'reagent', 147, 'Cr2O3 + 6HNO3'],
      ['Cr(NO3)3', 'нитрат хрома(III)', 'obtained', 147, '2Cr(NO3)3', { note: 'только формула' }],
      ['NaCrO2', 'хромит натрия', 'obtained', 147, '2NaCrO2', { note: 'только формула' }],
      ['(NH4)2Cr2O7', 'дихромат аммония', 'reagent', 147, 'накаливания дихромата аммония'],
      ['N2', 'азот', 'obtained', 147, 'Cr2O3 + N2'],
      ['Na3[Cr(OH)6]', 'гексагидроксохромат(III) натрия', 'obtained', 148, 'Na3[Cr(OH)6]', { kind: 'salt', note: 'только формула' }],
      ['Cr^2+', 'ион хрома(II)', 'mentioned', 147, '+2 (Cr2+)', { kind: 'other' }],
      ['Cr^3+', 'ион хрома(III)', 'mentioned', 147, '+3 (Cr3+)', { kind: 'other' }],
      ['K2SO4*Cr2(SO4)3*12H2O', 'калиево-хромистые квасцы', 'mentioned', 148, 'калиево-хромистые квасцы', { note: 'так в книге (12H2O); общепринятая формула K2SO4·Cr2(SO4)3·24H2O' }],
      ['(NH4)2SO4*Cr2(SO4)3*6H2O', 'аммониево-хромистые квасцы', 'mentioned', 148, 'аммониево-хромистые квасцы', { note: 'так в книге (6H2O); общепринятая формула (NH4)2SO4·Cr2(SO4)3·24H2O' }],
      ['Na2CrO4', 'хромат натрия', 'obtained', 148, 'соль хромат натрия'],
      ['S', 'сера', 'reagent', 148, '3S + 4CrO3'],
      ['SO2', 'оксид серы(IV)', 'obtained', 148, '3SO2 + 2Cr2O3', { note: 'только формула' }],
      ['K2Cr2O7', 'дихромат калия', 'reagent', 148, 'дихромат калия (K2Cr2O7)'],
      ['H2SO4', 'серная кислота (конц.)', 'reagent', 148, 'концентрированной серной кислотой'],
      ['K2SO4', 'сульфат калия', 'obtained', 148, '2CrO3 + K2SO4', { note: 'только формула' }],
      ['H2CrO4', 'хромовая кислота', 'obtained', 148, 'H2CrO4 — хромовая'],
      ['H2Cr2O7', 'дихромовая кислота', 'obtained', 148, 'H2Cr2O7 – дихромовая'],
      ['Na2SO3', 'сульфит натрия', 'reagent', 149, '3Na2SO3+ K2Cr2O7', { note: 'только формула' }],
      ['Na2SO4', 'сульфат натрия', 'obtained', 149, '3Na2SO4 + K2SO4', { note: 'только формула' }],
      ['Cr2(SO4)3', 'сульфат хрома(III)', 'obtained', 149, 'Cr2(SO4)3 + 4H2O'],
      ['FeSO4', 'сульфат железа(II)', 'reagent', 149, '6FeSO4 + K2Cr2O7'],
      ['Fe2(SO4)3', 'сульфат железа(III)', 'obtained', 149, '3Fe2(SO4)3', { note: 'только формула' }],
      ['CrSO4', 'сульфат хрома(II)', 'mentioned', 149, 'Cr(OH)2 → CrSO4', { note: 'в схеме соединений хрома' }],
      ['K2CrO4', 'хромат калия', 'mentioned', 149, 'H2CrO4 → K2CrO4', { note: 'в схеме соединений хрома' }],
      ['Fe^2+', 'ион железа(II)', 'mentioned', 150, '3 Fe2+ –1ē Fe3+', { kind: 'other', inWorkedExample: true }],
      ['Fe^3+', 'ион железа(III)', 'mentioned', 150, '3 Fe2+ –1ē Fe3+', { kind: 'other', inWorkedExample: true }],
      ['KI', 'йодид калия', 'reagent', 150, 'K2Cr2O7 + KI + H2SO4', { inWorkedExample: true }],
      ['I2', 'йод', 'obtained', 150, 'Cr2(SO4)3 + I2 + H2O', { inWorkedExample: true }],
      ['BaCrO4', 'хромат бария', 'mentioned', 151, 'осадок (BaCrO4)', { inExercise: true }],
      ['H2S', 'сероводород', 'reagent', 151, 'K2Cr2O7 + H2S', { inExercise: true }],
    ],
    R: [
      ['2Cr + O2 = 2CrO', '2Cr + O2 -> 2CrO', 'combination', null, 146, { note: 'окисление ртутной амальгамы хрома на воздухе' }],
      ['4CrO + O2 = 2Cr2O3', '4CrO + O2 -> 2Cr2O3', 'combination', '>100 °C', 147],
      ['CrO + 2HCl = CrCl2 + H2O', 'CrO + 2HCl -> CrCl2 + H2O', 'exchange', null, 147],
      ['Cr(OH)2 + 2HCl = CrCl2 + 2H2O', 'Cr(OH)2 + 2HCl -> CrCl2 + 2H2O', 'neutralization', null, 147],
      ['CrCl2 + 2NaOH = Cr(OH)2 + 2NaCl', 'CrCl2 + 2NaOH -> Cr(OH)2 + 2NaCl', 'exchange', null, 147],
      ['4Cr(OH)2 + O2 + 2H2O = 4Cr(OH)3', '4Cr(OH)2 + O2 + 2H2O -> 4Cr(OH)3', 'redox', null, 147],
      ['4Cr(OH)2 + O2 = 2Cr2O3 + 4H2O', '4Cr(OH)2 + O2 -> 2Cr2O3 + 4H2O', 'redox', 't°', 147],
      ['2CrCl2 + 2HCl = 2CrCl3 + H2', '2CrCl2 + 2HCl -> 2CrCl3 + H2', 'redox', null, 147],
      ['Cr2O3 + 6HNO3 = 2Cr(NO3)3 + 3H2O', 'Cr2O3 + 6HNO3 -> 2Cr(NO3)3 + 3H2O', 'exchange', null, 147],
      ['Cr2O3 + 2NaOH = 2NaCrO2 + H2O', 'Cr2O3 + 2NaOH -> 2NaCrO2 + H2O', 'exchange', 't°', 147, { note: 'сплавление' }],
      ['(NH4)2Cr2O7 → Cr2O3 + N2 + 4H2O', '(NH4)2Cr2O7 -> Cr2O3 + N2 + 4H2O', 'redox', 't°', 147, { note: '«искусственный вулкан»; повторяется в примере 1 на с.149' }],
      ['CrCl3 + 3NaOH = Cr(OH)3 + 3NaCl', 'CrCl3 + 3NaOH -> Cr(OH)3 + 3NaCl', 'exchange', null, 147],
      ['Cr(OH)3 + 3HCl = CrCl3 + 3H2O', 'Cr(OH)3 + 3HCl -> CrCl3 + 3H2O', 'neutralization', null, 148],
      ['Cr(OH)3 + 3NaOH = Na3[Cr(OH)6]', 'Cr(OH)3 + 3NaOH -> Na3[Cr(OH)6]', 'combination', null, 148],
      ['CrO3 + 2NaOH = Na2CrO4 + H2O', 'CrO3 + 2NaOH -> Na2CrO4 + H2O', 'exchange', null, 148, { note: 'в тексте опечатка «оксид хрома(III)» вместо (VI)' }],
      ['3S + 4CrO3 = 3SO2 + 2Cr2O3', '3S + 4CrO3 -> 3SO2 + 2Cr2O3', 'redox', null, 148],
      ['4CrO3 = 2Cr2O3 + 3O2', '4CrO3 -> 2Cr2O3 + 3O2', 'decomposition', 't°', 148],
      ['K2Cr2O7 + H2SO4 → 2CrO3 + K2SO4 + H2O', 'K2Cr2O7 + H2SO4 -> 2CrO3 + K2SO4 + H2O', 'exchange', 'H2SO4 конц.', 148],
      ['CrO3 + H2O = H2CrO4', 'CrO3 + H2O -> H2CrO4', 'combination', null, 148, { note: 'при большем количестве воды' }],
      ['2CrO3 + H2O = H2Cr2O7', '2CrO3 + H2O -> H2Cr2O7', 'combination', null, 148, { note: 'при большем количестве CrO3' }],
      ['3Na2SO3+ K2Cr2O7 + 4H2SO4 → → 3Na2SO4 + K2SO4 + Cr2(SO4)3 + 4H2O', '3Na2SO3 + K2Cr2O7 + 4H2SO4 -> 3Na2SO4 + K2SO4 + Cr2(SO4)3 + 4H2O', 'redox', null, 149],
      ['6FeSO4 + K2Cr2O7 + 7H2SO4 = = 3Fe2(SO4)3 + Cr2(SO4)3 + K2SO4 + 7H2O', '6FeSO4 + K2Cr2O7 + 7H2SO4 -> 3Fe2(SO4)3 + Cr2(SO4)3 + K2SO4 + 7H2O', 'redox', null, 149, { note: 'повторяется в примере 2 на с.150' }],
      ['K2Cr2O7 + 6KI + 7H2SO4 = 4K2SO4 + Cr2(SO4)3 + 3I2 + 7H2O', 'K2Cr2O7 + 6KI + 7H2SO4 -> 4K2SO4 + Cr2(SO4)3 + 3I2 + 7H2O', 'redox', null, 151, { inWorkedExample: true, note: 'на с.150 та же схема без коэффициентов' }],
      ['вступая в реакцию с водорастворимыми солями бария, образует осадок (BaCrO4)', 'Na2CrO4 + BaCl2 -> BaCrO4 + 2NaCl', 'exchange', null, 151, { described: true, noEquationInBook: true, inExercise: true, note: 'соль бария в задании не указана; взят BaCl2' }],
      ['K2Cr2O7 + H2S + H2SO4 = Cr2(SO4)3 + S + K2SO4 + H2O', 'K2Cr2O7 + 3H2S + 4H2SO4 -> Cr2(SO4)3 + 3S + K2SO4 + 7H2O', 'redox', null, 151, { inExercise: true, note: 'в книге без коэффициентов (задание «уравняйте»); коэффициенты расставлены' }],
    ],
    L: [],
  },
}
