// Hand-authored inventory data, grade 9 textbook (ru), §33–§41 + practical/lab works.
// S: [formula|null, nameRu (as in book), role, page, quoteHint, extra?]
// R: [bookTextHint|null, cleanedAsciiEquation, type, conditions, page, extra?]
export const DATA = {
  '33': {
    S: [
      ['Mn', 'марганец', 'studied', 152, 'Марганец получают'],
      ['Mn3O4', 'гаусманит (оксид марганца)', 'reagent', 152, 'Mn3O4 – гаусманит', { mineral: true, aliases: ['смесь оксидов марганца(II) и (III)'] }],
      ['Si', 'кремний', 'reagent', 152, 'марганца кремнием'],
      ['SiO2', 'оксид кремния', 'obtained', 152, '3Mn+2SiO2', { note: 'только формула' }],
      ['Al', 'алюминий', 'reagent', 152, '3Mn3O4+ 8Al', { note: 'алюминотермический способ' }],
      ['Al2O3', 'оксид алюминия', 'obtained', 152, '9Mn+4Al2O3', { note: 'только формула' }],
      ['MnO2', 'пиролюзит (оксид марганца(IV))', 'studied', 152, 'MnO2 – пиролюзит', { mineral: true, aliases: ['оксид марганца(IV)'] }],
      ['Mn2O3', 'браунит (оксид марганца(III))', 'mentioned', 152, 'Mn2O3 – браунит', { mineral: true, aliases: ['оксид марганца(III)', 'оксидная пленка'] }],
      ['MnSO4', 'сульфат марганца(II)', 'obtained', 152, 'раствора соли MnSO4'],
      ['O2', 'кислород', 'reagent', 153, '4Mn + 3O2'],
      ['MnO', 'оксид марганца(II)', 'mentioned', 153, 'MnO, MnO2, Mn2O3, Mn3O4'],
      ['H2O', 'вода', 'reagent', 153, 'реакцию с водой'],
      ['Mn(OH)2', 'гидроксид марганца(II)', 'obtained', 153, 'Mn(OH)2 + H2', { note: 'только формула' }],
      ['H2', 'водород', 'obtained', 153, 'вытесняет во'],
      ['Cl2', 'хлор (галогены)', 'reagent', 153, 'Mn + Cl2'],
      ['MnCl2', 'хлорид марганца(II)', 'obtained', 153, 'образует MnCl2'],
      ['S', 'сера', 'reagent', 153, 'галогенами, серой и азотом'],
      ['MnS', 'сульфид марганца(II)', 'obtained', 153, 'MnCl2, MnS'],
      ['N2', 'азот', 'reagent', 153, '3Mn + N2'],
      ['Mn3N2', 'нитрид марганца', 'obtained', 153, 'MnS, Mn3N2'],
      ['HCl', 'соляная кислота', 'reagent', 153, 'Mn + 2HCl'],
      ['H2SO4', 'серная кислота (разб., конц.)', 'reagent', 153, 'концентрированной серной'],
      ['SO2', 'оксид серы(IV)', 'obtained', 153, 'SO2 или NO2'],
      ['HNO3', 'азотная кислота (конц.)', 'reagent', 153, 'Mn + 4HNO3'],
      ['Mn(NO3)2', 'нитрат марганца(II)', 'obtained', 153, 'Mn(NO3)2 + 2NO2', { note: 'только формула' }],
      ['NO2', 'оксид азота(IV)', 'obtained', 153, 'SO2 или NO2'],
      ['MnO*Mn2O3', 'смешанный оксид (MnO·Mn2O3)', 'mentioned', 154, 'Смешанный оксид (MnO . Mn2O3)', { kind: 'oxide', note: 'то же, что Mn3O4' }],
      ['Mn2O7', 'оксид марганца(VII)', 'studied', 154, 'Оксид марганца(VII) Mn2O7'],
      ['KMnO4', 'перманганат калия', 'studied', 154, 'Перманганат калия KMnO4'],
      ['K2SO4', 'сульфат калия', 'obtained', 154, 'Mn2O7 + K2SO4', { note: 'только формула' }],
      ['KCl', 'хлорид калия', 'reagent', 154, '2KMnO4 + 10KCl', { note: 'только формула' }],
      ['K2SO3', 'сульфит калия', 'reagent', 154, '2KMnO4 + K2SO3', { note: 'только формула' }],
      ['KOH', 'гидроксид калия', 'reagent', 154, '+ 2KOH', { note: 'только формула' }],
      ['K2MnO4', 'манганат калия', 'obtained', 154, '2K2MnO4 + H2O', { note: 'в книге только формула' }],
      ['HMnO4', 'марганцевая кислота', 'mentioned', 154, 'Марганцевая кислота (HMnO4)'],
      ['MnSO4*4H2O', 'MnSO4·4H2O (микроудобрение)', 'mentioned', 155, 'MnSO4.4H2O', { note: 'производство микроудобрений' }],
      ['KNO3', 'нитрат калия', 'reagent', 155, 'гидроксида и нитрата калия', { inWorkedExample: true }],
      ['KNO2', 'нитрит калия', 'obtained', 155, 'K2MnO4 + KNO2', { inWorkedExample: true, note: 'только формула' }],
      ['Na2SO3', 'сульфит натрия', 'reagent', 156, 'KMnO4 + Na2SO3 + H2SO4', { inExercise: true }],
      ['NaNO2', 'нитрит натрия', 'reagent', 156, 'KMnO4 + NaNO2 + KOH', { inExercise: true }],
      ['FeSO4', 'сульфат железа(II)', 'reagent', 156, 'из соли FeSO4', { inExercise: true }],
      ['Fe2(SO4)3', 'сульфат железа(III)', 'obtained', 156, 'соль Fe2(SO4)3', { inExercise: true }],
      ['H2O2', 'пероксид водорода', 'reagent', 157, 'H2O2 + KMnO4 + H2SO4', { inExercise: true, note: 'только формула' }],
      ['H2S', 'сероводород', 'reagent', 157, 'H2S + KMnO4 + H2SO4', { inExercise: true, note: 'только формула' }],
      ['KClO3', 'хлорат калия', 'reagent', 157, 'MnO2 + KClO3 + KOH', { inExercise: true, note: 'только формула' }],
      ['H2MnO4', 'марганцовистая кислота (так в задании)', 'mentioned', 157, 'H2MnO4 + KCl + H2O', { kind: 'acid', inExercise: true, note: 'в книге продукт записан H2MnO4; по смыслу реакции — K2MnO4' }],
      ['HNO2', 'азотистая кислота', 'reagent', 157, 'KMnO4 + HNO2 + H2SO4', { inExercise: true, note: 'только формула' }],
    ],
    R: [
      ['Mn3O4+2Si → 3Mn+2SiO2', 'Mn3O4 + 2Si -> 3Mn + 2SiO2', 'redox', 't°, электропечь', 152],
      ['3Mn3O4+ 8Al → 9Mn+4Al2O3', '3Mn3O4 + 8Al -> 9Mn + 4Al2O3', 'redox', 't°', 152, { note: 'алюминотермия' }],
      ['4Mn + 3O2 = 2Mn2O3', '4Mn + 3O2 -> 2Mn2O3', 'combination', 't°', 153],
      ['Mn + 2H2O = Mn(OH)2 + H2', 'Mn + 2H2O -> Mn(OH)2 + H2', 'substitution', 't°', 153],
      ['Mn + Cl2 = MnCl2', 'Mn + Cl2 -> MnCl2', 'combination', 't°', 153],
      ['Mn + S = MnS', 'Mn + S -> MnS', 'combination', 't°', 153],
      ['3Mn + N2 = Mn3N2', '3Mn + N2 -> Mn3N2', 'combination', 't°', 153],
      ['Mn + 2HCl = MnCl2 + H2', 'Mn + 2HCl -> MnCl2 + H2', 'substitution', null, 153],
      ['Mn + H2SO4 = MnSO4 + H2', 'Mn + H2SO4 -> MnSO4 + H2', 'substitution', 'H2SO4 разб.', 153],
      ['Mn + 2H2SO4 = MnSO4 + SO2 + 2H2O', 'Mn + 2H2SO4 -> MnSO4 + SO2 + 2H2O', 'redox', 'H2SO4 конц.', 153],
      ['Mn + 4HNO3 = Mn(NO3)2 + 2NO2 + 2H2O', 'Mn + 4HNO3 -> Mn(NO3)2 + 2NO2 + 2H2O', 'redox', 'HNO3 конц.', 153],
      ['2KMnO4 + H2SO4 = Mn2O7 + K2SO4 + H2O', '2KMnO4 + H2SO4 -> Mn2O7 + K2SO4 + H2O', 'exchange', null, 154],
      ['2Mn2O7 = 4MnO2 + 3O2', '2Mn2O7 -> 4MnO2 + 3O2', 'decomposition', 't°', 154],
      ['2KMnO4 + 10KCl + 8H2SO4 = 6K2SO4 + 2MnSO4 + 5Cl2 + 8H2O', '2KMnO4 + 10KCl + 8H2SO4 -> 6K2SO4 + 2MnSO4 + 5Cl2 + 8H2O', 'redox', 'кислотная среда', 154],
      ['2KMnO4 + K2SO3 + 2KOH = K2SO4 + 2K2MnO4 + H2O', '2KMnO4 + K2SO3 + 2KOH -> K2SO4 + 2K2MnO4 + H2O', 'redox', 'щелочная среда', 154],
      ['2KMnO4 + 3K2SO3 + H2O = 2MnO2 + 3K2SO4 + 2KOH', '2KMnO4 + 3K2SO3 + H2O -> 2MnO2 + 3K2SO4 + 2KOH', 'redox', 'нейтральная среда', 154],
      ['2KMnO4 = K2MnO4 + MnO2 + O2', '2KMnO4 -> K2MnO4 + MnO2 + O2', 'decomposition', 't°', 154, { note: 'получение кислорода в лаборатории' }],
      ['MnO2 + 2KOH + KNO3 = K2MnO4 + KNO2 + H2O', 'MnO2 + 2KOH + KNO3 -> K2MnO4 + KNO2 + H2O', 'redox', 't°', 156, { inWorkedExample: true, note: 'на с.155 та же схема без коэффициентов' }],
      ['2KMnO4 + 16HCl = 2KCl + 2MnCl2 + 5Cl2 + 8H2O', '2KMnO4 + 16HCl -> 2KCl + 2MnCl2 + 5Cl2 + 8H2O', 'redox', null, 157, { inWorkedExample: true, note: 'получение хлора; на с.156 схема без коэффициентов' }],
      ['H2O2 + KMnO4 + H2SO4 → K2SO4 + MnSO4 + O2 + H2O', '5H2O2 + 2KMnO4 + 3H2SO4 -> K2SO4 + 2MnSO4 + 5O2 + 8H2O', 'redox', null, 157, { inExercise: true, note: 'в книге без коэффициентов (задание); коэффициенты расставлены' }],
      ['H2S + KMnO4 + H2SO4 → S + MnSO4 + K2SO4 + H2O', '5H2S + 2KMnO4 + 3H2SO4 -> 5S + 2MnSO4 + K2SO4 + 8H2O', 'redox', null, 157, { inExercise: true, note: 'в книге без коэффициентов (задание); коэффициенты расставлены' }],
      ['MnO2 + HCl = MnCl2 + Cl2 + H2O', 'MnO2 + 4HCl -> MnCl2 + Cl2 + 2H2O', 'redox', null, 157, { inExercise: true, note: 'в книге без коэффициентов (задание); коэффициенты расставлены' }],
      ['MnO2 + KClO3 + KOH → H2MnO4 + KCl + H2O', '3MnO2 + KClO3 + 6KOH -> 3K2MnO4 + KCl + 3H2O', 'redox', 't°', 157, { inExercise: true, note: 'в книге продукт «H2MnO4» (ошибка: не уравнивается); исправлено на K2MnO4, коэффициенты расставлены' }],
      ['K2MnO4+ H2O → KMnO4 + MnO2 + KOH', '3K2MnO4 + 2H2O -> 2KMnO4 + MnO2 + 4KOH', 'redox', null, 157, { inExercise: true, note: 'в книге без коэффициентов (задание); коэффициенты расставлены' }],
      ['KMnO4 + HNO2 + H2SO4 → MnSO4 + HNO3 + K2SO4+ H2O', '2KMnO4 + 5HNO2 + 3H2SO4 -> 2MnSO4 + 5HNO3 + K2SO4 + 3H2O', 'redox', null, 157, { inExercise: true, note: 'в книге без коэффициентов (задание); коэффициенты расставлены' }],
      ['FeSO4 + KMnO4 + H2SO4 → Fe2(SO4)3 + K2SO4 + + MnSO4 + H2O', '10FeSO4 + 2KMnO4 + 8H2SO4 -> 5Fe2(SO4)3 + K2SO4 + 2MnSO4 + 8H2O', 'redox', null, 157, { inExercise: true, note: 'в книге без коэффициентов (задание); коэффициенты расставлены' }],
    ],
    L: [],
  },
  '34': {
    S: [
      ['Fe', 'железо', 'studied', 157, 'Химический символ – Fe'],
      ['Fe^2+', 'ион железа(II)', 'mentioned', 158, 'Ион Fe2+', { kind: 'other' }],
      ['Fe^3+', 'ион железа(III)', 'mentioned', 158, 'ион с зарядом +3', { kind: 'other' }],
      ['FeS', 'сульфид железа(II)', 'obtained', 158, 'FeS', { note: 'в инфографике как сырье; уравнение Fe + S на с.159' }],
      ['Fe2O3', 'гематит (красный железняк)', 'reagent', 158, 'гематит Fe2O3', { mineral: true, aliases: ['красный железняк', 'оксид железа(III)'] }],
      ['Fe3O4', 'магнетит (магнитный железняк)', 'reagent', 158, 'Maгнетит Fe3O4', { mineral: true, aliases: ['магнитный железняк', 'железная окалина'] }],
      ['FeCl2', 'хлорид железа(II)', 'mentioned', 158, 'FeCl2', { note: 'в инфографике' }],
      ['FeS2', 'пирит (железный колчедан)', 'mentioned', 158, 'пирит FeS2', { mineral: true }],
      ['FeO2*nH2O', 'лимонит (бурый железняк) — схема', 'mentioned', 158, 'лимонит FeO2 nH2O', { mineral: true, kind: 'oxide', note: 'так в инфографике; в тексте с.159: 2Fe2O3·3H2O (HFeO2·nH2O)' }],
      ['2Fe2O3*3H2O', 'лимонит (бурый железняк)', 'mentioned', 159, 'лимонит – бурый железняк', { mineral: true, kind: 'oxide', note: 'в книге также HFeO2·nH2O' }],
      ['FeCO3', 'сидерит (железный шпат)', 'mentioned', 158, 'сидерит FeCO3', { mineral: true }],
      ['Fe(CO)5', 'пентакарбонил железа', 'mentioned', 158, 'Fe(CO)5', { kind: 'other', note: 'в инфографике только формула' }],
      ['Fe(NO3)3', 'нитрат железа(III)', 'obtained', 158, 'Fe(NO3)3'],
      ['Fe(OH)3', 'гидроксид железа(III) (ржавчина)', 'obtained', 158, 'Fe(OH)3', { aliases: ['ржавчина'] }],
      ['Fe2(SO4)3', 'сульфат железа(III)', 'mentioned', 158, 'Fe2(SO4)3'],
      ['FeSO4', 'сульфат железа(II)', 'obtained', 158, 'FeSO4'],
      ['FeO', 'оксид железа(II)', 'reagent', 159, 'FeO + H2'],
      ['H2', 'водород', 'reagent', 159, 'оксиды железа водородом'],
      ['C', 'углерод', 'reagent', 159, 'водородом, углеродом или угарным газом'],
      ['CO', 'угарный газ', 'reagent', 159, 'угарным газом'],
      ['H2O', 'вода (водяные пары)', 'reagent', 159, 'Fe + H2O'],
      ['CO2', 'углекислый газ', 'obtained', 159, '2Fe + 3CO2'],
      ['Al', 'алюминий', 'reagent', 159, '3Fe3O4 + 8Al'],
      ['Al2O3', 'оксид алюминия', 'obtained', 159, '9Fe + 4Al2O3'],
      ['O2', 'кислород', 'reagent', 159, '3Fe + 2O2'],
      ['FeO*Fe2O3', 'железная окалина (FeO·Fe2O3)', 'obtained', 159, 'или FeO', { kind: 'oxide', note: 'то же, что Fe3O4' }],
      ['N2', 'азот', 'reagent', 159, '2Fe + N2'],
      ['FeN', 'нитрид железа(III)', 'obtained', 159, 'нитрид железа(III)'],
      ['S', 'сера', 'reagent', 159, 'Fe + S'],
      ['Fe3C', 'карбид железа', 'obtained', 159, 'карбид железа'],
      ['Cl2', 'хлор', 'reagent', 159, '2Fe + 3Cl2'],
      ['FeCl3', 'хлорид железа(III)', 'obtained', 159, 'хлорид железа(III)'],
      ['H2SO4', 'серная кислота (разб.)', 'reagent', 160, 'Fe + H2SO4'],
      ['HCl', 'соляная кислота', 'reagent', 160, 'из соляной и разбавленной серной', { formulaInBook: false }],
      ['HNO3', 'азотная кислота (разб., конц.)', 'reagent', 160, 'Fe + 4HNO3'],
      ['NO', 'оксид азота(II)', 'obtained', 160, 'Fe(NO3)3 + NO', { note: 'только формула' }],
      ['Fe(NO3)2', 'нитрат железа(II)', 'obtained', 160, '5Fe(NO3)2', { note: 'только формула' }],
      ['CuSO4', 'сульфат меди(II)', 'reagent', 160, 'Fe + CuSO4'],
      ['Cu', 'медь', 'obtained', 160, 'FeSO4 + Cu'],
      ['KMnO4', 'перманганат калия', 'reagent', 161, 'окисляется перман', { inExercise: true, formulaInBook: false }],
    ],
    R: [
      ['FeO + H2 = Fe + H2O', 'FeO + H2 -> Fe + H2O', 'redox', 't°', 159],
      ['Fe2O3 + 3CO = 2Fe + 3CO2', 'Fe2O3 + 3CO -> 2Fe + 3CO2', 'redox', 't°', 159],
      ['3Fe3O4 + 8Al = 9Fe + 4Al2O3', '3Fe3O4 + 8Al -> 9Fe + 4Al2O3', 'redox', 't°', 159, { note: 'алюминотермия' }],
      ['3Fe + 2O2 → Fe3O4', '3Fe + 2O2 -> Fe3O4', 'combination', 't°', 159, { note: 'железная окалина (FeO·Fe2O3)' }],
      ['2Fe + N2→ 2FeN', '2Fe + N2 -> 2FeN', 'combination', 't°', 159],
      ['Fe + S → FeS', 'Fe + S -> FeS', 'combination', 't°', 159],
      ['3Fe + C → Fe3C', '3Fe + C -> Fe3C', 'combination', 't°', 159],
      ['2Fe + 3Cl2 → 2FeCl3', '2Fe + 3Cl2 -> 2FeCl3', 'combination', 't°', 159],
      ['3Fe + 4H2O = Fe3O4 + 4H2', '3Fe + 4H2O <=> Fe3O4 + 4H2', 'redox', 't°', 160, { note: 'в книге знак «=», но сказано, что реакция обратимая; раскаленное железо + водяной пар' }],
      ['4Fe + 6H2O + 3O2 → 4Fe(OH)3', '4Fe + 6H2O + 3O2 -> 4Fe(OH)3', 'redox', null, 160, { note: 'образование ржавчины' }],
      ['Fe + H2SO4 → FeSO4 + H2', 'Fe + H2SO4 -> FeSO4 + H2', 'substitution', 'H2SO4 разб.', 160],
      ['Fe + 4HNO3 = Fe(NO3)3 + NO + 2H2O', 'Fe + 4HNO3 -> Fe(NO3)3 + NO + 2H2O', 'redox', 'HNO3 разб., t°', 160],
      ['5Fe + 12HNO3 = 5Fe(NO3)2 + N2 + 6H2O', '5Fe + 12HNO3 -> 5Fe(NO3)2 + N2 + 6H2O', 'redox', 'HNO3 сильно разб., 0–10 °C', 160],
      ['Fe + CuSO4 = FeSO4 + Cu', 'Fe + CuSO4 -> FeSO4 + Cu', 'substitution', null, 160],
    ],
    L: [],
  },
  '35': {
    S: [
      ['FeO', 'оксид железа(II)', 'studied', 161, 'степень окисления +2: FeO'],
      ['Fe(OH)2', 'гидроксид железа(II)', 'studied', 161, 'FeO, Fe(OH)2, FeCl2'],
      ['FeCl2', 'хлорид железа(II)', 'studied', 161, 'Из хлорида железа(II)'],
      ['Fe3O4', 'магнетит (смешанный оксид FeO·Fe2O3)', 'studied', 161, 'Fe3O4 [FeO, Fe2O3], магнетит', { mineral: true }],
      ['Fe2O3', 'оксид железа(III)', 'studied', 161, 'степень окисления +3: Fe2O3'],
      ['Fe(OH)3', 'гидроксид железа(III)', 'studied', 161, 'Fe2O3, Fe(OH)3, FeCl3', { aliases: ['осадок бурого цвета'] }],
      ['FeCl3', 'хлорид железа(III)', 'studied', 161, 'Fe(OH)3, FeCl3'],
      ['Fe', 'железо', 'reagent', 161, 'воздействия на железо кислотой'],
      ['HCl', 'соляная кислота', 'reagent', 161, 'Fe + 2HCl'],
      ['H2', 'водород', 'obtained', 161, 'FeCl2 + H2'],
      ['NaOH', 'гидроксид натрия', 'reagent', 161, 'FeCl2 + 2NaOH'],
      ['NaCl', 'хлорид натрия', 'obtained', 161, 'Fe(OH)2 + 2NaCl', { note: 'только формула' }],
      ['H2O', 'вода', 'obtained', 161, 'FeO + H2O'],
      ['K3[Fe(CN)6]', 'гексацианоферрат калия(III) (красная кровяная соль)', 'reagent', 161, 'красная кровяная соль', { kind: 'salt', note: 'формула в уравнении на с.162' }],
      ['KFe[Fe(CN)6]', 'турнбулева синь / берлинская лазурь', 'obtained', 161, 'турнбулевая синь', { kind: 'salt', note: 'в книге одна формула KFe[Fe(CN)6] для турнбулевой сини и берлинской лазури' }],
      ['KCl', 'хлорид калия', 'obtained', 162, '2KCl', { note: 'только формула' }],
      ['Cl2', 'хлор', 'reagent', 162, 'кислоты или хлор'],
      ['H2SO4', 'серная кислота (конц.)', 'reagent', 162, 'концентрированные азотную и серную'],
      ['HNO3', 'азотная кислота (конц.)', 'mentioned', 162, 'концентрированные азотную и серную', { formulaInBook: false }],
      ['Fe2(SO4)3', 'сульфат железа(III)', 'obtained', 162, 'Fe2(SO4)3 + 3SO2'],
      ['SO2', 'оксид серы(IV)', 'obtained', 162, '3SO2 + 6H2O', { note: 'только формула' }],
      ['K4[Fe(CN)6]', 'желтая кровяная соль (гексацианоферрат калия(II))', 'reagent', 162, 'желтая кровяная соль', { kind: 'salt' }],
      ['KNCS', 'роданид калия', 'reagent', 162, 'роданид калия (KNCS)'],
      ['NH4NCS', 'роданид аммония', 'mentioned', 162, 'роданид аммония (NH4NCS)'],
      ['Fe(NCS)3', 'роданид железа(III)', 'obtained', 162, 'роданид железа темно-красного цвета'],
      ['O2', 'кислород', 'reagent', 162, '2H2O + O2'],
      ['FeSO4*7H2O', 'железный купорос', 'studied', 163, 'лезный купорос'],
      ['Fe2(SO4)3*9H2O', 'кристаллогидрат сульфата железа(III)', 'mentioned', 163, 'Fe2(SO4)3 .  9H2O'],
      ['Fe^2+', 'ионы железа (в гемоглобине)', 'mentioned', 163, 'четыре иона железа Fe2+', { kind: 'other' }],
      [null, 'гемоглобин', 'mentioned', 163, 'молекуле гемоглобина', { kind: 'organic' }],
      [null, 'ферроцен', 'mentioned', 163, 'динение ферроцен', { kind: 'organic', note: 'металлоорганическое соединение, формула не дана' }],
    ],
    R: [
      ['Fe + 2HCl = FeCl2 + H2', 'Fe + 2HCl -> FeCl2 + H2', 'substitution', null, 161],
      ['FeCl2 + 2NaOH = Fe(OH)2 + 2NaCl', 'FeCl2 + 2NaOH -> Fe(OH)2 + 2NaCl', 'exchange', null, 161],
      ['Fe(OH)2 → FeO + H2O', 'Fe(OH)2 -> FeO + H2O', 'decomposition', 't°', 161],
      ['2FeCl3 + Fe = 3FeCl2', '2FeCl3 + Fe -> 3FeCl2', 'redox', null, 161],
      ['FeCl2 + K3[Fe(CN)6] = KFe[Fe(CN)6] + 2KCl', 'FeCl2 + K3[Fe(CN)6] -> KFe[Fe(CN)6] + 2KCl', 'exchange', null, 162, { note: 'качественная реакция на Fe2+ (турнбулева синь)' }],
      ['2Fe + 3Cl2 = 2FeCl3', '2Fe + 3Cl2 -> 2FeCl3', 'combination', 't°', 162],
      ['2Fe + 6H2SO4 = Fe2(SO4)3 + 3SO2 + 6H2O', '2Fe + 6H2SO4 -> Fe2(SO4)3 + 3SO2 + 6H2O', 'redox', 'H2SO4 конц., t°', 162],
      ['FeCl3 + 3NaOH = Fe(OH)3 + 3NaCl', 'FeCl3 + 3NaOH -> Fe(OH)3 + 3NaCl', 'exchange', null, 162],
      ['2Fe(OH)3 → Fe2O3 + 3H2O', '2Fe(OH)3 -> Fe2O3 + 3H2O', 'decomposition', 't°', 162],
      ['FeCl3 + K4[Fe(CN)6] = KFe[Fe(CN)6] + 3KCl', 'FeCl3 + K4[Fe(CN)6] -> KFe[Fe(CN)6] + 3KCl', 'exchange', null, 162, { note: 'качественная реакция на Fe3+ (берлинская лазурь)' }],
      ['FeCl3 + 3KNCS = Fe(NCS)3 + 3KCl', 'FeCl3 + 3KNCS -> Fe(NCS)3 + 3KCl', 'exchange', null, 162, { note: 'качественная реакция на Fe3+ (темно-красное окрашивание)' }],
      ['4Fe(OH)2 + 2H2O + O2 = 4Fe(OH)3', '4Fe(OH)2 + 2H2O + O2 -> 4Fe(OH)3', 'redox', null, 162],
    ],
    L: [],
  },
  '36': {
    S: [
      [null, 'чугун (сплав железа и углерода >2,14% C)', 'studied', 165, 'Чугун – сплав железа и углерода', { kind: 'other', note: 'сплав' }],
      [null, 'сталь (сплав железа и углерода <2,14% C)', 'mentioned', 165, 'Сталь – сплав железа и углерода', { kind: 'other', note: 'сплав' }],
      ['C', 'кокс (углерод)', 'reagent', 165, 'кокса – C', { aliases: ['графит'] }],
      ['CaCO3', 'известняк (флюс)', 'reagent', 165, 'флюса – известняка'],
      ['SiO2', 'песок', 'reagent', 165, 'известняка и песка', { note: 'в книге «песок»; формула SiO2 в уравнении на с.166' }],
      ['O2', 'кислород (воздух, кислородное дутье)', 'reagent', 165, 'чистый кислород'],
      ['CO', 'угарный газ (оксид углерода(II))', 'obtained', 165, 'источником CO'],
      ['CO2', 'углекислый газ', 'obtained', 165, 'образование CO2'],
      ['Fe2O3*nH2O', 'гидратированный оксид железа(III) (руда)', 'reagent', 165, 'Fe2O3 . nH2O', { kind: 'oxide', note: 'переменный состав (n)' }],
      ['Fe2O3', 'оксид железа(III) (железная руда)', 'reagent', 165, '3Fe2O3 + CO'],
      ['Fe3O4', 'оксид железа(II,III)', 'obtained', 165, '2Fe3O4 + CO2'],
      ['FeO', 'оксид железа(II)', 'obtained', 166, '3FeO + CO2'],
      ['Fe', 'железо', 'obtained', 166, 'FeO + CO → Fe + CO2'],
      ['CaO', 'оксид кальция', 'obtained', 166, 'CaO + CO2'],
      ['CaSiO3', 'силикат кальция (шлак)', 'obtained', 166, 'CaO + SiO2 → CaSiO3'],
      ['CH4', 'метан (природный газ)', 'reagent', 166, 'Входящий в состав природного газа метан', { kind: 'organic' }],
      ['H2O', 'вода (пары)', 'obtained', 166, 'CO2 + 2H2O'],
      ['H2', 'водород', 'obtained', 166, 'угарным газом и водородом'],
      ['Si', 'кремний', 'mentioned', 166, 'углеродом кокса, крем', { note: 'примеси в чугуне: до 4,5 % Si' }],
      ['Mn', 'марганец', 'mentioned', 166, 'марганцем, фосфором, серой', { note: 'до 1,5 % Mn в чугуне' }],
      ['P', 'фосфор', 'mentioned', 166, 'марганцем, фосфором, серой'],
      ['S', 'сера', 'mentioned', 166, 'марганцем, фосфором, серой'],
      ['Cr', 'хром', 'mentioned', 167, 'имеются Cr, Ni, Si и Mn', { note: 'легированная сталь' }],
      ['Ni', 'никель', 'mentioned', 167, 'имеются Cr, Ni, Si и Mn', { note: 'легированная сталь' }],
      ['Fe3C', 'карбид железа', 'mentioned', 167, 'в форме карбида железа', { formulaInBook: false, note: 'белый (предельный) чугун' }],
    ],
    R: [
      ['C + O2 → CO2', 'C + O2 -> CO2', 'combustion', null, 165, { note: 'доменная печь, стадия 1' }],
      ['CO2 + C → 2CO', 'CO2 + C -> 2CO', 'redox', 't°', 165, { note: 'доменная печь, стадия 2; повторяется на с.166', repeatedOnPages: [166] }],
      ['Fe2O3 . nH2O → Fe2O3 + nH2O (500—700 °C)', 'Fe2O3*nH2O -> Fe2O3 + nH2O', 'decomposition', '500–700 °C', 165, { skipBalance: true, note: 'n — переменное число молекул воды' }],
      ['3Fe2O3 + CO → 2Fe3O4 + CO2 (450—500 °C)', '3Fe2O3 + CO -> 2Fe3O4 + CO2', 'redox', '450–500 °C', 165],
      ['Fe3O4 + CO → 3FeO + CO2 (500—700 °C)', 'Fe3O4 + CO -> 3FeO + CO2', 'redox', '500–700 °C', 166],
      ['FeO + CO → Fe + CO2 (700—800 °C)', 'FeO + CO -> Fe + CO2', 'redox', '700–800 °C', 166],
      ['CaCO3 → CaO + CO2', 'CaCO3 -> CaO + CO2', 'decomposition', 't°', 166, { note: 'образование шлака' }],
      ['CaO + SiO2 → CaSiO3', 'CaO + SiO2 -> CaSiO3', 'combination', 't°', 166, { note: 'шлак' }],
      ['CH4 + 2O2 → CO2 + 2H2O', 'CH4 + 2O2 -> CO2 + 2H2O', 'combustion', null, 166, { note: 'газокислородное дутье' }],
      ['H2O + C → H2 + CO', 'H2O + C -> H2 + CO', 'redox', 't°', 166],
    ],
    L: [],
  },
  '37': {
    S: [
      [null, 'сталь', 'studied', 167, 'Сталь, больше всего используемая', { kind: 'other', note: 'сплав' }],
      ['Fe', 'железо', 'reagent', 168, '2Fe + O2'],
      ['O2', 'кислород (воздуха)', 'reagent', 167, 'кислорода воздуха'],
      ['FeO', 'оксид железа(II)', 'obtained', 167, 'образуется оксид железа(II)'],
      ['P', 'фосфор', 'reagent', 168, '5FeO + 2P'],
      ['P2O5', 'оксид фосфора(V)', 'obtained', 168, 'образует оксид P2O5'],
      ['Si', 'кремний', 'reagent', 168, '2FeO + Si'],
      ['SiO2', 'оксид кремния', 'obtained', 168, '2Fe + SiO2 + Q'],
      ['Mn', 'марганец', 'reagent', 168, 'FeO + Mn'],
      ['MnO', 'оксид марганца(II)', 'obtained', 168, 'Fe + MnO + Q'],
      ['C', 'углерод', 'reagent', 168, 'FeO + C'],
      ['CO', 'оксид углерода(II)', 'obtained', 168, 'газов CO и CO2'],
      ['CO2', 'оксид углерода(IV)', 'obtained', 168, 'газов CO и CO2'],
      ['FeS', 'сульфид железа(II)', 'reagent', 168, 'в виде FeS'],
      ['CaO', 'оксид кальция (известь)', 'reagent', 168, 'с помощью CaO'],
      ['CaS', 'сульфид кальция', 'obtained', 168, 'переходит в CaS'],
      ['Ca3(PO4)2', 'фосфат кальция', 'obtained', 168, 'образует Ca3(PO4)2'],
      [null, 'легирующие добавки: хром, никель, титан, молибден, ванадий, вольфрам', 'mentioned', 168, 'хром, никель, титан, молибден, ванадий, вольфрам', { kind: 'simple', note: 'Cr, Ni, Ti, Mo, V, W; в тексте с.169 также Cr, Ni, Mo, Al' }],
      ['H2', 'водород', 'reagent', 170, 'применяются водород и природный газ', { note: 'бескоксовое получение железа' }],
      ['P2O5', 'высший оксид фосфора', 'mentioned', 171, 'Это фосфор, P2O5', { inWorkedExample: true }],
      ['PH3', 'фосфин', 'mentioned', 171, 'РH3- фосфин', { inWorkedExample: true, kind: 'other' }],
      ['CuSO4*5H2O', 'медный купорос', 'mentioned', 171, 'медного купороса', { inWorkedExample: true, note: 'бордосская жидкость' }],
      ['CuSO4', 'сульфат меди(II) (безводный)', 'obtained', 171, 'безводная соль сульфат меди(II)', { inWorkedExample: true }],
      ['HCl', 'соляная кислота', 'reagent', 172, 'раствора соляной кислоты', { inWorkedExample: true }],
      ['Mg', 'магний', 'mentioned', 172, 'Ответ: магний Mg', { inWorkedExample: true }],
      ['H2SO4', 'серная кислота', 'reagent', 172, 'серной кислоте', { inWorkedExample: true, formulaInBook: false }],
      ['Cr2O3', 'оксид хрома(III)', 'mentioned', 173, 'Cr2O3 — оксид хрома(III)', { inWorkedExample: true }],
      ['Al2O3*3BeO*6SiO2', 'берилл', 'mentioned', 173, 'формула минерала берилла', { inWorkedExample: true, mineral: true, kind: 'salt', aliases: ['Al2Be3Si6O18'] }],
      ['Al', 'алюминий', 'reagent', 173, 'из 10,8 г алюминия', { inWorkedExample: true }],
      ['Al2O3', 'оксид алюминия', 'obtained', 173, 'получения оксида алюминия', { inWorkedExample: true }],
      ['Na2CO3', 'карбонат натрия', 'obtained', 174, 'смеси карбоната натрия', { inWorkedExample: true }],
      ['NaHCO3', 'гидрокарбонат натрия', 'reagent', 174, 'гидрокарбоната натрия', { inWorkedExample: true }],
      ['FeSO4', 'сульфат железа(II)', 'obtained', 175, 'CuSO4+Fe=FeSO4+Cu', { inWorkedExample: true }],
      ['Cu', 'медь', 'obtained', 175, 'Ответ: 3,2 г Cu', { inWorkedExample: true }],
      ['N2', 'азот', 'reagent', 175, 'с 2,8 г азота', { inWorkedExample: true }],
      ['Ca', 'кальций', 'mentioned', 175, 'Это — кальций', { inWorkedExample: true }],
    ],
    R: [
      ['2Fe + O2 → 2FeO + Q', '2Fe + O2 -> 2FeO + Q', 'combination', 't°', 168, { note: 'передел чугуна в сталь' }],
      ['5FeO + 2P → 5Fe + P2O5 + Q', '5FeO + 2P -> 5Fe + P2O5 + Q', 'redox', 't°', 168],
      ['2FeO + Si → 2Fe + SiO2 + Q', '2FeO + Si -> 2Fe + SiO2 + Q', 'redox', 't°', 168],
      ['FeO + Mn → Fe + MnO + Q', 'FeO + Mn -> Fe + MnO + Q', 'redox', 't°', 168],
      ['FeO + C → Fe + CO + Q', 'FeO + C -> Fe + CO + Q', 'redox', 't°', 168],
      ['FeS + CaO = CaS + FeO', 'FeS + CaO -> CaS + FeO', 'exchange', 't°', 168, { note: 'удаление серы в шлак' }],
      ['3CaO + P2O5 = Ca3 (PO4)2', '3CaO + P2O5 -> Ca3(PO4)2', 'combination', 't°', 168, { note: 'удаление фосфора в шлак' }],
      ['MeO + 2HCl = MeCl2 + H2', 'MeO + 2HCl -> MeCl2 + H2O', 'exchange', null, 172, { isGeneralScheme: true, inWorkedExample: true, note: 'в книге продукт «H2» (опечатка, должно быть H2O); ответ — Mg' }],
      ['Me2On + nH2SO4= Me2(SO4)n + nH2O', 'Me2On + nH2SO4 -> Me2(SO4)n + nH2O', 'exchange', null, 172, { isGeneralScheme: true, inWorkedExample: true, note: 'ответ — Cr2O3' }],
      ['2Al + 3O2 = 2Al2O3', '4Al + 3O2 -> 2Al2O3', 'combination', null, 173, { inWorkedExample: true, note: 'в книге «2Al + 3O2 = 2Al2O3» (не уравнено); исправлено на 4Al' }],
      ['2NaHCO3 → Na2CO3 + CO2 + H2O', '2NaHCO3 -> Na2CO3 + CO2 + H2O', 'decomposition', 't°', 174, { inWorkedExample: true }],
      ['CuSO4+Fe=FeSO4+Cu', 'CuSO4 + Fe -> FeSO4 + Cu', 'substitution', null, 175, { inWorkedExample: true }],
      ['3Me + N2 = Me3N2', '3Me + N2 -> Me3N2', 'combination', null, 175, { isGeneralScheme: true, inWorkedExample: true, note: 'ответ — кальций' }],
    ],
    L: [],
  },
}
