import type { ReactorEquationTerm } from './reactorEquationBalance'
import type { ReactionClass } from './reactionTypeTaxonomy'

export type BalanceLessonKind = 'synthesis' | 'practice_only'

export type BalanceLesson = {
  id: string
  /** i18n key or plain RU title fallback */
  titleRu: string
  titleEn: string
  kind: BalanceLessonKind
  reactionClass: ReactionClass
  /** Продукт каталога для синтеза (null для practice_only) */
  productId: string | null
  /** Начальные коэффициенты = 1 */
  left: readonly Omit<ReactorEquationTerm, 'id'>[]
  /** Правильные коэффициенты после баланса (для проверки урока) */
  correctLeftCoeffs: readonly number[]
  correctProductCoeff: number
  /** Для practice_only: отображаемое уравнение */
  displayEquationRu?: string
  displayEquationEn?: string
  /** Как собрать реакцию в реакторе */
  howToRu: string
  howToEn: string
  methodHint: 'substitution' | 'electron' | 'both'
  gradeHint: 7 | 8 | 9
}

/**
 * Учебные примеры 7–9 классов (Kimyo / школьный курс).
 * synthesis — загружается в реактор; practice_only — только балансировка (два продукта).
 */
export const BALANCE_LESSON_BANK: readonly BalanceLesson[] = [
  {
    id: 'h2-o2-h2o',
    titleRu: 'Образование воды: H₂ + O₂ → H₂O',
    titleEn: 'Water formation: H₂ + O₂ → H₂O',
    kind: 'synthesis',
    reactionClass: 'combination',
    productId: 'h2o',
    left: [
      { z: 1, coeff: 1, diatomic: true },
      { z: 8, coeff: 1, diatomic: true },
    ],
    correctLeftCoeffs: [2, 1],
    correctProductCoeff: 2,
    howToRu: 'Добавьте H (×2, двухатомный) и O (×1, двухатомный). Выберите продукт H₂O.',
    howToEn: 'Add H (×2, diatomic) and O (×1, diatomic). Product: H₂O.',
    methodHint: 'substitution',
    gradeHint: 7,
  },
  {
    id: 'na-cl-nacl',
    titleRu: 'Соединение: 2Na + Cl₂ → 2NaCl',
    titleEn: 'Combination: 2Na + Cl₂ → 2NaCl',
    kind: 'synthesis',
    reactionClass: 'combination',
    productId: 'nacl',
    left: [
      { z: 11, coeff: 1 },
      { z: 17, coeff: 1, diatomic: true },
    ],
    correctLeftCoeffs: [2, 1],
    correctProductCoeff: 2,
    howToRu: 'Na + Cl₂ (двухатомный) → поваренная соль.',
    howToEn: 'Sodium + chlorine → table salt.',
    methodHint: 'substitution',
    gradeHint: 7,
  },
  {
    id: 'mg-o2-mgo',
    titleRu: 'Горение магния: 2Mg + O₂ → 2MgO',
    titleEn: 'Magnesium combustion: 2Mg + O₂ → 2MgO',
    kind: 'synthesis',
    reactionClass: 'combustion',
    productId: 'mgo',
    left: [
      { z: 12, coeff: 1 },
      { z: 8, coeff: 1, diatomic: true },
    ],
    correctLeftCoeffs: [2, 1],
    correctProductCoeff: 2,
    howToRu: 'Mg + O₂ → MgO. Яркая вспышка при горении ленты.',
    howToEn: 'Mg + O₂ → MgO.',
    methodHint: 'substitution',
    gradeHint: 7,
  },
  {
    id: 'fe-o2-fe2o3',
    titleRu: 'Горение железа: 4Fe + 3O₂ → 2Fe₂O₃',
    titleEn: 'Iron combustion: 4Fe + 3O₂ → 2Fe₂O₃',
    kind: 'synthesis',
    reactionClass: 'combustion',
    productId: 'fe2o3',
    left: [
      { z: 26, coeff: 1 },
      { z: 8, coeff: 1, diatomic: true },
    ],
    correctLeftCoeffs: [4, 3],
    correctProductCoeff: 2,
    howToRu: 'Fe + O₂ → Fe₂O₃. Подбор коэффициентов 4:3:2.',
    howToEn: 'Iron oxidizes to Fe₂O₃.',
    methodHint: 'both',
    gradeHint: 7,
  },
  {
    id: 'c-o2-co2',
    titleRu: 'Горение углерода: C + O₂ → CO₂',
    titleEn: 'Carbon combustion: C + O₂ → CO₂',
    kind: 'synthesis',
    reactionClass: 'combustion',
    productId: 'co2',
    left: [
      { z: 6, coeff: 1 },
      { z: 8, coeff: 1, diatomic: true },
    ],
    correctLeftCoeffs: [1, 1],
    correctProductCoeff: 1,
    howToRu: 'C + O₂ → CO₂. Полное горение.',
    howToEn: 'Complete combustion of carbon.',
    methodHint: 'substitution',
    gradeHint: 7,
  },
  {
    id: 'al-o2-al2o3',
    titleRu: 'Горение алюминия: 4Al + 3O₂ → 2Al₂O₃',
    titleEn: 'Aluminum combustion: 4Al + 3O₂ → 2Al₂O₃',
    kind: 'synthesis',
    reactionClass: 'combustion',
    productId: 'al2o3',
    left: [
      { z: 13, coeff: 1 },
      { z: 8, coeff: 1, diatomic: true },
    ],
    correctLeftCoeffs: [4, 3],
    correctProductCoeff: 2,
    howToRu: 'Al + O₂ → Al₂O₃. Термит и защитная плёнка.',
    howToEn: 'Al + O₂ → Al₂O₃.',
    methodHint: 'both',
    gradeHint: 8,
  },
  {
    id: 'cu-o2-cuo',
    titleRu: 'Окисление меди: 2Cu + O₂ → 2CuO',
    titleEn: 'Copper oxidation: 2Cu + O₂ → 2CuO',
    kind: 'synthesis',
    reactionClass: 'combustion',
    productId: 'cuo',
    left: [
      { z: 29, coeff: 1 },
      { z: 8, coeff: 1, diatomic: true },
    ],
    correctLeftCoeffs: [2, 1],
    correctProductCoeff: 2,
    howToRu: 'Медь чернеет при нагревании на воздухе.',
    howToEn: 'Copper turns black (CuO) on heating.',
    methodHint: 'substitution',
    gradeHint: 8,
  },
  {
    id: 's-o2-so2',
    titleRu: 'Горение серы: S + O₂ → SO₂',
    titleEn: 'Sulfur combustion: S + O₂ → SO₂',
    kind: 'synthesis',
    reactionClass: 'combustion',
    productId: 'so2',
    left: [
      { z: 16, coeff: 1 },
      { z: 8, coeff: 1, diatomic: true },
    ],
    correctLeftCoeffs: [1, 1],
    correctProductCoeff: 1,
    howToRu: 'S + O₂ → SO₂. Синее пламя, резкий запах.',
    howToEn: 'S + O₂ → SO₂.',
    methodHint: 'substitution',
    gradeHint: 8,
  },
  {
    id: 'cao-h2o',
    titleRu: 'Гашение извести: CaO + H₂O → Ca(OH)₂',
    titleEn: 'Slaking lime: CaO + H₂O → Ca(OH)₂',
    kind: 'synthesis',
    reactionClass: 'combination',
    productId: 'ca_oh_2',
    left: [
      { z: 20, coeff: 1 },
      { z: 8, coeff: 1 },
      { z: 1, coeff: 1, diatomic: true },
    ],
    correctLeftCoeffs: [1, 1, 1],
    correctProductCoeff: 1,
    howToRu: 'Ca + O + H₂ → Ca(OH)₂. Сильно экзотермично.',
    howToEn: 'Quicklime + water → slaked lime.',
    methodHint: 'substitution',
    gradeHint: 7,
  },
  {
    id: 'so2-o2-so3',
    titleRu: 'Контактный процесс: 2SO₂ + O₂ → 2SO₃',
    titleEn: 'Contact process: 2SO₂ + O₂ → 2SO₃',
    kind: 'synthesis',
    reactionClass: 'catalytic',
    productId: 'so3',
    left: [
      { z: 16, coeff: 1 },
      { z: 8, coeff: 1, diatomic: true },
    ],
    correctLeftCoeffs: [2, 3],
    correctProductCoeff: 2,
    howToRu: '2S + 3O₂ → 2SO₃ (из элементов). В промышленности — окисление SO₂ с V₂O₅.',
    howToEn: '2S + 3O₂ → 2SO₃ from elements; industry oxidizes SO₂ with V₂O₅.',
    methodHint: 'both',
    gradeHint: 9,
  },
  {
    id: 'cao-co2',
    titleRu: 'Соединение: CaO + CO₂ → CaCO₃',
    titleEn: 'Combination: CaO + CO₂ → CaCO₃',
    kind: 'synthesis',
    reactionClass: 'combination',
    productId: 'salt_ca_co3',
    left: [
      { z: 20, coeff: 1 },
      { z: 8, coeff: 1 },
      { z: 6, coeff: 1 },
    ],
    correctLeftCoeffs: [1, 1, 1],
    correctProductCoeff: 1,
    howToRu: 'Ca + O + C → CaCO₃ (карбонат кальция). Обратная реакция к обжигу известняка.',
    howToEn: 'Ca + O + C → calcium carbonate.',
    methodHint: 'substitution',
    gradeHint: 8,
  },
  {
    id: 'nh3-hcl',
    titleRu: 'NH₃ + HCl → NH₄Cl',
    titleEn: 'NH₃ + HCl → NH₄Cl',
    kind: 'synthesis',
    reactionClass: 'combination',
    productId: 'salt_nh4_cl',
    left: [
      { z: 7, coeff: 1 },
      { z: 1, coeff: 1, diatomic: true },
      { z: 17, coeff: 1 },
    ],
    correctLeftCoeffs: [1, 2, 1],
    correctProductCoeff: 1,
    howToRu: 'N + H + Cl → NH₄Cl. Белый дым NH₄Cl в опыте «стеклянная палочка».',
    howToEn: 'N + H + Cl → ammonium chloride.',
    methodHint: 'substitution',
    gradeHint: 9,
  },
  {
    id: 'n2-h2-nh3',
    titleRu: 'Синтез аммиака: N₂ + 3H₂ ⇄ 2NH₃',
    titleEn: 'Ammonia synthesis: N₂ + 3H₂ ⇄ 2NH₃',
    kind: 'synthesis',
    reactionClass: 'combination',
    productId: 'nh3',
    left: [
      { z: 7, coeff: 1, diatomic: true },
      { z: 1, coeff: 1, diatomic: true },
    ],
    correctLeftCoeffs: [1, 3],
    correctProductCoeff: 2,
    howToRu: 'N₂ + H₂ → NH₃. Процесс Габера — обратимая реакция, промышленный катализатор Fe.',
    howToEn: 'Haber process — reversible combination.',
    methodHint: 'both',
    gradeHint: 9,
  },
  {
    id: 'zn-cuso4',
    titleRu: 'Вытеснение меди: Fe + CuSO₄ → FeSO₄ + Cu',
    titleEn: 'Copper displacement: Fe + CuSO₄ → FeSO₄ + Cu',
    kind: 'practice_only',
    reactionClass: 'substitution',
    productId: null,
    left: [{ z: 26, coeff: 1 }],
    correctLeftCoeffs: [1],
    correctProductCoeff: 1,
    displayEquationRu: 'Fe + CuSO₄ → FeSO₄ + Cu',
    displayEquationEn: 'Fe + CuSO₄ → FeSO₄ + Cu',
    howToRu: 'Ряд активности металлов. Два продукта — только балансировка.',
    howToEn: 'Activity series — practice only.',
    methodHint: 'electron',
    gradeHint: 9,
  },
  {
    id: 'zn-hcl',
    titleRu: 'Zn + 2HCl → ZnCl₂ + H₂',
    titleEn: 'Zn + 2HCl → ZnCl₂ + H₂',
    kind: 'practice_only',
    reactionClass: 'substitution',
    productId: null,
    left: [{ z: 30, coeff: 1 }],
    correctLeftCoeffs: [1],
    correctProductCoeff: 1,
    displayEquationRu: 'Zn + 2HCl → ZnCl₂ + H₂↑',
    displayEquationEn: 'Zn + 2HCl → ZnCl₂ + H₂↑',
    howToRu: 'Для синтеза ZnCl₂: Zn + Cl в реакторе. Газ H₂ — признак реакции.',
    howToEn: 'Synthesize ZnCl₂ from Zn + Cl in reactor.',
    methodHint: 'electron',
    gradeHint: 8,
  },
  {
    id: 'naoh-hcl',
    titleRu: 'Нейтрализация: NaOH + HCl → NaCl + H₂O',
    titleEn: 'Neutralization: NaOH + HCl → NaCl + H₂O',
    kind: 'practice_only',
    reactionClass: 'neutralization',
    productId: null,
    left: [{ z: 11, coeff: 1 }],
    correctLeftCoeffs: [1],
    correctProductCoeff: 1,
    displayEquationRu: 'NaOH + HCl → NaCl + H₂O',
    displayEquationEn: 'NaOH + HCl → NaCl + H₂O',
    howToRu: 'H⁺ + OH⁻ → H₂O. Синтез NaCl: Na + Cl.',
    howToEn: 'Classic neutralization — practice balancing.',
    methodHint: 'substitution',
    gradeHint: 7,
  },
  {
    id: 'bacl2-na2so4',
    titleRu: 'Обмен: BaCl₂ + Na₂SO₄ → BaSO₄↓ + 2NaCl',
    titleEn: 'Exchange: BaCl₂ + Na₂SO₄ → BaSO₄↓ + 2NaCl',
    kind: 'practice_only',
    reactionClass: 'exchange',
    productId: null,
    left: [{ z: 56, coeff: 1 }],
    correctLeftCoeffs: [1],
    correctProductCoeff: 1,
    displayEquationRu: 'BaCl₂ + Na₂SO₄ → BaSO₄↓ + 2NaCl',
    displayEquationEn: 'BaCl₂ + Na₂SO₄ → BaSO₄↓ + 2NaCl',
    howToRu: 'Белый осадок BaSO₄ — качественная на SO₄²⁻.',
    howToEn: 'Barium sulfate precipitate.',
    methodHint: 'substitution',
    gradeHint: 8,
  },
  {
    id: 'agno3-nacl',
    titleRu: 'Обмен: AgNO₃ + NaCl → AgCl↓ + NaNO₃',
    titleEn: 'Exchange: AgNO₃ + NaCl → AgCl↓ + NaNO₃',
    kind: 'practice_only',
    reactionClass: 'exchange',
    productId: null,
    left: [{ z: 47, coeff: 1 }],
    correctLeftCoeffs: [1],
    correctProductCoeff: 1,
    displayEquationRu: 'AgNO₃ + NaCl → AgCl↓ + NaNO₃',
    displayEquationEn: 'AgNO₃ + NaCl → AgCl↓ + NaNO₃',
    howToRu: 'Творожистый осадок AgCl — качественная на Cl⁻.',
    howToEn: 'Silver chloride precipitate.',
    methodHint: 'substitution',
    gradeHint: 8,
  },
  {
    id: 'na2co3-hcl',
    titleRu: 'Обмен: Na₂CO₃ + 2HCl → 2NaCl + H₂O + CO₂↑',
    titleEn: 'Exchange: Na₂CO₃ + 2HCl → 2NaCl + H₂O + CO₂↑',
    kind: 'practice_only',
    reactionClass: 'exchange',
    productId: null,
    left: [{ z: 11, coeff: 1 }],
    correctLeftCoeffs: [1],
    correctProductCoeff: 1,
    displayEquationRu: 'Na₂CO₃ + 2HCl → 2NaCl + H₂O + CO₂↑',
    displayEquationEn: 'Na₂CO₃ + 2HCl → 2NaCl + H₂O + CO₂↑',
    howToRu: 'Выделение CO₂ — признак карбонатов.',
    howToEn: 'CO₂ evolution — carbonate test.',
    methodHint: 'substitution',
    gradeHint: 8,
  },
  {
    id: 'caco3-decomp',
    titleRu: 'Разложение: CaCO₃ → CaO + CO₂',
    titleEn: 'Decomposition: CaCO₃ → CaO + CO₂',
    kind: 'practice_only',
    reactionClass: 'decomposition',
    productId: null,
    left: [{ z: 20, coeff: 1 }],
    correctLeftCoeffs: [1],
    correctProductCoeff: 1,
    displayEquationRu: 'CaCO₃ → CaO + CO₂ (нагрев)',
    displayEquationEn: 'CaCO₃ → CaO + CO₂ (heat)',
    howToRu: 'Обжиг известняка. Синтез CaO: Ca + O.',
    howToEn: 'Limestone roasting — endothermic.',
    methodHint: 'substitution',
    gradeHint: 8,
  },
  {
    id: 'k2cr2o7-ki',
    titleRu: 'ОВР: K₂Cr₂O₇ + KI + H₂SO₄',
    titleEn: 'Redox: K₂Cr₂O₇ + KI + H₂SO₄',
    kind: 'practice_only',
    reactionClass: 'redox',
    productId: null,
    left: [{ z: 24, coeff: 1 }],
    correctLeftCoeffs: [1],
    correctProductCoeff: 1,
    displayEquationRu: 'K₂Cr₂O₇ + 6KI + 7H₂SO₄ → 3I₂ + Cr₂(SO₄)₃ + 4K₂SO₄ + 7H₂O',
    displayEquationEn: 'K₂Cr₂O₇ + 6KI + 7H₂SO₄ → 3I₂ + Cr₂(SO₄)₃ + 4K₂SO₄ + 7H₂O',
    howToRu: 'Cr⁺6 → Cr⁺3, I⁻ → I₂. Электронный баланс.',
    howToEn: 'Dichromate oxidizes iodide — electron balance.',
    methodHint: 'electron',
    gradeHint: 9,
  },
  {
    id: 'h2-cl2-hcl',
    titleRu: 'H₂ + Cl₂ → 2HCl',
    titleEn: 'H₂ + Cl₂ → 2HCl',
    kind: 'synthesis',
    reactionClass: 'combination',
    productId: 'hcl',
    left: [
      { z: 1, coeff: 1, diatomic: true },
      { z: 17, coeff: 1, diatomic: true },
    ],
    correctLeftCoeffs: [1, 1],
    correctProductCoeff: 2,
    howToRu: 'H₂ + Cl₂ → HCl. Двухатомные элементы.',
    howToEn: 'Hydrogen and chlorine form HCl.',
    methodHint: 'substitution',
    gradeHint: 8,
  },
  {
    id: 'ca-o2-cao',
    titleRu: '2Ca + O₂ → 2CaO',
    titleEn: '2Ca + O₂ → 2CaO',
    kind: 'synthesis',
    reactionClass: 'combination',
    productId: 'cao',
    left: [
      { z: 20, coeff: 1 },
      { z: 8, coeff: 1, diatomic: true },
    ],
    correctLeftCoeffs: [2, 1],
    correctProductCoeff: 2,
    howToRu: 'Ca + O₂ → CaO.',
    howToEn: 'Calcium burns to quicklime.',
    methodHint: 'substitution',
    gradeHint: 8,
  },
  {
    id: 'fe-s-fes',
    titleRu: 'Fe + S → FeS',
    titleEn: 'Fe + S → FeS',
    kind: 'synthesis',
    reactionClass: 'combination',
    productId: 'salt_fe2_s',
    left: [
      { z: 26, coeff: 1 },
      { z: 16, coeff: 1 },
    ],
    correctLeftCoeffs: [1, 1],
    correctProductCoeff: 1,
    howToRu: 'Fe + S → сульфид железа(II).',
    howToEn: 'Iron and sulfur form FeS.',
    methodHint: 'substitution',
    gradeHint: 8,
  },
  {
    id: 'cu-s-cus',
    titleRu: 'Cu + S → CuS',
    titleEn: 'Cu + S → CuS',
    kind: 'synthesis',
    reactionClass: 'combination',
    productId: 'salt_cu_s',
    left: [
      { z: 29, coeff: 1 },
      { z: 16, coeff: 1 },
    ],
    correctLeftCoeffs: [1, 1],
    correctProductCoeff: 1,
    howToRu: 'Cu + S → сульфид меди.',
    howToEn: 'Copper and sulfur form CuS.',
    methodHint: 'substitution',
    gradeHint: 8,
  },
  {
    id: 'al-cl2-alcl3',
    titleRu: '2Al + 3Cl₂ → 2AlCl₃',
    titleEn: '2Al + 3Cl₂ → 2AlCl₃',
    kind: 'synthesis',
    reactionClass: 'combination',
    productId: 'salt_al_cl',
    left: [
      { z: 13, coeff: 1 },
      { z: 17, coeff: 1, diatomic: true },
    ],
    correctLeftCoeffs: [2, 3],
    correctProductCoeff: 2,
    howToRu: 'Al + Cl₂ → AlCl₃. Упражнение 7 кл.',
    howToEn: 'Aluminum + chlorine → AlCl₃.',
    methodHint: 'both',
    gradeHint: 7,
  },
  {
    id: 'fe-cl2-fecl3',
    titleRu: '2Fe + 3Cl₂ → 2FeCl₃',
    titleEn: '2Fe + 3Cl₂ → 2FeCl₃',
    kind: 'synthesis',
    reactionClass: 'combination',
    productId: 'salt_fe3_cl',
    left: [
      { z: 26, coeff: 1 },
      { z: 17, coeff: 1, diatomic: true },
    ],
    correctLeftCoeffs: [2, 3],
    correctProductCoeff: 2,
    howToRu: 'Fe + Cl₂ → FeCl₃.',
    howToEn: 'Iron + chlorine → FeCl₃.',
    methodHint: 'both',
    gradeHint: 8,
  },
  {
    id: 'n2-o2-no',
    titleRu: 'N₂ + O₂ ⇄ 2NO',
    titleEn: 'N₂ + O₂ ⇄ 2NO',
    kind: 'synthesis',
    reactionClass: 'combination',
    productId: 'no',
    left: [
      { z: 7, coeff: 1, diatomic: true },
      { z: 8, coeff: 1, diatomic: true },
    ],
    correctLeftCoeffs: [1, 1],
    correctProductCoeff: 2,
    howToRu: 'N₂ + O₂ → NO при высокой температуре.',
    howToEn: 'Nitrogen and oxygen form NO.',
    methodHint: 'substitution',
    gradeHint: 9,
  },
  {
    id: 'p-o2-p2o5',
    titleRu: '4P + 5O₂ → 2P₂O₅',
    titleEn: '4P + 5O₂ → 2P₂O₅',
    kind: 'synthesis',
    reactionClass: 'combination',
    productId: 'p2o5',
    left: [
      { z: 15, coeff: 1 },
      { z: 8, coeff: 1, diatomic: true },
    ],
    correctLeftCoeffs: [4, 5],
    correctProductCoeff: 2,
    howToRu: 'P + O₂ → P₂O₅.',
    howToEn: 'Phosphorus burns to P₂O₅.',
    methodHint: 'both',
    gradeHint: 7,
  },
  {
    id: 'co-o2-co2',
    titleRu: '2CO + O₂ → 2CO₂',
    titleEn: '2CO + O₂ → 2CO₂',
    kind: 'practice_only',
    reactionClass: 'combustion',
    productId: 'co2',
    left: [{ z: 6, coeff: 1 }],
    correctLeftCoeffs: [2],
    correctProductCoeff: 2,
    displayEquationRu: '2CO + O₂ → 2CO₂',
    displayEquationEn: '2CO + O₂ → 2CO₂',
    howToRu: 'CO (молекула) + O₂ → CO₂. Для синтеза CO₂ из элементов: C + O₂.',
    howToEn: 'CO burns to CO₂. Element route: C + O₂ → CO₂.',
    methodHint: 'substitution',
    gradeHint: 8,
  },
  {
    id: 'zn-o2-zno',
    titleRu: '2Zn + O₂ → 2ZnO',
    titleEn: '2Zn + O₂ → 2ZnO',
    kind: 'synthesis',
    reactionClass: 'combustion',
    productId: 'zno',
    left: [
      { z: 30, coeff: 1 },
      { z: 8, coeff: 1, diatomic: true },
    ],
    correctLeftCoeffs: [2, 1],
    correctProductCoeff: 2,
    howToRu: 'Zn + O₂ → ZnO.',
    howToEn: 'Zinc burns to zinc oxide.',
    methodHint: 'substitution',
    gradeHint: 8,
  },
  {
    id: 'li-o2-li2o',
    titleRu: '4Li + O₂ → 2Li₂O',
    titleEn: '4Li + O₂ → 2Li₂O',
    kind: 'synthesis',
    reactionClass: 'combination',
    productId: 'li2o',
    left: [
      { z: 3, coeff: 1 },
      { z: 8, coeff: 1, diatomic: true },
    ],
    correctLeftCoeffs: [4, 1],
    correctProductCoeff: 2,
    howToRu: 'Li + O₂ → Li₂O.',
    howToEn: 'Lithium burns to Li₂O.',
    methodHint: 'both',
    gradeHint: 7,
  },
  {
    id: 'k-cl-kcl',
    titleRu: '2K + Cl₂ → 2KCl',
    titleEn: '2K + Cl₂ → 2KCl',
    kind: 'synthesis',
    reactionClass: 'combination',
    productId: 'salt_k_cl',
    left: [
      { z: 19, coeff: 1 },
      { z: 17, coeff: 1, diatomic: true },
    ],
    correctLeftCoeffs: [2, 1],
    correctProductCoeff: 2,
    howToRu: 'K + Cl₂ → KCl.',
    howToEn: 'Potassium + chlorine → KCl.',
    methodHint: 'substitution',
    gradeHint: 7,
  },
  {
    id: 'mg-cl2-mgcl2',
    titleRu: 'Mg + Cl₂ → MgCl₂',
    titleEn: 'Mg + Cl₂ → MgCl₂',
    kind: 'synthesis',
    reactionClass: 'combination',
    productId: 'salt_mg_cl',
    left: [
      { z: 12, coeff: 1 },
      { z: 17, coeff: 1, diatomic: true },
    ],
    correctLeftCoeffs: [1, 1],
    correctProductCoeff: 1,
    howToRu: 'Mg + Cl₂ → MgCl₂.',
    howToEn: 'Magnesium + chlorine → MgCl₂.',
    methodHint: 'substitution',
    gradeHint: 8,
  },
  {
    id: 'zn-cl2-zncl2',
    titleRu: 'Zn + Cl₂ → ZnCl₂',
    titleEn: 'Zn + Cl₂ → ZnCl₂',
    kind: 'synthesis',
    reactionClass: 'combination',
    productId: 'salt_zn_cl',
    left: [
      { z: 30, coeff: 1 },
      { z: 17, coeff: 1, diatomic: true },
    ],
    correctLeftCoeffs: [1, 1],
    correctProductCoeff: 1,
    howToRu: 'Zn + Cl₂ → ZnCl₂.',
    howToEn: 'Zinc + chlorine → ZnCl₂.',
    methodHint: 'substitution',
    gradeHint: 8,
  },
  {
    id: 'ca-cl2-cacl2',
    titleRu: 'Ca + Cl₂ → CaCl₂',
    titleEn: 'Ca + Cl₂ → CaCl₂',
    kind: 'synthesis',
    reactionClass: 'combination',
    productId: 'salt_ca_cl',
    left: [
      { z: 20, coeff: 1 },
      { z: 17, coeff: 1, diatomic: true },
    ],
    correctLeftCoeffs: [1, 1],
    correctProductCoeff: 1,
    howToRu: 'Ca + Cl₂ → CaCl₂.',
    howToEn: 'Calcium + chlorine → CaCl₂.',
    methodHint: 'substitution',
    gradeHint: 8,
  },
  {
    id: 'h2-br2-hbr',
    titleRu: 'H₂ + Br₂ → 2HBr',
    titleEn: 'H₂ + Br₂ → 2HBr',
    kind: 'synthesis',
    reactionClass: 'combination',
    productId: 'hbr',
    left: [
      { z: 1, coeff: 1, diatomic: true },
      { z: 35, coeff: 1, diatomic: true },
    ],
    correctLeftCoeffs: [1, 1],
    correctProductCoeff: 2,
    howToRu: 'H₂ + Br₂ → HBr.',
    howToEn: 'Hydrogen + bromine → HBr.',
    methodHint: 'substitution',
    gradeHint: 8,
  },
  {
    id: 'h2-i2-hi',
    titleRu: 'H₂ + I₂ ⇄ 2HI',
    titleEn: 'H₂ + I₂ ⇄ 2HI',
    kind: 'synthesis',
    reactionClass: 'combination',
    productId: 'hi',
    left: [
      { z: 1, coeff: 1, diatomic: true },
      { z: 53, coeff: 1, diatomic: true },
    ],
    correctLeftCoeffs: [1, 1],
    correctProductCoeff: 2,
    howToRu: 'H₂ + I₂ → HI (обратимая).',
    howToEn: 'Hydrogen + iodine → HI.',
    methodHint: 'substitution',
    gradeHint: 8,
  },
  {
    id: 'na-s-na2s',
    titleRu: '2Na + S → Na₂S',
    titleEn: '2Na + S → Na₂S',
    kind: 'synthesis',
    reactionClass: 'combination',
    productId: 'salt_na_s',
    left: [
      { z: 11, coeff: 1 },
      { z: 16, coeff: 1 },
    ],
    correctLeftCoeffs: [2, 1],
    correctProductCoeff: 1,
    howToRu: 'Na + S → Na₂S.',
    howToEn: 'Sodium + sulfur → Na₂S.',
    methodHint: 'substitution',
    gradeHint: 8,
  },
  {
    id: 'fe-o2-fe3o4',
    titleRu: '3Fe + 2O₂ → Fe₃O₄',
    titleEn: '3Fe + 2O₂ → Fe₃O₄',
    kind: 'synthesis',
    reactionClass: 'combustion',
    productId: 'fe3o4',
    left: [
      { z: 26, coeff: 1 },
      { z: 8, coeff: 1, diatomic: true },
    ],
    correctLeftCoeffs: [3, 2],
    correctProductCoeff: 1,
    howToRu: 'Fe + O₂ → Fe₃O₄ (магнетит).',
    howToEn: 'Iron burns to magnetite.',
    methodHint: 'both',
    gradeHint: 8,
  },
  {
    id: 'c-o2-co',
    titleRu: '2C + O₂ → 2CO',
    titleEn: '2C + O₂ → 2CO',
    kind: 'synthesis',
    reactionClass: 'combustion',
    productId: 'co',
    left: [
      { z: 6, coeff: 1 },
      { z: 8, coeff: 1, diatomic: true },
    ],
    correctLeftCoeffs: [2, 1],
    correctProductCoeff: 2,
    howToRu: 'Неполное горение: C → CO.',
    howToEn: 'Incomplete combustion to CO.',
    methodHint: 'substitution',
    gradeHint: 8,
  },
]

export function getBalanceLesson(id: string): BalanceLesson | undefined {
  return BALANCE_LESSON_BANK.find((l) => l.id === id)
}

export function lessonToLeftTerms(lesson: BalanceLesson, idPrefix = 'lesson'): ReactorEquationTerm[] {
  return lesson.left.map((t, i) => ({
    id: `${idPrefix}-${lesson.id}-${i}`,
    z: t.z,
    coeff: 1,
    diatomic: t.diatomic,
  }))
}

export function lessonsByReactionClass(reactionClass: ReactionClass): readonly BalanceLesson[] {
  return BALANCE_LESSON_BANK.filter((l) => l.reactionClass === reactionClass)
}
