/**
 * Перевод «уникального момента» (special) из таблицы docs/plans/formation200-rules.md на EN и UZ (латиница) для
 * «учителя» «Как образуется». Русский текст — в formationScripts.ts (генерируется из таблицы). При правке строки
 * таблицы — поправьте и перевод здесь (тест scripts/test-formation-teacher.mts проверяет, что перевод есть у всех 200).
 */
const T: Record<string, readonly [en: string, uz: string]> = {
  co2: ['C is excited (2s¹2p³: 4 unpaired e⁻); two C=O double bonds, linear; a non-polar molecule with polar bonds (the dipoles cancel).', 'C qoʻzgʻaladi (2s¹2p³: 4 ta juftlashmagan e⁻); ikkita C=O qoʻsh bogʻ, chiziqli; bogʻlar qutbli, molekula qutbsiz (dipollar bir-birini yoʻqotadi).'],
  hcl: ['H 1s¹ + Cl 3p⁵: one shared pair shifted towards Cl (δ+ H, δ− Cl); H₂ + Cl₂ — both molecules break, 1 e⁻ from each atom.', 'H 1s¹ + Cl 3p⁵: Cl tomon siljigan bitta umumiy juft (δ+ H, δ− Cl); H₂ + Cl₂ — ikkala molekula uziladi, har bir atomdan 1 tadan e⁻.'],
  h2o: ['O 2s²2p⁴ has two unpaired e⁻; two shared pairs with H; angle 104.5°; two lone pairs on O; the pairs are shifted towards O (δ−).', 'O 2s²2p⁴ — ikkita juftlashmagan e⁻; H bilan ikkita umumiy juft; burchak 104,5°; O da ikkita taqsimlanmagan juft; juftlar O tomon siljigan (δ−).'],
  h2so4: ['S is excited to 6 unpaired e⁻; two S=O and two S–O–H; a tetrahedron; made from SO₃ + H₂O: the water molecule adds to SO₃ (pair of the water O → S).', 'S 6 ta juftlashmagan e⁻ gacha qoʻzgʻaladi; ikkita S=O va ikkita S–O–H; tetraedr; SO₃ + H₂O dan olinadi: suv molekulasi SO₃ ga birikadi (suv O ining jufti → S).'],
  so2: ['Bent, 119°; in the school formula O=S=O both bonds are double (S excited: 4 unpaired e⁻, valency IV); a lone pair on S; another model has one S=O and one donor–acceptor S→O.', 'Burchakli, 119°; maktab yozuvida O=S=O — ikkala bogʻ qoʻsh (S qoʻzgʻalgan: 4 ta juftlashmagan e⁻, valentlik IV); S da taqsimlanmagan juft; boshqa modelda — bitta S=O va bitta donor-akseptor S→O.'],
  nacl: ['THE MODEL CASE: Na 3s¹ gives 1 e⁻ → Cl 3s²3p⁵ accepts it; the § 16 scheme; the lattice grows from one ion pair to 3×3×3; fig. 13 (6 neighbours).', 'NAMUNA: Na 3s¹ 1 e⁻ beradi → Cl 3s²3p⁵ qabul qiladi; 16-§ sxemasi; panjara bitta ion juftidan 3×3×3 gacha oʻsadi; 13-rasm (6 ta qoʻshni).'],
  co: ['C≡O: two ordinary shared pairs + one donor–acceptor pair (O → C); school formula C≡O.', 'C≡O: ikkita oddiy umumiy juft + bitta donor-akseptor juft (O → C); maktab yozuvi C≡O.'],
  salt_ca_co3: ['CaO + CO₂: the O²⁻ ion (lone pair) joins the C of CO₂ → CO₃²⁻ (donor–acceptor), Ca²⁺ stays; the calcite lattice.', 'CaO + CO₂: O²⁻ ioni (taqsimlanmagan jufti bilan) CO₂ ning C atomiga birikadi → CO₃²⁻ (donor-akseptor), Ca²⁺ qoladi; kalsit panjarasi.'],
  tb_cl2: ['p–p overlap along the axis (σ); 3 lone pairs on each Cl.', 'p–p qoplanish oʻq boʻylab (σ); har bir Cl da 3 ta taqsimlanmagan juft.'],
  tb_o2: ['O: 2p⁴, two unpaired e⁻ → double bond O=O (one σ + one π: the p clouds overlap sideways).', 'O: 2p⁴, ikkita juftlashmagan e⁻ → qoʻsh bogʻ O=O (bitta σ + bitta π: p-bulutlar yon tomondan qoplanadi).'],
  ca_oh_2: ['CaO + H₂O (slaking lime): O²⁻ + H₂O → 2 OH⁻, exothermic — steam is given off.', 'CaO + H₂O (ohakni soʻndirish): O²⁻ + H₂O → 2 OH⁻, ekzotermik — bugʻ chiqadi.'],
  tb_h2: ['s–s overlap, one shared pair; the simplest bond.', 's–s qoplanish, bitta umumiy juft; eng oddiy bogʻ.'],
  hno3: ['Trigonal planar; one N=O, one N–OH, one donor–acceptor N→O (N cannot have valency five — said honestly, as in the school formula H–O–N(=O)→O).', 'Yassi uchburchak; bitta N=O, bitta N–OH, bitta donor-akseptor N→O (N besh valentli boʻla olmaydi — maktab yozuvidagidek H–O–N(=O)→O).'],
  naoh: ['Na₂O + H₂O: the oxide ion O²⁻ takes H⁺ from water → 2 OH⁻ (proton transfer!), Na⁺ stays; a Na⁺/OH⁻ lattice.', 'Na₂O + H₂O: oksid-ion O²⁻ suvdan H⁺ ni oladi → 2 OH⁻ (proton oʻtishi!), Na⁺ qoladi; Na⁺/OH⁻ panjarasi.'],
  h2s: ['Bent, 92°; weakly polar bonds; H₂ + S on heating.', 'Burchakli, 92°; kuchsiz qutbli bogʻlar; H₂ + S qizdirilganda.'],
  salt_cu_so4: ['Cu(OH)₂ + H₂SO₄: H⁺ + OH⁻ → H₂O; Cu²⁺ and SO₄²⁻ remain; anhydrous CuSO₄ is white.', 'Cu(OH)₂ + H₂SO₄: H⁺ + OH⁻ → H₂O; Cu²⁺ va SO₄²⁻ qoladi; suvsiz CuSO₄ — oq.'],
  nh3: ['N 2s²2p³: three shared pairs with H + one lone pair (it will be needed for NH₄⁺); a pyramid, 107°.', 'N 2s²2p³: H bilan uchta umumiy juft + bitta taqsimlanmagan juft (NH₄⁺ uchun kerak boʻladi); piramida, 107°.'],
  koh: ['Like NaOH; route 2K + 2H₂O: K gives e⁻ to water → H₂↑ and OH⁻.', 'NaOH kabi; yoʻli 2K + 2H₂O: K suvga e⁻ beradi → H₂↑ va OH⁻.'],
  salt_na_so4: ['Neutralisation 2NaOH + H₂SO₄: 2 H⁺ + 2 OH⁻ → 2 H₂O; Na⁺ and SO₄²⁻ remain and crystallise on evaporation.', 'Neytrallanish 2NaOH + H₂SO₄: 2 H⁺ + 2 OH⁻ → 2 H₂O; Na⁺ va SO₄²⁻ qoladi, bugʻlatilganda kristallanadi.'],
  tb_n2: ['N: 2p³ → triple bond N≡N (σ + 2π), very strong — this explains why nitrogen is unreactive.', 'N: 2p³ → uchlamchi bogʻ N≡N (σ + 2π), juda mustahkam — azotning inertligi shundan.'],
  salt_k_cl: ['2K + Cl₂ — just like NaCl.', '2K + Cl₂ — NaCl kabi.'],
  tb_s8: ['Crown-shaped S₈ ring: each S has two single bonds; a molecular lattice.', 'S₈ toj-halqasi: har bir S da ikkita oddiy bogʻ; molekulyar panjara.'],
  cuo: ['2Cu + O₂ (heating): Cu gives 2 e⁻; the tenorite lattice (black).', '2Cu + O₂ (qizdirish): Cu 2 e⁻ beradi; tenorit panjarasi (qora).'],
  cu_oh_2: ['EXCHANGE in solution: Cu²⁺ (blue, hydrated) meets OH⁻ → precipitate; ions in water, not simple substances.', 'Eritmada ALMASHINISH: Cu²⁺ (koʻk, gidratlangan) OH⁻ bilan uchrashadi → choʻkma; oddiy moddalar emas, suvdagi ionlar.'],
  salt_na_co3: ['2NaOH + CO₂: CO₂ takes O²⁻ from two OH⁻ → CO₃²⁻ + H₂O; Na⁺ and CO₃²⁻ remain; crystallisation on evaporation.', '2NaOH + CO₂: CO₂ ikki OH⁻ dan O²⁻ oladi → CO₃²⁻ + H₂O; Na⁺ va CO₃²⁻ qoladi; bugʻlatilganda kristallanadi.'],
  cao: ['Roasting CaCO₃: CO₃²⁻ breaks into O²⁻ + CO₂ — the lattice rebuilds; from the elements 2Ca + O₂ is also correct.', 'CaCO₃ ni kuydirish: CO₃²⁻ O²⁻ + CO₂ ga parchalanadi — panjara qayta quriladi; elementlardan 2Ca + O₂ ham toʻgʻri.'],
  sio2: ['NOT ionic and NOT a molecule! Si (4 valence e⁻) forms 4 polar covalent Si–O bonds; each O bridges two Si; SiO₄ tetrahedra share corners into a framework (quartz). SiO₂ is the simplest formula; an atomic lattice (§ 17).', 'Ion ham, molekula ham EMAS! Si (4 valent e⁻) 4 ta kovalent qutbli Si–O bogʻ hosil qiladi; har bir O — ikki Si orasida koʻprik; SiO₄ tetraedrlari uchlari bilan karkasga birlashadi (kvars). SiO₂ — eng oddiy formula; atom panjara (17-§).'],
  no: ['An odd electron (radical): 11 valence e⁻ — said honestly; bond order “2.5”, school formula N=O; that is why it is easily oxidised to NO₂.', 'Toq elektron (radikal): 11 ta valent e⁻ — rostini aytamiz; bogʻ karraligi «2,5», maktab yozuvi N=O; shuning uchun NO₂ gacha oson oksidlanadi.'],
  no2: ['A radical (odd e⁻ on N); bent, 134°; dimerises to N₂O₄ in the cold.', 'Radikal (N da toq e⁻); burchakli, 134°; sovuqda N₂O₄ ga dimerlanadi.'],
  salt_k_so4: ['Neutralisation.', 'Neytrallanish.'],
  salt_ba_so4: ['EXCHANGE in solution: Ba²⁺ + SO₄²⁻ → BaSO₄↓ (barite lattice) — the same chemistry as in the BaSO₄ school scene.', 'Eritmada ALMASHINISH: Ba²⁺ + SO₄²⁻ → BaSO₄↓ (barit panjarasi) — BaSO₄ maktab sahnasidagi kimyoning oʻzi.'],
  tb_i2: ['Like Cl₂; the solid has a MOLECULAR lattice (I₂ molecules at the lattice points, § 17): the packing of molecules is shown.', 'Cl₂ kabi; qattiq holda — MOLEKULYAR panjara (tugunlarda I₂ molekulalari, 17-§): molekulalar joylashuvi koʻrsatiladi.'],
  salt_ca_cl: ['Ca + Cl₂; also made by drying out solutions.', 'Ca + Cl₂; eritmalarni suvsizlantirib ham olinadi.'],
  al2o3: ['4Al + 3O₂: each Al gives 3 e⁻, each O takes 2 — 12 e⁻ for 2 formula units; the corundum lattice.', '4Al + 3O₂: har bir Al 3 e⁻ beradi, har bir O 2 e⁻ oladi — 2 formula birligiga 12 e⁻; korund panjarasi.'],
  salt_k_mno4: ['Mn⁺⁷ in an O tetrahedron; made by oxidising K₂MnO₄ with chlorine — the MnO₄²⁻ ion loses 1 e⁻ (green → violet).', 'Mn⁺⁷ O tetraedrida; K₂MnO₄ ni xlor bilan oksidlab olinadi — MnO₄²⁻ ioni 1 e⁻ yoʻqotadi (yashil → binafsha).'],
  tb_br2: ['Like Cl₂; a liquid — molecules are closer, attraction between molecules.', 'Cl₂ kabi; suyuqlik — molekulalar yaqinroq, molekulalararo tortishish.'],
  salt_na_no3: ['Neutralisation NaOH + HNO₃.', 'Neytrallanish NaOH + HNO₃.'],
  salt_fe3_cl: ['2Fe + 3Cl₂: chlorine is a strong oxidiser, Fe gives 3 e⁻ (with HCl only 2 → FeCl₂: note the difference).', '2Fe + 3Cl₂: xlor kuchli oksidlovchi, Fe 3 e⁻ beradi (HCl bilan faqat 2 → FeCl₂: farqiga e’tibor bering).'],
  h3po4: ['P is excited (5 unpaired); one P=O, three P–O–H; a tetrahedron; P₂O₅ + 3H₂O — water adds to P=O / P–O–P.', 'P qoʻzgʻaladi (5 ta juftlashmagan); bitta P=O, uchta P–O–H; tetraedr; P₂O₅ + 3H₂O — suv P=O / P–O–P ga birikadi.'],
  mno2: ['From KMnO₄ on heating (Mn⁺⁷ → Mn⁺⁴, accepts 3 e⁻); the rutile lattice 6:3.', 'KMnO₄ qizdirilganda (Mn⁺⁷ → Mn⁺⁴, 3 e⁻ qabul qiladi); rutil panjarasi 6:3.'],
  p2o5: ['Real P₄O₁₀ molecules: 4 P in a tetrahedron, 6 bridging O and 4 terminal P=O; built from P₄ (P–P bonds break, O inserts) and O₂.', 'Haqiqiy P₄O₁₀ molekulalari: tetraedrda 4 ta P, 6 ta koʻprik O va 4 ta chetki P=O; P₄ (P–P uziladi, O kiradi) va O₂ dan yigʻiladi.'],
  fe2o3: ['From the elements (scale/rust) or 2Fe(OH)₃ → Fe₂O₃ + 3H₂O: water splits off from OH⁻.', 'Elementlardan (kuyindi/zang) yoki 2Fe(OH)₃ → Fe₂O₃ + 3H₂O: OH⁻ dan suv ajraladi.'],
  tb_p4: ['P₄ tetrahedron: each P bonded to three; angles 60° (strain → white phosphorus is very reactive).', 'P₄ tetraedri: har bir P uchtasi bilan bogʻlangan; burchaklar 60° (kuchlanish → oq fosfor juda faol).'],
  al_oh_3: ['Exchange Al³⁺ + 3OH⁻; amphoteric.', 'Almashinish Al³⁺ + 3OH⁻; amfoter.'],
  salt_ag_no3: ['Ag + 2HNO₃ (conc.): Ag gives 1 e⁻ to N⁺⁵ → NO₂ (brown gas).', 'Ag + 2HNO₃ (kons.): Ag N⁺⁵ ga 1 e⁻ beradi → NO₂ (qoʻngʻir gaz).'],
  salt_k_no3: ['Neutralisation (saltpetre).', 'Neytrallanish (selitra).'],
  salt_zn_cl: ['Zn + Cl₂ or ZnO + 2HCl (O²⁻ + 2H⁺ → H₂O).', 'Zn + Cl₂ yoki ZnO + 2HCl (O²⁻ + 2H⁺ → H₂O).'],
  so3: ['Trigonal planar, three S=O; S has 6 unpaired e⁻ (excited); made by 2SO₂ + O₂ on a V₂O₅ catalyst.', 'Yassi uchburchak, uchta S=O; S da 6 ta juftlashmagan e⁻ (qoʻzgʻalgan); 2SO₂ + O₂ dan V₂O₅ katalizatorida olinadi.'],
  zno: ['From the elements or by decomposing Zn(NO₃)₂.', 'Elementlardan yoki Zn(NO₃)₂ ni parchalab.'],
  salt_fe2_so4: ['Fe + H₂SO₄ (dilute): Fe gives 2 e⁻ → H₂.', 'Fe + H₂SO₄ (suyultirilgan): Fe 2 e⁻ beradi → H₂.'],
  salt_al_cl: ['2Al + 3Cl₂: Al gives 3 e⁻; the solid is a layered lattice, the vapour contains Al₂Cl₆ molecules (said honestly).', '2Al + 3Cl₂: Al 3 e⁻ beradi; qattiq holda — qatlamli panjara, bugʻda — Al₂Cl₆ molekulalari (rostini aytamiz).'],
  salt_nahco3: ['NaOH + CO₂: OH⁻ joins the C of CO₂ → HCO₃⁻ (H stays covalently on O).', 'NaOH + CO₂: OH⁻ CO₂ ning C atomiga birikadi → HCO₃⁻ (H O da kovalent qoladi).'],
  fe_oh_3: ['Exchange Fe³⁺ + 3OH⁻ → brown precipitate; in the reaction catalogue — rusting 4Fe + 6H₂O + 3O₂.', 'Almashinish Fe³⁺ + 3OH⁻ → qoʻngʻir choʻkma; reaksiyalar katalogida — zanglash 4Fe + 6H₂O + 3O₂.'],
  h2co3: ['Unstable: CO₂ + H₂O ⇄ H₂CO₃ — water adds to C=O; one C=O, two C–O–H.', 'Beqaror: CO₂ + H₂O ⇄ H₂CO₃ — suv C=O ga birikadi; bitta C=O, ikkita C–O–H.'],
  salt_nh4_cl: ['NH₃ + HCl: H⁺ moves from HCl to the lone pair of N (donor–acceptor) → NH₄⁺ and Cl⁻, then an ionic lattice (CsCl type, 8:8).', 'NH₃ + HCl: H⁺ HCl dan N ning taqsimlanmagan juftiga oʻtadi (donor-akseptor) → NH₄⁺ va Cl⁻, keyin ion panjara (CsCl tipi, 8:8).'],
  h2so3: ['SO₂ + H₂O ⇄: unstable; a pyramid, one S=O, two S–O–H, a lone pair on S.', 'SO₂ + H₂O ⇄: beqaror; piramida, bitta S=O, ikkita S–O–H, S da taqsimlanmagan juft.'],
  salt_al_so4: ['Neutralisation Al(OH)₃ + H₂SO₄.', 'Neytrallanish Al(OH)₃ + H₂SO₄.'],
  mgo: ['2Mg + O₂ (a flash): Mg gives 2 e⁻; NaCl-type lattice.', '2Mg + O₂ (chaqnash): Mg 2 e⁻ beradi; NaCl tipidagi panjara.'],
  salt_cu_cl: ['Cu + Cl₂ (copper burning in chlorine).', 'Cu + Cl₂ (mis xlorda yonadi).'],
  hbr: ['Like HCl, less polar.', 'HCl kabi, qutbliligi kamroq.'],
  h2o2: ['H–O–O–H: the O–O bond is non-polar (the pair is in the middle), O–H bonds are polar; the molecule is not flat (an “open book”).', 'H–O–O–H: O–O bogʻi qutbsiz (juft oʻrtada), O–H bogʻlari qutbli; molekula yassi emas («ochiq kitob»).'],
  salt_ba_cl: ['Ba + Cl₂.', 'Ba + Cl₂.'],
  tb_ca3po42: ['Neutralisation H₃PO₄ + Ca(OH)₂; phosphorite/apatite.', 'Neytrallanish H₃PO₄ + Ca(OH)₂; fosforit/apatit.'],
  salt_ag_cl: ['Exchange Ag⁺ + Cl⁻ → white curdy precipitate; at school it is not made from the elements Ag + Cl₂.', 'Almashinish Ag⁺ + Cl⁻ → oq ivisimon choʻkma; maktabda elementlardan Ag + Cl₂ olinmaydi.'],
  tb_f2: ['Like Cl₂, but the bond is weaker (the lone pairs repel) — one sentence.', 'Cl₂ kabi, lekin bogʻ kuchsizroq (taqsimlanmagan juftlar itarishadi).'],
  salt_k_co3: ['2KOH + CO₂.', '2KOH + CO₂.'],
  fe3o4: ['Magnetite = FeO·Fe₂O₃: Fe²⁺ and Fe³⁺ in one lattice (spinel) — two kinds of cations labelled +2/+3.', 'Magnetit = FeO·Fe₂O₃: Fe²⁺ va Fe³⁺ bitta panjarada (shpinel) — +2/+3 belgili ikki xil kation.'],
  hi: ['Like HCl, almost non-polar; reversible (H₂ + I₂ ⇄ 2HI).', 'HCl kabi, deyarli qutbsiz; qaytar (H₂ + I₂ ⇄ 2HI).'],
  salt_k_clo3: ['Cl₂ + 6KOH (hot): 5 Cl → Cl⁻, 1 Cl → ClO₃⁻ (+5); Berthollet’s salt.', 'Cl₂ + 6KOH (qizdirib): 5 Cl → Cl⁻, 1 Cl → ClO₃⁻ (+5); bertolle tuzi.'],
  salt_nh4_no3: ['NH₃ + HNO₃: H⁺ moves to N; two polyatomic ions.', 'NH₃ + HNO₃: H⁺ N ga oʻtadi; ikki koʻp atomli ion.'],
  salt_k2cr2o7: ['Two CrO₄ tetrahedra through a bridging O; from CrO₄²⁻ in acid: 2CrO₄²⁻ + 2H⁺ → Cr₂O₇²⁻ + H₂O (yellow → orange).', 'Koʻprik O orqali ikkita CrO₄ tetraedri; kislotali muhitda CrO₄²⁻ dan: 2CrO₄²⁻ + 2H⁺ → Cr₂O₇²⁻ + H₂O (sariq → toʻq sariq).'],
  salt_fe2_cl: ['Fe + 2HCl: Fe⁰ gives 2 e⁻ to two H⁺ → H₂ (chlorine would give FeCl₃); or FeCl₃ + Fe.', 'Fe + 2HCl: Fe⁰ ikkita H⁺ ga 2 e⁻ beradi → H₂ (xlor FeCl₃ beradi); yoki FeCl₃ + Fe.'],
  zn_oh_2: ['Exchange Zn²⁺ + 2OH⁻; amphoteric — link to Na₂[Zn(OH)₄].', 'Almashinish Zn²⁺ + 2OH⁻; amfoter — Na₂[Zn(OH)₄] bilan bogʻliq.'],
  fe_oh_2: ['Exchange Fe²⁺ + 2OH⁻; a greenish precipitate that turns brown in air.', 'Almashinish Fe²⁺ + 2OH⁻; yashilroq choʻkma, havoda qoʻngʻirlashadi.'],
  salt_mg_cl: ['Mg + Cl₂; a layered lattice.', 'Mg + Cl₂; qatlamli panjara.'],
  salt_zn_so4: ['ZnO + H₂SO₄: O²⁻ + 2H⁺ → H₂O.', 'ZnO + H₂SO₄: O²⁻ + 2H⁺ → H₂O.'],
  salt_k_i: ['2K + I₂.', '2K + I₂.'],
  salt_fe2_s: ['Fe + S (the classic experiment with a magnet): Fe gives 2 e⁻; the troilite lattice.', 'Fe + S (magnit bilan klassik tajriba): Fe 2 e⁻ beradi; troilit panjarasi.'],
  tb_o3: ['Bent, 117°; one O=O and one donor–acceptor O→O; from O₂: 3O₂ → 2O₃ (one O=O breaks under UV light or a discharge).', 'Burchakli, 117°; bitta O=O va bitta donor-akseptor O→O; O₂ dan: 3O₂ → 2O₃ (UB nur yoki razryadda bitta O=O uziladi).'],
  hf: ['The most polar H–F bond; HYDROGEN bonds between molecules (chains).', 'Eng qutbli H–F bogʻi; molekulalar orasida VODOROD bogʻlar (zanjirlar).'],
  salt_ca_hco3_2: ['CaCO₃ + CO₂ + H₂O: CO₃²⁻ + H₂O + CO₂ → 2 HCO₃⁻ — limestone dissolves (karst).', 'CaCO₃ + CO₂ + H₂O: CO₃²⁻ + H₂O + CO₂ → 2 HCO₃⁻ — ohaktosh eriydi (karst).'],
  cu2o: ['Cu⁺¹ — one e⁻ from each Cu; from CuO at 1100 °C (O is lost); red.', 'Cu⁺¹ — har bir Cu dan bitta e⁻; CuO dan 1100 °C da (O ajraladi); qizil.'],
  ba_oh_2: ['Ba + 2H₂O: 2 e⁻ → 2 H⁺ → H₂; Ba²⁺ and 2 OH⁻ remain.', 'Ba + 2H₂O: 2 e⁻ → 2 H⁺ → H₂; Ba²⁺ va 2 OH⁻ qoladi.'],
  salt_ca_so4: ['Neutralisation; slightly soluble — it precipitates.', 'Neytrallanish; kam eriydi — choʻkmaga tushadi.'],
  salt_nh4_so4: ['2NH₃ + H₂SO₄: two H⁺ transfers.', '2NH₃ + H₂SO₄: ikki marta H⁺ oʻtadi.'],
  salt_na_br: ['NaOH + HBr or 2Na + Br₂.', 'NaOH + HBr yoki 2Na + Br₂.'],
  mg_oh_2: ['Exchange in solution: Mg²⁺ + 2OH⁻ → white precipitate; Mg + 2H₂O goes only in hot water.', 'Eritmada almashinish: Mg²⁺ + 2OH⁻ → oq choʻkma; Mg + 2H₂O faqat issiq suvda boradi.'],
  salt_mg_so4: ['Mg + H₂SO₄: Mg gives 2 e⁻ to two H⁺ → H₂; Mg²⁺ and SO₄²⁻ remain.', 'Mg + H₂SO₄: Mg ikkita H⁺ ga 2 e⁻ beradi → H₂; Mg²⁺ va SO₄²⁻ qoladi.'],
  tb_cah2: ['Ca + H₂: the HYDRIDE ion H⁻ — hydrogen ACCEPTS e⁻ (like a halogen); a Ca²⁺/H⁻ lattice.', 'Ca + H₂: GIDRID-ion H⁻ — vodorod e⁻ ni QABUL QILADI (galogen kabi); Ca²⁺/H⁻ panjarasi.'],
  hno2: ['H–O–N=O, bent; unstable.', 'H–O–N=O, burchakli; beqaror.'],
  tb_cac2: ['CaO + 3C (electric arc): C₂²⁻ is [C≡C]²⁻ — a triple bond + 2 e⁻ from Ca; a NaCl-like lattice with C₂ “dumbbells”.', 'CaO + 3C (yoy): C₂²⁻ — [C≡C]²⁻: uchlamchi bogʻ + Ca dan 2 e⁻; C₂ «gantellari» bilan NaCl ga oʻxshash panjara.'],
  salt_na_sio3: ['Chain anion (SiO₃²⁻)ₙ, Na⁺ between the chains; made from SiO₂ + 2NaOH (fusion): the quartz framework breaks up.', 'Zanjirsimon anion (SiO₃²⁻)ₙ, zanjirlar orasida Na⁺; SiO₂ + 2NaOH dan (suyuqlantirib): kvars karkasi buziladi.'],
  salt_fe3_so4: ['Neutralisation Fe(OH)₃ + H₂SO₄: H⁺ + OH⁻ → H₂O; Fe³⁺ and SO₄²⁻ remain.', 'Neytrallanish Fe(OH)₃ + H₂SO₄: H⁺ + OH⁻ → H₂O; Fe³⁺ va SO₄²⁻ qoladi.'],
  tb_na3po4: ['Neutralisation in 3 steps: three H⁺ in turn.', '3 bosqichli neytrallanish: uchta H⁺ navbat bilan.'],
  h2sio3: ['A POLYMER xSiO₂·yH₂O: chains of SiO₄ tetrahedra with OH groups; a gel; precipitated by Na₂SiO₃ + 2HCl: H⁺ joins SiO₃²⁻.', 'POLIMER xSiO₂·yH₂O: OH guruhli SiO₄ tetraedrlari zanjirlari; ivitma; Na₂SiO₃ + 2HCl bilan choʻktiriladi: H⁺ SiO₃²⁻ ga birikadi.'],
  n2o5: ['O₂N–O–NO₂: two NO₂ triangles through a bridging O; in the crystal it is NO₂⁺NO₃⁻ (said honestly).', 'O₂N–O–NO₂: koʻprik O orqali ikki NO₂ uchburchagi; kristallda — NO₂⁺NO₃⁻ (rostini aytamiz).'],
  salt_ca_no3: ['CaCO₃ + 2HNO₃: CO₃²⁻ + 2H⁺ → H₂O + CO₂↑.', 'CaCO₃ + 2HNO₃: CO₃²⁻ + 2H⁺ → H₂O + CO₂↑.'],
  salt_k_br: ['2K + Br₂.', '2K + Br₂.'],
  salt_na_so3: ['2NaOH + SO₂: OH⁻ joins S (pair O → S) → HSO₃⁻ → SO₃²⁻.', '2NaOH + SO₂: OH⁻ S ga birikadi (juft O → S) → HSO₃⁻ → SO₃²⁻.'],
  tb_nah: ['Na + ½H₂ → Na⁺H⁻ (hydrogen accepts an e⁻).', 'Na + ½H₂ → Na⁺H⁻ (vodorod e⁻ qabul qiladi).'],
  cr2o3: ['From the elements or the “volcano” (NH₄)₂Cr₂O₇: Cr⁺⁶ → Cr⁺³ accepts 3 e⁻ from N⁻³ → N₂.', 'Elementlardan yoki «vulqon» (NH₄)₂Cr₂O₇: Cr⁺⁶ → Cr⁺³ N⁻³ dan 3 e⁻ oladi → N₂.'],
  feo: ['Fe(OH)₂ → FeO + H₂O without air.', 'Fe(OH)₂ → FeO + H₂O havosiz.'],
  salt_na_s: ['2Na + S (heating): S accepts 2 e⁻ from two Na; antifluorite.', '2Na + S (qizdirish): S ikki Na dan 2 e⁻ oladi; antiflyuorit.'],
  na2o: ['NOT made directly from the elements (burning gives Na₂O₂): Na₂O₂ + 2Na → 2Na₂O — the peroxide O–O bond is broken by two e⁻ from Na.', 'Oddiy moddalardan bevosita OLINMAYDI (yonishda Na₂O₂ hosil boʻladi): Na₂O₂ + 2Na → 2Na₂O — peroksid O–O bogʻi Na dan kelgan ikki e⁻ bilan uziladi.'],
  salt_cu_no3: ['CuO + 2HNO₃: O²⁻ + 2H⁺ → H₂O.', 'CuO + 2HNO₃: O²⁻ + 2H⁺ → H₂O.'],
  salt_mn_so4: ['MnO + H₂SO₄: O²⁻ + 2H⁺ → H₂O; Mn²⁺ and SO₄²⁻ remain (Mn²⁺ is also what MnO₄⁻ is reduced to).', 'MnO + H₂SO₄: O²⁻ + 2H⁺ → H₂O; Mn²⁺ va SO₄²⁻ qoladi (MnO₄⁻ ham Mn²⁺ gacha qaytariladi).'],
  fes2: ['Pyrite: Fe²⁺ and the DISULFIDE ion S₂²⁻ (single S–S + 2 e⁻) — not Fe⁴⁺!; a NaCl-like lattice with S₂ dumbbells.', 'Pirit: Fe²⁺ va DISULFID-ion S₂²⁻ (oddiy S–S + 2 e⁻) — Fe⁴⁺ emas!; S₂ gantellari bilan NaCl ga oʻxshash panjara.'],
  k2o: ['Like Na₂O (K₂O₂ + 2K).', 'Na₂O kabi (K₂O₂ + 2K).'],
  cro3: ['A POLYMER: chains of CrO₄ tetrahedra sharing corners, (CrO₃)ₙ; a chain of 3–4 units, Cr⁺⁶.', 'POLIMER: uchlari umumiy CrO₄ tetraedrlari zanjiri (CrO₃)ₙ; 3–4 boʻgʻinli zanjir, Cr⁺⁶.'],
  li2o: ['4Li + O₂ — the only alkali metal that burns to the oxide.', '4Li + O₂ — oksidgacha yonadigan yagona ishqoriy metall.'],
  tb_ph3: ['A pyramid, bonds almost non-polar (EN of P ≈ H); a lone pair; made by hydrolysis of Ca₃P₂.', 'Piramida, bogʻlar deyarli qutbsiz (P ning EM ≈ H); taqsimlanmagan juft; Ca₃P₂ gidrolizi bilan olinadi.'],
  tb_cuso4_5h2o: ['HYDRATION: 4 H₂O turn their O to Cu²⁺ (donor–acceptor), the fifth is held to SO₄²⁻ by a hydrogen bond; the colour becomes blue.', 'GIDRATLANISH: 4 ta H₂O O atomi bilan Cu²⁺ ga buriladi (donor-akseptor), beshinchisi SO₄²⁻ ga vodorod bogʻ bilan; rang koʻk boʻladi.'],
  tb_sih4: ['A tetrahedron, weakly polar Si–H bonds (H is δ−!) — the opposite polarity to CH₄.', 'Tetraedr, kuchsiz qutbli Si–H bogʻlari (H δ−!) — CH₄ ga nisbatan teskari qutblilik.'],
  n2o: ['Linear N≡N→O: a triple bond + a donor–acceptor bond; made by decomposing NH₄NO₃.', 'Chiziqli N≡N→O: uchlamchi bogʻ + donor-akseptor bogʻ; NH₄NO₃ ni parchalab olinadi.'],
  nh3_h2o: ['NH₃ + H₂O: a HYDROGEN bond (H of water → lone pair of N); partly NH₄⁺ + OH⁻ — an equilibrium.', 'NH₃ + H₂O: VODOROD bogʻ (suvning H i → N ning taqsimlanmagan jufti); qisman NH₄⁺ + OH⁻ — muvozanat.'],
  salt_na_clo2: ['Cl⁺³ in ClO₂⁻, bent.', 'ClO₂⁻ da Cl⁺³, burchakli.'],
  na2o2: ['2Na + O₂ (burning): O₂ accepts 2 e⁻, the O–O bond is KEPT (peroxide) — unlike Na₂O; a Na⁺/O₂²⁻ lattice.', '2Na + O₂ (yonish): O₂ 2 e⁻ oladi, O–O bogʻi SAQLANADI (peroksid) — Na₂O dan farqi; Na⁺/O₂²⁻ panjarasi.'],
  salt_cr_so4: ['Neutralisation Cr(OH)₃ + H₂SO₄: H⁺ + OH⁻ → H₂O; Cr³⁺ and SO₄²⁻ remain (Cr³⁺ is also the product of reducing Cr₂O₇²⁻).', 'Neytrallanish Cr(OH)₃ + H₂SO₄: H⁺ + OH⁻ → H₂O; Cr³⁺ va SO₄²⁻ qoladi (Cr³⁺ — Cr₂O₇²⁻ qaytarilishi mahsuloti ham).'],
  salt_pb_no3: ['PbO + 2HNO₃.', 'PbO + 2HNO₃.'],
  tb_cro: ['Cr(OH)₂ → CrO + H₂O (two OH⁻ → O²⁻ + H₂O — water splits off).', 'Cr(OH)₂ → CrO + H₂O (ikki OH⁻ → O²⁻ + H₂O — suv ajraladi).'],
  tb_croh2: ['Exchange Cr²⁺ + 2OH⁻.', 'Almashinish Cr²⁺ + 2OH⁻.'],
  salt_mn_cl: ['Mn + Cl₂, or in the lab 2KMnO₄ + 16HCl: Mn⁺⁷ accepts 5 e⁻ (given by Cl⁻ → Cl₂), Mn²⁺ remains.', 'Mn + Cl₂ yoki laboratoriyada 2KMnO₄ + 16HCl: Mn⁺⁷ 5 e⁻ oladi (ularni Cl⁻ beradi → Cl₂), Mn²⁺ qoladi.'],
  tb_nahso4: ['An acid salt: one H⁺ is neutralised, the second stays in HSO₄⁻.', 'Nordon tuz: bitta H⁺ neytrallangan, ikkinchisi HSO₄⁻ da qolgan.'],
  salt_al_no3: ['Al(OH)₃ + 3HNO₃.', 'Al(OH)₃ + 3HNO₃.'],
  hclo: ['Cl₂ + H₂O ⇄ HCl + HClO: disproportionation, H–O–Cl.', 'Cl₂ + H₂O ⇄ HCl + HClO: disproporsiyalanish, H–O–Cl.'],
  salt_mg_co3: ['Exchange Mg²⁺ + CO₃²⁻ → precipitate.', 'Almashinish Mg²⁺ + CO₃²⁻ → choʻkma.'],
  salt_na_i: ['2Na + I₂.', '2Na + I₂.'],
  salt_zn_s: ['Zn + S (a flash); sphalerite, a bond with a covalent share.', 'Zn + S (chaqnash); sfalerit, kovalent ulushli bogʻ.'],
  salt_cu_s: ['Cu + S or exchange Cu²⁺ + H₂S; black; high covalency; honestly: strong heating of Cu with S gives mostly Cu₂S, so CuS is usually precipitated from a copper salt solution by hydrogen sulfide.', 'Cu + S yoki almashinish Cu²⁺ + H₂S; qora; kovalentlik yuqori; rostini aytganda: Cu ni S bilan kuchli qizdirganda asosan Cu₂S hosil boʻladi, shuning uchun CuS odatda mis tuzi eritmasidan vodorod sulfid bilan choʻktiriladi.'],
  hclo4: ['H–O–ClO₃ tetrahedron, Cl⁺⁷ — the strongest acid.', 'H–O–ClO₃ tetraedri, Cl⁺⁷ — eng kuchli kislota.'],
  salt_al_s: ['2Al + 3S (fusion); completely hydrolysed by water.', '2Al + 3S (suyuqlantirib); suvda toʻliq gidrolizlanadi.'],
  salt_pb_s: ['Pb + S or exchange Pb²⁺ + S²⁻ (black, a test for H₂S).', 'Pb + S yoki almashinish Pb²⁺ + S²⁻ (qora, H₂S ga sifat reaksiyasi).'],
  lioh: ['Like KOH (Li + H₂O).', 'KOH kabi (Li + H₂O).'],
  tb_cuoh2co3: ['Malachite: a basic salt — Cu²⁺, OH⁻ and CO₃²⁻ in one lattice; three kinds of particles.', 'Malaxit: asosli tuz — Cu²⁺, OH⁻ va CO₃²⁻ bitta panjarada; uch xil zarracha.'],
  tb_k2mno4: ['Mn⁺⁶; a product of decomposing KMnO₄.', 'Mn⁺⁶; KMnO₄ parchalanishi mahsuloti.'],
  tb_cl2o7: ['O₃Cl–O–ClO₃: two tetrahedra through a bridge, Cl⁺⁷; the anhydride of HClO₄ (2HClO₄ − H₂O).', 'O₃Cl–O–ClO₃: koʻprik orqali ikki tetraedr, Cl⁺⁷; HClO₄ angidridi (2HClO₄ − H₂O).'],
  tb_crcl2: ['Cr + 2HCl: Cr gives 2 e⁻ to two H⁺ → H₂.', 'Cr + 2HCl: Cr ikki H⁺ ga 2 e⁻ beradi → H₂.'],
  tb_mn2o7: ['O₃Mn–O–MnO₃, Mn⁺⁷ — a molecular oxide (a liquid), not ionic: unlike MnO/MnO₂.', 'O₃Mn–O–MnO₃, Mn⁺⁷ — molekulyar oksid (suyuqlik), ion emas: MnO/MnO₂ dan farqi.'],
  bao: ['Like CaO (from BaCO₃).', 'CaO kabi (BaCO₃ dan).'],
  salt_ba_no3: ['Like Ca(NO₃)₂.', 'Ca(NO₃)₂ kabi.'],
  salt_zn_no3: ['Zn + dilute HNO₃: Zn gives 2 e⁻, N⁺⁵ → N⁺² (NO), not H₂!', 'Zn + suyultirilgan HNO₃: Zn 2 e⁻ beradi, N⁺⁵ → N⁺² (NO), H₂ emas!'],
  tb_mn3o4: ['MnO·Mn₂O₃: Mn²⁺ and Mn³⁺.', 'MnO·Mn₂O₃: Mn²⁺ va Mn³⁺.'],
  tb_croh3: ['Exchange Cr³⁺ + 3OH⁻.', 'Almashinish Cr³⁺ + 3OH⁻.'],
  tb_v2o5: ['A layered polymer of VO₅ pyramids; a fragment of a layer; the catalyst for SO₃.', 'VO₅ piramidalaridan qatlamli polimer; qatlam boʻlagi; SO₃ uchun katalizator.'],
  tb_cs2: ['S=C=S, linear, like CO₂; almost non-polar bonds.', 'S=C=S, chiziqli, CO₂ kabi; deyarli qutbsiz bogʻlar.'],
  pbo: ['2Pb + O₂; litharge (layers).', '2Pb + O₂; glyot (qatlamlar).'],
  tb_k2o2: ['Like Na₂O₂.', 'Na₂O₂ kabi.'],
  salt_k_s: ['2K + S.', '2K + S.'],
  tb_aucl3: ['2Au + 3Cl₂ (heating); the crystal consists of Au₂Cl₆ dimers; “a bond with a large covalent share”.', '2Au + 3Cl₂ (qizdirish); kristall Au₂Cl₆ dimerlaridan iborat; «katta kovalent ulushli bogʻ».'],
  salt_ca_s: ['Ca + S.', 'Ca + S.'],
  salt_ag_br: ['Exchange Ag⁺ + Br⁻ (light-sensitive — photography); at school it is not made from the elements.', 'Almashinish Ag⁺ + Br⁻ (yorugʻlikka sezgir — fotografiya); maktabda elementlardan olinmaydi.'],
  salt_na_no2: ['2NaNO₃ → 2NaNO₂ + O₂ (heating): NO₃⁻ loses an O (N⁺⁵ → N⁺³).', '2NaNO₃ → 2NaNO₂ + O₂ (qizdirish): NO₃⁻ bitta O ni yoʻqotadi (N⁺⁵ → N⁺³).'],
  hmno4: ['H–O–MnO₃, Mn⁺⁷; exists only in solution.', 'H–O–MnO₃, Mn⁺⁷; faqat eritmada mavjud.'],
  salt_li_cl: ['2Li + Cl₂.', '2Li + Cl₂.'],
  salt_fe3_no3: ['Fe(OH)₃ + 3HNO₃.', 'Fe(OH)₃ + 3HNO₃.'],
  hclo3: ['H–O–ClO₂, Cl⁺⁵.', 'H–O–ClO₂, Cl⁺⁵.'],
  salt_ag_i: ['Exchange Ag⁺ + I⁻ (yellow precipitate); at school it is not made from the elements.', 'Almashinish Ag⁺ + I⁻ (sariq choʻkma); maktabda elementlardan olinmaydi.'],
  tb_hgo: ['2Hg + O₂ (heating, reversible) — the Lavoisier/Priestley experiment; –Hg–O– chains.', '2Hg + O₂ (qizdirish, qaytar) — Lavuazye/Pristli tajribasi; –Hg–O– zanjirlari.'],
  tb_hpo3: ['A polymer (HPO₃)ₙ: chains of PO₄ tetrahedra.', 'Polimer (HPO₃)ₙ: PO₄ tetraedrlari zanjirlari.'],
  ago: ['Exchange in solution: 2Ag⁺ + 2OH⁻ → Ag₂O↓ + H₂O (AgOH is unstable).', 'Eritmada almashinish: 2Ag⁺ + 2OH⁻ → Ag₂O↓ + H₂O (AgOH beqaror).'],
  salt_cr_cl: ['2Cr + 3Cl₂.', '2Cr + 3Cl₂.'],
  salt_k_no2: ['Like NaNO₂.', 'NaNO₂ kabi.'],
  salt_pb_i: ['Exchange Pb²⁺ + 2I⁻ — golden flakes.', 'Almashinish Pb²⁺ + 2I⁻ — oltinrang tangachalar.'],
  tb_al4c3: ['Al³⁺ and C⁴⁻ (methanide): 4 Al give 12 e⁻ to three C.', 'Al³⁺ va C⁴⁻ (metanid): 4 ta Al uchta C ga 12 e⁻ beradi.'],
  tb_cah2po42: ['Ca₃(PO₄)₂ + 4H₃PO₄: PO₄³⁻ + 2H⁺ → H₂PO₄⁻ (double superphosphate).', 'Ca₃(PO₄)₂ + 4H₃PO₄: PO₄³⁻ + 2H⁺ → H₂PO₄⁻ (qoʻsh superfosfat).'],
  salt_ca_sio3: ['Like Na₂SiO₃; SiO₂ + CaO in a melt: O²⁻ breaks the Si–O–Si bridges.', 'Na₂SiO₃ kabi; suyuqlanmada SiO₂ + CaO: O²⁻ Si–O–Si koʻpriklarini uzadi.'],
  tb_ag3po4: ['Exchange 3Ag⁺ + PO₄³⁻ — a yellow precipitate.', 'Almashinish 3Ag⁺ + PO₄³⁻ — sariq choʻkma.'],
  tb_cahpo4: ['Neutralisation to the second step (one H remains).', 'Ikkinchi bosqichgacha neytrallanish (bitta H qoladi).'],
  tb_caocl2: ['Bleaching powder is a MIXED salt: Ca²⁺, Cl⁻ and ClO⁻ (Cl⁻¹ and Cl⁺¹); Ca(OH)₂ + Cl₂: disproportionation of Cl₂ — one Cl gives, the other accepts e⁻.', 'Xlorli ohak — ARALASH tuz: Ca²⁺, Cl⁻ va ClO⁻ (Cl⁻¹ va Cl⁺¹); Ca(OH)₂ + Cl₂: Cl₂ ning disproporsiyalanishi — bir Cl e⁻ beradi, ikkinchisi qabul qiladi.'],
  tb_n2o3: ['O=N–NO₂: an N–N bond; unstable (NO + NO₂ in the cold).', 'O=N–NO₂: N–N bogʻi; beqaror (sovuqda NO + NO₂).'],
  tb_caso4_2h2o: ['Gypsum: 2 H₂O in layers between Ca²⁺ and SO₄²⁻.', 'Gips: Ca²⁺ va SO₄²⁻ orasidagi qatlamlarda 2 ta H₂O.'],
  salt_pb_cl: ['Exchange Pb²⁺ + 2Cl⁻.', 'Almashinish Pb²⁺ + 2Cl⁻.'],
  tb_kh: ['Like NaH.', 'NaH kabi.'],
  tb_naalo2: ['Fusion Al₂O₃ + 2NaOH; in the crystal — an AlO₄ framework; in solution — Na[Al(OH)₄] (said honestly).', 'Al₂O₃ + 2NaOH ni suyuqlantirish; kristallda — AlO₄ karkasi; eritmada — Na[Al(OH)₄] (rostini aytamiz).'],
  tb_beo: ['Be + O₂; wurtzite; a bond with a noticeable covalent share (Be is small).', 'Be + O₂; vyursit; sezilarli kovalent ulushli bogʻ (Be kichik).'],
  tb_cu2s: ['2Cu + S (heating).', '2Cu + S (qizdirish).'],
  salt_fe2_no3: ['Exchange FeSO₄ + Ba(NO₃)₂ (BaSO₄↓ leaves).', 'Almashinish FeSO₄ + Ba(NO₃)₂ (BaSO₄↓ chiqib ketadi).'],
  tb_kcl_mgcl2_6h2o: ['Carnallite: Mg²⁺ in an octahedron of 6 H₂O, K⁺ and Cl⁻ separately — a DOUBLE salt, three kinds of ions.', 'Karnallit: Mg²⁺ 6 ta H₂O oktaedrida, K⁺ va Cl⁻ alohida — QOʻSH tuz, uch xil ion.'],
  tb_kcl_nacl: ['A mixture — two NaCl-type lattices side by side.', 'Aralashma — yonma-yon ikki NaCl tipidagi panjara.'],
  tb_mn2o3: ['4MnO₂ → 2Mn₂O₃ + O₂ (Mn⁺⁴ → Mn⁺³).', '4MnO₂ → 2Mn₂O₃ + O₂ (Mn⁺⁴ → Mn⁺³).'],
  salt_nh4_co3: ['NH₃ + CO₂ + H₂O.', 'NH₃ + CO₂ + H₂O.'],
  tb_kclo: ['Cl₂ + 2KOH (cold): disproportionation Cl₂ → Cl⁻ + ClO⁻.', 'Cl₂ + 2KOH (sovuqda): disproporsiyalanish Cl₂ → Cl⁻ + ClO⁻.'],
  tb_p4o10: ['The same as P₂O₅ — one shared scene; P₄ + 5O₂: P–O–P bridges + terminal P=O.', 'P₂O₅ ning oʻzi — umumiy sahna; P₄ + 5O₂: P–O–P koʻpriklari + chetki P=O.'],
  tb_sif4: ['Si + 2F₂ or SiO₂ + 4HF (etching glass): the SiO₂ framework breaks; a SiF₄ tetrahedron.', 'Si + 2F₂ yoki SiO₂ + 4HF (shishani yemirish): SiO₂ karkasi buziladi; SiF₄ tetraedri.'],
  tb_feso4_7h2o: ['Hydration of Fe²⁺: 6 H₂O around Fe²⁺ + 1 attached to SO₄²⁻.', 'Fe²⁺ gidratlanishi: Fe²⁺ atrofida 6 ta H₂O + 1 tasi SO₄²⁻ ga.'],
  tb_kcl_mgso4_3h2o: ['Kainite: K⁺, Mg²⁺, Cl⁻, SO₄²⁻ and water — all kinds are shown.', 'Kainit: K⁺, Mg²⁺, Cl⁻, SO₄²⁻ va suv — hammasi koʻrsatiladi.'],
  tb_mno: ['Mn(OH)₂ → MnO + H₂O: H⁺ of one OH⁻ moves to the other — H₂O leaves, O²⁻ stays with Mn²⁺.', 'Mn(OH)₂ → MnO + H₂O: bitta OH⁻ ning H⁺ i ikkinchisiga oʻtadi — H₂O ketadi, O²⁻ Mn²⁺ da qoladi.'],
  tb_na2so4_10h2o: ['Glauber’s salt: water around Na⁺ (6 each) — all 10 molecules are shown.', 'Glauber tuzi: Na⁺ atrofida suv (6 tadan) — 10 ta molekula koʻrsatiladi.'],
  tb_nh42hpo4: ['Two H⁺ transfers from H₃PO₄ to NH₃ (the third H stays in HPO₄²⁻).', 'H₃PO₄ dan NH₃ ga ikki marta H⁺ oʻtadi (uchinchi H HPO₄²⁻ da qoladi).'],
  salt_k_cro4: ['The reverse: Cr₂O₇²⁻ + 2OH⁻ → 2CrO₄²⁻ + H₂O.', 'Teskarisi: Cr₂O₇²⁻ + 2OH⁻ → 2CrO₄²⁻ + H₂O.'],
  tb_ca3p2: ['Ca²⁺ and P³⁻: 3 Ca give 6 e⁻ to two P.', 'Ca²⁺ va P³⁻: 3 ta Ca ikki P ga 6 e⁻ beradi.'],
  tb_n2o4: ['Two NO₂ molecules pair their unpaired e⁻ into an N–N bond (weak, long) — dimerisation; this is combination (2NO₂ → N₂O₄), not decomposition.', 'Ikki NO₂ molekulasi juftlashmagan e⁻ larini N–N bogʻiga birlashtiradi (kuchsiz, uzun) — dimerlanish; bu birikish (2NO₂ → N₂O₄), parchalanish emas.'],
  tb_na2zno2: ['Fusion ZnO + 2NaOH; in solution — Na₂[Zn(OH)₄].', 'ZnO + 2NaOH ni suyuqlantirish; eritmada — Na₂[Zn(OH)₄].'],
  tb_bao2: ['2BaO + O₂ (heating): O²⁻ + ½O₂ → O₂²⁻ — oxygen adds on.', '2BaO + O₂ (qizdirish): O²⁻ + ½O₂ → O₂²⁻ — kislorod birikadi.'],
  tb_h4p2o7: ['Two H₃PO₄ − H₂O: a P–O–P bridge (condensation) — water splits off.', 'Ikki H₃PO₄ − H₂O: P–O–P koʻprigi (kondensatsiya) — suv ajraladi.'],
  tb_ko2: ['K + O₂: O₂ accepts 1 e⁻ → O₂⁻ (superoxide, an odd e⁻).', 'K + O₂: O₂ 1 e⁻ oladi → O₂⁻ (superoksid, toq e⁻).'],
  tb_na2znoh4: ['Zn(OH)₂ + 2OH⁻: two OH⁻ give pairs to Zn²⁺ (donor–acceptor) → the [Zn(OH)₄]²⁻ tetrahedron — amphoteric behaviour.', 'Zn(OH)₂ + 2OH⁻: ikki OH⁻ Zn²⁺ ga juft beradi (donor-akseptor) → [Zn(OH)₄]²⁻ tetraedri — amfoterlik.'],
  salt_k_so3: ['Like Na₂SO₃.', 'Na₂SO₃ kabi.'],
  salt_nh4_cr2o7: ['An ionic salt with Cr₂O₇²⁻ and NH₄⁺ (Cr–O–Cr bridge).', 'Cr₂O₇²⁻ va NH₄⁺ li ion tuz (Cr–O–Cr koʻprigi).'],
  tb_mg3po42: ['Exchange.', 'Almashinish.'],
}

/**
 * Русский текст «особенности» для панели там, где заметка таблицы для анимации («— показать …», «Этапы: …») несёт
 * сам факт: автоматическая чистка (formationTeacher.cleanRu) отрезала бы его, и RU стал бы короче EN / UZ.
 */
const RU_FULL: Record<string, string> = {
  sio2: 'НЕ ионная и НЕ молекула! Si (4 валентных e⁻) образует 4 полярные ковалентные связи Si–O; каждый O — мостик между двумя Si; тетраэдры SiO₄ соединяются вершинами в каркас (кварц). Формула SiO₂ — простейшая; атомная решётка (§ 17).',
  tb_i2: 'Как Cl₂; твёрдое — МОЛЕКУЛЯРНАЯ решётка (молекулы I₂ в узлах, § 17): видна укладка молекул.',
  salt_k_mno4: 'Mn⁺⁷ в тетраэдре O; получают окислением K₂MnO₄ хлором — ион MnO₄²⁻ теряет 1 e⁻ (зелёный → фиолетовый).',
  fe3o4: 'Магнетит = FeO·Fe₂O₃: Fe²⁺ и Fe³⁺ в одной решётке (шпинель) — два вида катионов с зарядами +2/+3.',
  cro3: 'ПОЛИМЕР: цепи тетраэдров CrO₄ с общими вершинами, (CrO₃)ₙ; на модели — цепь из 3–4 звеньев, Cr⁺⁶.',
  tb_na2so4_10h2o: 'Глауберова соль: вода вокруг Na⁺ (по 6) — все 10 молекул воды на модели.',
}

export function formationSpecialRu(id: string): string | null {
  return RU_FULL[id] ?? null
}

export function formationSpecialText(id: string, lang: 'en' | 'uz'): string | null {
  const t = T[id]
  return t ? t[lang === 'en' ? 0 : 1] : null
}

export const FORMATION_SPECIAL_IDS: readonly string[] = Object.keys(T)
