import type { ChemistryKnowledgeChunk } from '../learnChemistryKnowledgeBase'

/**
 * Учёные химии и естествознания — для вопросов «кто такой Менделеев»,
 * «что открыл Лавуазье», «вклад Ибн Сины». Школьная программа 7–11 класс.
 */

export type ScientistEntry = {
  id: string
  ru: string
  en: string
  /** Кратко по-узбекски (необязательно). */
  uz?: string
  keywords: string[]
}

const SCIENTISTS: ScientistEntry[] = [
  {
    id: 'mendeleev',
    keywords: ['mendeleyev', 'менделеев', 'mendeleev', 'периодический закон', 'периодическая таблица', 'periodic law'],
    ru: 'Дмитрий Иванович Менделеев (1834–1907) — русский химик, автор **Периодического закона** (1869). Он расположил элементы по возрастанию атомной массы и открыл периодичность их свойств, оставив пустые клетки и предсказав свойства ещё не открытых элементов (галлий, скандий, германий). Его именем названа Периодическая таблица химических элементов.',
    en: 'Dmitri Mendeleev (1834–1907) — Russian chemist, author of the Periodic Law (1869) and the periodic table; predicted undiscovered elements.',
    uz: 'Dmitriy Ivanovich Mendeleyev (1834–1907) — rus kimyogari, Davriy qonun muallifi (1869); elementlarni atom massasi ortib borishi tartibida joylashtirib, hali ochilmagan elementlarning xossalarini bashorat qilgan.',
  },
  {
    id: 'lavoisier',
    keywords: ['lavuazye', 'лавуазье', 'lavoisier', 'закон сохранения массы', 'кислород назвал'],
    ru: 'Антуан Лавуазье (1743–1794) — французский химик, «отец современной химии». Сформулировал **закон сохранения массы** веществ, объяснил роль кислорода в горении и дыхании, ввёл понятие химического элемента и современную номенклатуру.',
    en: 'Antoine Lavoisier (1743–1794) — father of modern chemistry; law of conservation of mass; explained combustion and oxygen.',
    uz: 'Antuan Lavuazye (1743–1794) — fransuz kimyogari, zamonaviy kimyoning asoschisi; massaning saqlanish qonuni, yonish va kislorodning rolini tushuntirgan.',
  },
  {
    id: 'lomonosov',
    keywords: ['ломоносов', 'lomonosov'],
    ru: 'Михаил Васильевич Ломоносов (1711–1765) — русский учёный-энциклопедист. Независимо сформулировал **закон сохранения массы вещества** и заложил основы атомно-молекулярного учения в России.',
    en: 'Mikhail Lomonosov (1711–1765) — Russian polymath; conservation of mass; atomic-molecular theory.',
    uz: 'Mixail Vasilyevich Lomonosov (1711–1765) — rus olimi; massaning saqlanish qonuni, atom-molekulyar ta’limot.',
  },
  {
    id: 'dalton',
    keywords: ['дальтон', 'dalton', 'атомная теория', 'atomic theory'],
    ru: 'Джон Дальтон (1766–1844) — английский химик и физик, создатель **атомной теории**. Утверждал, что вещества состоят из атомов, у каждого элемента свои атомы с определённой массой; ввёл относительные атомные массы.',
    en: 'John Dalton (1766–1844) — atomic theory; each element has atoms of a characteristic mass.',
    uz: 'Jon Dalton (1766–1844) — ingliz olimi; atom nazariyasi: har bir elementning o‘z atomlari bor, ular birikib molekulalar hosil qiladi.',
  },
  {
    id: 'avogadro',
    keywords: ['авогадро', 'avogadro', 'число авогадро', 'моль'],
    ru: 'Амедео Авогадро (1776–1856) — итальянский учёный. **Закон Авогадро**: в равных объёмах газов при одинаковых условиях содержится одинаковое число молекул. Его именем названо число Авогадро Nₐ ≈ 6,02·10²³ частиц в 1 моль.',
    en: 'Amedeo Avogadro (1776–1856) — equal volumes of gases contain equal numbers of molecules; Avogadro number ≈ 6.02·10²³.',
    uz: 'Amedeo Avogadro (1776–1856) — italyan olimi; Avogadro qonuni: bir xil sharoitda teng hajmdagi gazlarda molekulalar soni teng.',
  },
  {
    id: 'rutherford',
    keywords: ['rezerford', 'резерфорд', 'rutherford', 'ядро атома', 'nucleus'],
    ru: 'Эрнест Резерфорд (1871–1937) — британский физик. Опытом с рассеянием α-частиц доказал существование **атомного ядра** и предложил планетарную модель атома. Открыл протон.',
    en: 'Ernest Rutherford (1871–1937) — discovered the atomic nucleus (gold foil experiment); planetary model; proton.',
    uz: 'Ernest Rezerford (1871–1937) — britaniyalik fizik; atom yadrosini kashf etgan (oltin zar tajribasi, 1911), atomning planetar modeli.',
  },
  {
    id: 'bohr',
    keywords: ['nils bor', 'бор', 'нильс бор', 'niels bohr', 'модель бора', 'орбит'],
    ru: 'Нильс Бор (1885–1962) — датский физик. Предложил **планетарную (боровскую) модель атома**: электроны движутся по разрешённым орбитам (энергетическим уровням) и излучают/поглощают энергию при переходах.',
    en: 'Niels Bohr (1885–1962) — Bohr model of the atom; electrons on quantized orbits.',
    uz: 'Nils Bor (1885–1962) — daniyalik fizik; Bor atom modeli: elektronlar aniq energiyali orbitalarda harakatlanadi.',
  },
  {
    id: 'curie',
    keywords: ['kyuri', 'mariya kyuri', 'кюри', 'мария кюри', 'curie', 'радиоактивность', 'полоний', 'радий'],
    ru: 'Мария Склодовская-Кюри (1867–1934) — учёный, дважды лауреат Нобелевской премии. Исследовала **радиоактивность**, открыла элементы полоний и радий (вместе с Пьером Кюри).',
    en: 'Marie Curie (1867–1934) — radioactivity research; discovered polonium and radium; two Nobel Prizes.',
    uz: 'Mariya Sklodovskaya-Kyuri (1867–1934) — ikki marta Nobel mukofoti sovrindori; radioaktivlikni o‘rgangan, poloniy va radiy elementlarini kashf etgan.',
  },
  {
    id: 'boyle',
    keywords: ['boyl', 'бойль', 'boyle', 'закон бойля'],
    ru: 'Роберт Бойль (1627–1691) — англо-ирландский химик, один из основателей научной химии. Дал определение химического элемента, открыл **закон Бойля–Мариотта** (p·V = const при постоянной температуре).',
    en: 'Robert Boyle (1627–1691) — defined chemical element; Boyle’s law (pV = const at constant T).',
    uz: 'Robert Boyl (1627–1691) — ingliz olimi; kimyoviy element tushunchasini kiritgan; Boyl qonuni (pV = const).',
  },
  {
    id: 'arrhenius',
    keywords: ['arrenius', 'аррениус', 'arrhenius', 'электролитическая диссоциация', 'ионы'],
    ru: 'Сванте Аррениус (1859–1927) — шведский химик. Создал **теорию электролитической диссоциации**: при растворении электролиты распадаются на ионы, поэтому растворы проводят ток.',
    en: 'Svante Arrhenius (1859–1927) — theory of electrolytic dissociation into ions.',
    uz: 'Svante Arrenius (1859–1927) — shved olimi; elektrolitik dissotsiatsiya nazariyasi: eritmada elektrolitlar ionlarga ajraladi.',
  },
  {
    id: 'ibn-sina',
    keywords: ['ибн сина', 'авиценна', 'ibn sina', 'ibn sino', 'sino', 'avicenna'],
    ru: 'Ибн Сина (Авиценна, 980–1037) — великий учёный Востока родом из Средней Азии. Внёс вклад в медицину, естествознание и химию (перегонка, получение эфирных масел). Автор «Канона врачебной науки».',
    en: 'Ibn Sina (Avicenna, 980–1037) — Central Asian scholar; medicine, distillation, natural sciences.',
    uz: 'Ibn Sino (Abu Ali ibn Sino, 980–1037) — buyuk Markaziy Osiyo olimi; tibbiyot, distillash va dorivor moddalar haqida asarlar.',
  },
  {
    id: 'al-biruni',
    keywords: ['beruniy', 'беруни', 'аль-беруни', 'biruni', 'al-biruni'],
    ru: 'Абу Райхан Беруни (973–1048) — среднеазиатский учёный-энциклопедист. Точно определял плотность (удельный вес) металлов и минералов, развивал минералогию и естественные науки.',
    en: 'Abu Rayhan al-Biruni (973–1048) — measured densities of metals and minerals; mineralogy.',
    uz: 'Abu Rayhon Beruniy (973–1048) — xorazmlik olim; metallar va minerallarning zichligini aniq o‘lchagan.',
  },
  {
    id: 'jabir',
    keywords: ['jobir', 'джабир', 'гебер', 'jabir', 'geber'],
    ru: 'Джабир ибн Хайян (Гебер, ~721–815) — один из основоположников практической химии (алхимии). Описал перегонку, кристаллизацию, получение кислот, ввёл лабораторные методы.',
    en: 'Jabir ibn Hayyan (Geber, c.721–815) — founder of practical chemistry; distillation, crystallization, acids.',
    uz: 'Jobir ibn Hayyon (Geber, taxm. 721–815) — amaliy kimyo asoschisi; distillash, kristallash, kislotalar.',
  },
  {
    id: 'ar-razi',
    keywords: ['roziy', 'ар-рази', 'разес', 'razi', 'rhazes'],
    ru: 'Ар-Рази (Разес, 865–925) — учёный и врач. Систематизировал вещества, описал химическую посуду и опыты, применил химию в медицине.',
    en: 'Al-Razi (Rhazes, 865–925) — classified substances; chemical apparatus; applied chemistry in medicine.',
    uz: 'Abu Bakr ar-Roziy (865–925) — moddalarni tasniflagan, kimyoviy asboblarni tavsiflagan olim va tabib.',
  },
  {
    id: 'al-kindi',
    keywords: ['kindiy', 'аль-кинди', 'кинди', 'al-kindi', 'kindi'],
    ru: 'Аль-Кинди (801–873) — арабский философ и учёный. Один из первых критиковал алхимические заблуждения, занимался перегонкой и получением ароматических веществ.',
    en: 'Al-Kindi (801–873) — early scholar; distillation and perfumery; critiqued alchemy.',
    uz: 'Al-Kindiy (801–873) — ilk olimlardan; distillash va atir-upa kimyosi.',
  },
  {
    id: 'butlerov',
    keywords: ['бутлеров', 'butlerov', 'теория строения', 'строение органических'],
    ru: 'Александр Михайлович Бутлеров (1828–1886) — русский химик, создатель **теории химического строения органических веществ**: свойства зависят от порядка соединения атомов в молекуле (структуры).',
    en: 'Alexander Butlerov (1828–1886) — theory of chemical structure of organic compounds.',
    uz: 'Aleksandr Mixaylovich Butlerov (1828–1886) — rus kimyogari; organik moddalar kimyoviy tuzilishi nazariyasi (1861).',
  },
  {
    id: 'faraday',
    keywords: ['faradey', 'фарадей', 'faraday', 'электролиз'],
    ru: 'Майкл Фарадей (1791–1867) — английский учёный. Открыл законы **электролиза**, ввёл термины «ион», «электрод», «электролит».',
    en: 'Michael Faraday (1791–1867) — laws of electrolysis; terms ion, electrode, electrolyte.',
    uz: 'Maykl Faradey (1791–1867) — ingliz olimi; elektroliz qonunlari; «ion», «elektrod», «elektroliz» atamalari.',
  },
  {
    id: 'thomson',
    keywords: ['tomson', 'томсон', 'thomson', 'электрон открыл'],
    ru: 'Джозеф Джон Томсон (1856–1940) — английский физик, открыл **электрон** (1897) и предложил модель атома «пудинг с изюмом».',
    en: 'J. J. Thomson (1856–1940) — discovered the electron; plum-pudding model.',
    uz: 'Jozef Jon Tomson (1856–1940) — ingliz fizigi; elektronni kashf etgan (1897).',
  },
  {
    id: 'chadwick',
    keywords: ['chedvik', 'чедвик', 'chadwick', 'нейтрон открыл'],
    ru: 'Джеймс Чедвик (1891–1974) — английский физик, открыл **нейтрон** (1932) — незаряженную частицу ядра.',
    en: 'James Chadwick (1891–1974) — discovered the neutron (1932).',
    uz: 'Jeyms Chedvik (1891–1974) — ingliz fizigi; neytronni kashf etgan (1932).',
  },
  {
    id: 'berzelius',
    keywords: ['bertselius', 'берцелиус', 'berzelius', 'символы элементов'],
    ru: 'Йёнс Якоб Берцелиус (1779–1848) — шведский химик. Ввёл современные **буквенные символы элементов** (H, O, Fe), точно определил атомные массы многих элементов, открыл церий, селен, торий.',
    en: 'Jöns Jacob Berzelius (1779–1848) — introduced letter symbols for elements; measured atomic masses.',
    uz: 'Yons Yakob Bertselius (1779–1848) — shved kimyogari; elementlarning harfli belgilarini kiritgan, ko‘plab atom massalarini aniqlagan.',
  },
  {
    id: 'gaylussac',
    keywords: ['gey-lyussak', 'lyussak', 'гей-люссак', 'гей люссак', 'gay-lussac', 'объёмные отношения'],
    ru: 'Жозеф Гей-Люссак (1778–1850) — французский химик и физик. Открыл **закон объёмных отношений газов** и закон теплового расширения газов (закон Гей-Люссака).',
    en: 'Joseph Gay-Lussac (1778–1850) — law of combining gas volumes; gas expansion law.',
    uz: 'Jozef Lui Gey-Lyussak (1778–1850) — fransuz olimi; gazlarning hajmiy nisbatlari qonuni.',
  },
  {
    id: 'proust',
    keywords: ['prust', 'пруст', 'proust', 'постоянства состава'],
    ru: 'Жозеф Пруст (1754–1826) — французский химик. Сформулировал **закон постоянства состава**: любое чистое вещество имеет постоянный качественный и количественный состав.',
    en: 'Joseph Proust (1754–1826) — law of definite proportions (constant composition).',
    uz: 'Jozef Lui Prust (1754–1826) — fransuz kimyogari; tarkibning doimiylik qonuni.',
  },
  {
    id: 'lechatelier',
    keywords: ['shatelye', 'ле шателье', 'ле-шателье', 'chatelier', 'принцип равновес'],
    ru: 'Анри Ле Шателье (1850–1936) — французский химик. **Принцип Ле Шателье**: если на систему в равновесии подействовать (изменить t, p, концентрацию), равновесие смещается так, чтобы ослабить это воздействие.',
    en: 'Henri Le Chatelier (1850–1936) — Le Chatelier’s principle of equilibrium shift.',
    uz: 'Anri Le Shatelye (1850–1936) — fransuz olimi; kimyoviy muvozanat siljishi prinsipi.',
  },
  {
    id: 'pauling',
    keywords: ['poling', 'полинг', 'pauling', 'электроотрицательность', 'природа связи'],
    ru: 'Лайнус Полинг (1901–1994) — американский химик. Развил теорию **химической связи** и ввёл шкалу **электроотрицательности**. Дважды лауреат Нобелевской премии.',
    en: 'Linus Pauling (1901–1994) — nature of the chemical bond; electronegativity scale.',
    uz: 'Laynus Poling (1901–1994) — amerikalik kimyogar; kimyoviy bog‘ tabiati, elektromanfiylik shkalasi; ikki Nobel mukofoti.',
  },
  {
    id: 'nobel',
    keywords: ['нобель', 'nobel', 'динамит', 'нобелевская премия'],
    ru: 'Альфред Нобель (1833–1896) — шведский химик и инженер, изобрёл **динамит**. Завещал состояние на учреждение Нобелевской премии.',
    en: 'Alfred Nobel (1833–1896) — invented dynamite; founded the Nobel Prize.',
    uz: 'Alfred Nobel (1833–1896) — shved kimyogari va muhandisi; dinamitni ixtiro qilgan, Nobel mukofotini ta’sis etgan.',
  },
  {
    id: 'zelinsky',
    keywords: ['zelinskiy', 'зелинский', 'zelinsky', 'противогаз', 'угольный'],
    ru: 'Николай Дмитриевич Зелинский (1861–1953) — русский химик-органик. Изобрёл **угольный противогаз** (1915), развивал органический катализ и нефтехимию.',
    en: 'Nikolai Zelinsky (1861–1953) — invented the activated-charcoal gas mask; organic catalysis.',
    uz: 'Nikolay Dmitriyevich Zelinskiy (1861–1953) — rus kimyogari; ko‘mirli protivogaz (1915), organik kataliz.',
  },
  {
    id: 'markovnikov',
    keywords: ['марковников', 'markovnikov', 'правило марковникова'],
    ru: 'Владимир Марковников (1838–1904) — русский химик. **Правило Марковникова**: при присоединении к несимметричному алкену водород идёт к более гидрогенизированному атому углерода.',
    en: 'Vladimir Markovnikov (1838–1904) — Markovnikov’s rule of addition to alkenes.',
    uz: 'Vladimir Markovnikov (1838–1904) — rus kimyogari; Markovnikov qoidasi (birikish reaksiyalari yo‘nalishi).',
  },
  {
    id: 'kekule',
    keywords: ['кекуле', 'kekule', 'бензол', 'структура бензола'],
    ru: 'Фридрих Кекуле (1829–1896) — немецкий химик. Предложил **циклическую структуру бензола** (кольцо из шести атомов углерода) и идеи о валентности углерода.',
    en: 'Friedrich Kekulé (1829–1896) — proposed the ring structure of benzene.',
    uz: 'Avgust Kekule (1829–1896) — nemis kimyogari; benzolning halqali tuzilishi.',
  },
  {
    id: 'wohler',
    keywords: ['vyoler', 'вёлер', 'велер', 'wohler', 'мочевина', 'синтез органики'],
    ru: 'Фридрих Вёлер (1800–1882) — немецкий химик. В 1828 году синтезировал **мочевину** из неорганических веществ, опровергнув «витализм» и открыв органический синтез.',
    en: 'Friedrich Wöhler (1800–1882) — synthesized urea, founding organic synthesis.',
    uz: 'Fridrix Vyoler (1800–1882) — nemis kimyogari; anorganik moddadan mochevinani sintez qilgan (1828).',
  },
  {
    id: 'priestley',
    keywords: ['pristli', 'пристли', 'priestley', 'открыл кислород'],
    ru: 'Джозеф Пристли (1733–1804) — английский химик, один из первооткрывателей **кислорода** (1774), исследовал газы (получил «дефлогистированный воздух»).',
    en: 'Joseph Priestley (1733–1804) — co-discoverer of oxygen; studied gases.',
    uz: 'Jozef Pristli (1733–1804) — ingliz olimi; kislorodni olgan (1774).',
  },
  {
    id: 'davy',
    keywords: ['devi', 'дэви', 'дэйви', 'davy', 'электролиз металлов'],
    ru: 'Гемфри Дэви (1778–1829) — английский химик. Электролизом впервые получил **натрий, калий, кальций, магний, барий**, изучал электрохимию.',
    en: 'Humphry Davy (1778–1829) — isolated Na, K, Ca, Mg, Ba by electrolysis.',
    uz: 'Hemfri Devi (1778–1829) — ingliz kimyogari; elektroliz yo‘li bilan natriy, kaliy, kaltsiy va boshqa metallarni ajratgan.',
  },
  {
    id: 'bunsen',
    keywords: ['bunzen', 'бунзен', 'bunsen', 'горелка', 'спектральный анализ'],
    ru: 'Роберт Бунзен (1811–1899) — немецкий химик. Создал **горелку Бунзена** и вместе с Кирхгофом — спектральный анализ, открыл цезий и рубидий.',
    en: 'Robert Bunsen (1811–1899) — Bunsen burner; spectral analysis; discovered Cs and Rb.',
    uz: 'Robert Bunzen (1811–1899) — nemis kimyogari; Bunzen gorelkasi, spektral analiz (Kirxgof bilan).',
  },
  {
    id: 'moseley',
    keywords: ['mozli', 'мозли', 'moseley', 'заряд ядра', 'порядковый номер'],
    ru: 'Генри Мозли (1887–1915) — английский физик. Показал, что свойства элементов определяются **зарядом ядра (порядковым номером Z)**, а не атомной массой, уточнив Периодический закон.',
    en: 'Henry Moseley (1887–1915) — properties depend on nuclear charge (atomic number Z).',
    uz: 'Genri Mozli (1887–1915) — ingliz fizigi; yadro zaryadi tartib raqamiga teng ekanini ko‘rsatgan (1913).',
  },
  {
    id: 'butlerov2',
    keywords: ['зинин', 'zinin', 'анилин'],
    ru: 'Николай Зинин (1812–1880) — русский химик-органик. Разработал **реакцию восстановления** нитробензола в анилин — основу анилинокрасочной промышленности.',
    en: 'Nikolai Zinin (1812–1880) — reduction of nitrobenzene to aniline (Zinin reaction).',
    uz: 'Nikolay Zinin (1812–1880) — rus kimyogari; nitrobenzoldan anilin olgan (1842).',
  },
  {
    id: 'berthollet',
    keywords: ['bertolle', 'бертолле', 'berthollet', 'бертоллетова соль'],
    ru: 'Клод Бертолле (1748–1822) — французский химик. Исследовал влияние массы веществ на реакции; его именем названа бертоллетова соль KClO₃.',
    en: 'Claude Berthollet (1748–1822) — studied reaction affinity; KClO₃ is named after him.',
    uz: 'Klod Lui Bertolle (1748–1822) — fransuz kimyogari; bertolle tuzi (KClO₃), oqartirish.',
  },
  {
    id: 'kurchatov',
    keywords: ['курчатов', 'kurchatov', 'атомная'],
    ru: 'Игорь Курчатов (1903–1960) — советский физик, руководитель атомного проекта, исследователь ядерных реакций и деления ядер. Элемент №104 назван курчатовием.',
    en: 'Igor Kurchatov (1903–1960) — nuclear physicist; led the Soviet atomic project.',
    uz: 'Igor Kurchatov (1903–1960) — sovet fizigi; atom energetikasi va yadro dasturi rahbari.',
  },
  // ---- расширение: история химии, промышленность, биохимия, материалы, Узбекистан (только общеизвестные факты)
  {
    id: 'scheele',
    keywords: ['шееле', 'scheele'],
    ru: 'Карл Вильгельм Шееле (1742–1786) — шведский химик-аптекарь. Открыл **кислород** (независимо от Пристли), хлор, марганец, молибден, а также множество кислот: винную, лимонную, молочную, синильную. Работал в аптеке без университетского образования и имел привычку пробовать вещества на вкус. В школьном курсе — история открытия кислорода (7 класс).',
    en: 'Carl Wilhelm Scheele (1742–1786) — Swedish pharmacist-chemist; discovered oxygen independently, chlorine, manganese and many organic acids.',
    uz: 'Karl Vilgelm Sheele (1742–1786) — shved kimyogari; kislorod (mustaqil), xlor va koʻplab kislotalarni kashf etgan.',
  },
  {
    id: 'cavendish',
    keywords: ['кавендиш', 'cavendish'],
    ru: 'Генри Кавендиш (1731–1810) — английский физик и химик. В 1766 году получил и описал **водород** («горючий воздух»), а позже показал, что при его горении образуется вода, то есть вода — не элемент, а соединение. Был крайне замкнутым человеком и общался с прислугой записками. В школьном курсе — получение водорода и состав воды (7–8 класс).',
    en: 'Henry Cavendish (1731–1810) — English scientist; isolated hydrogen (1766) and showed that water forms when it burns.',
    uz: 'Genri Kavendish (1731–1810) — ingliz olimi; vodorodni ajratib olgan (1766) va suvning tarkibini aniqlagan.',
  },
  {
    id: 'hess',
    keywords: ['гесс', 'hess', 'закон гесса'],
    ru: 'Герман Иванович Гесс (1802–1850) — русский химик швейцарского происхождения, основоположник термохимии. В 1840 году сформулировал **закон Гесса**: тепловой эффект реакции не зависит от пути процесса, а только от начального и конечного состояний. Преподавал в Петербурге и написал один из первых русских учебников химии. В школьном курсе — термохимические уравнения (9 и 11 класс).',
    en: 'Germain Henri Hess (1802–1850) — founder of thermochemistry; Hess’s law (1840): the heat of reaction does not depend on the pathway.',
    uz: 'German Gess (1802–1850) — termokimyo asoschisi; Gess qonuni (1840): reaksiya issiqlik effekti yoʻlga bogʻliq emas.',
  },
  {
    id: 'zaitsev',
    keywords: ['зайцев', 'zaitsev', 'saytzeff', 'правило зайцева'],
    ru: 'Александр Михайлович Зайцев (1841–1910) — русский химик-органик, ученик Бутлерова. Сформулировал **правило Зайцева** (1875): при отщеплении галогеноводорода или воды водород уходит от наименее гидрогенизированного атома углерода. Полвека преподавал в Казани и воспитал целую школу химиков. В школьном курсе — реакции отщепления у алкенов (10 класс).',
    en: 'Alexander Zaitsev (1841–1910) — Russian organic chemist; Zaitsev’s rule (1875) for elimination reactions.',
    uz: 'Aleksandr Zaytsev (1841–1910) — rus organik kimyogari; ajralish reaksiyalari uchun Zaytsev qoidasi (1875).',
  },
  {
    id: 'lebedev',
    keywords: ['лебедев', 'lebedev', 'синтетический каучук'],
    ru: 'Сергей Васильевич Лебедев (1874–1934) — русский химик. Разработал первый промышленный способ получения **синтетического каучука** из бутадиена, который получали из этилового спирта; в 1932 году в СССР заработал первый в мире завод синтетического каучука. Начинал исследования полимеризации диенов ещё в 1910 году. В школьном курсе — диены и каучуки (10 класс).',
    en: 'Sergei Lebedev (1874–1934) — Russian chemist; first industrial synthetic rubber from butadiene (plant launched 1932).',
    uz: 'Sergey Lebedev (1874–1934) — rus kimyogari; butadiendan sanoat sintetik kauchugi (1932).',
  },
  {
    id: 'semenov',
    keywords: ['семёнов', 'семенов', 'semenov', 'semyonov', 'цепные реакции'],
    ru: 'Николай Николаевич Семёнов (1896–1986) — советский физикохимик, создатель теории **цепных реакций** (разветвлённые цепи, взрывные пределы). В 1956 году получил Нобелевскую премию по химии (вместе с Сирилом Хиншелвудом) — первую Нобелевскую премию советского учёного. Основал Институт химической физики. В школьном курсе — скорость реакций и механизм горения (9 класс).',
    en: 'Nikolay Semenov (1896–1986) — Soviet physical chemist; theory of chain reactions; Nobel Prize in Chemistry 1956.',
    uz: 'Nikolay Semyonov (1896–1986) — zanjir reaksiyalar nazariyasi; 1956-yil kimyo boʻyicha Nobel mukofoti.',
  },
  {
    id: 'haber',
    keywords: ['габер', 'хабер', 'haber', 'синтез аммиака'],
    ru: 'Фриц Габер (1868–1934) — немецкий химик. Разработал **синтез аммиака** из азота и водорода при высоком давлении на катализаторе (процесс Габера–Боша), за что получил Нобелевскую премию по химии 1918 года. Этот процесс сделал возможным массовое производство азотных удобрений и, по оценкам, кормит значительную часть человечества. Фигура противоречивая: в Первую мировую войну руководил разработкой химического оружия. В школьном курсе — обратимые реакции, равновесие, производство аммиака (9 класс).',
    en: 'Fritz Haber (1868–1934) — German chemist; ammonia synthesis from N₂ and H₂ (Haber–Bosch process); Nobel Prize 1918.',
    uz: 'Fris Gaber (1868–1934) — nemis kimyogari; azot va vodoroddan ammiak sintezi; 1918-yil Nobel mukofoti.',
  },
  {
    id: 'bosch',
    keywords: ['бош', 'bosch', 'карл бош'],
    ru: 'Карл Бош (1874–1940) — немецкий химик-технолог и инженер. Перевёл лабораторный синтез аммиака Габера в **промышленный процесс** при давлении в сотни атмосфер, решив задачи с прочными реакторами и дешёвым катализатором. Нобелевская премия по химии 1931 года за методы высокого давления. В школьном курсе — химическое производство и условия смещения равновесия (9 класс).',
    en: 'Carl Bosch (1874–1940) — German engineer; scaled the Haber ammonia synthesis to industry; Nobel Prize 1931.',
    uz: 'Karl Bosh (1874–1940) — nemis muhandisi; ammiak sintezini sanoatga joriy etgan; 1931-yil Nobel mukofoti.',
  },
  {
    id: 'ostwald',
    keywords: ['оствальд', 'ostwald', 'катализ'],
    ru: 'Вильгельм Оствальд (1853–1932) — немецкий физикохимик, родился в Риге. Дал современное определение **катализа**, разработал промышленный способ получения азотной кислоты окислением аммиака (процесс Оствальда), сформулировал закон разбавления. Нобелевская премия по химии 1909 года. Увлекался живописью и теорией цвета. В школьном курсе — катализаторы, производство HNO₃ (9 класс).',
    en: 'Wilhelm Ostwald (1853–1932) — physical chemist; defined catalysis; nitric acid from ammonia (Ostwald process); Nobel Prize 1909.',
    uz: 'Vilgelm Ostvald (1853–1932) — kataliz tushunchasi; ammiakdan nitrat kislota olish; 1909-yil Nobel mukofoti.',
  },
  {
    id: 'vanthoff',
    keywords: ['вант-гофф', 'вант гофф', "van 't hoff", 'vant hoff', 'правило вант-гоффа'],
    ru: "Якоб Хендрик Вант-Гофф (1852–1911) — нидерландский химик, **первый лауреат Нобелевской премии по химии** (1901). Предложил тетраэдрическую модель атома углерода (основа стереохимии), вывел законы химической кинетики и осмотического давления растворов. Эмпирическое правило Вант-Гоффа: при нагревании на 10 °C скорость реакции растёт в 2–4 раза. В школьном курсе — скорость реакций (9 класс) и строение органических молекул (10 класс).",
    en: "Jacobus van 't Hoff (1852–1911) — Dutch chemist; first Nobel Prize in Chemistry (1901); tetrahedral carbon, kinetics, osmotic pressure.",
    uz: "Yakob Vant-Goff (1852–1911) — kimyo boʻyicha birinchi Nobel mukofoti (1901); tetraedrik uglerod, kinetika, osmotik bosim.",
  },
  {
    id: 'nernst',
    keywords: ['нернст', 'nernst'],
    ru: 'Вальтер Нернст (1864–1941) — немецкий физикохимик. Вывел **уравнение Нернста** для электродного потенциала, сформулировал третье начало термодинамики (тепловую теорему), за что получил Нобелевскую премию по химии 1920 года. Изобрёл электрическую лампу с керамическим стержнем накала. В школьном курсе — электрохимический ряд напряжений и гальванические элементы (9 и 11 класс).',
    en: 'Walther Nernst (1864–1941) — German physical chemist; Nernst equation; third law of thermodynamics; Nobel Prize 1920.',
    uz: 'Valter Nernst (1864–1941) — Nernst tenglamasi; termodinamikaning uchinchi qonuni; 1920-yil Nobel mukofoti.',
  },
  {
    id: 'gibbs',
    keywords: ['гиббс', 'gibbs', 'энергия гиббса'],
    ru: 'Джозайя Уиллард Гиббс (1839–1903) — американский физик и математик, создатель химической термодинамики. Ввёл понятие свободной энергии (**энергия Гиббса** ΔG), по знаку которой судят о возможности самопроизвольной реакции, вывел правило фаз. Всю жизнь проработал в Йельском университете, первые годы — без жалованья. В школьном курсе — направление реакций и энтальпия (11 класс).',
    en: 'Josiah Willard Gibbs (1839–1903) — American scientist; founder of chemical thermodynamics; Gibbs free energy; phase rule.',
    uz: 'Jozaya Uillard Gibbs (1839–1903) — kimyoviy termodinamika asoschisi; Gibbs energiyasi; fazalar qoidasi.',
  },
  {
    id: 'pasteur',
    keywords: ['пастер', 'pasteur', 'брожение', 'пастеризация'],
    ru: 'Луи Пастер (1822–1895) — французский химик и микробиолог. Начинал как химик: в 1848 году разделил кристаллы солей винной кислоты на «правые» и «левые» и открыл **оптическую изомерию**. Доказал, что брожение и гниение вызывают микроорганизмы, придумал пастеризацию, создал вакцины против сибирской язвы и бешенства. В школьном курсе — изомерия (10 класс), спиртовое брожение глюкозы (10 класс).',
    en: 'Louis Pasteur (1822–1895) — French chemist and microbiologist; optical isomers of tartaric acid (1848); fermentation; pasteurisation; vaccines.',
    uz: 'Lui Paster (1822–1895) — fransuz kimyogari va mikrobiologi; optik izomeriya (1848); bijgʻish; pasterlash; vaksinalar.',
  },
  {
    id: 'liebig',
    keywords: ['либих', 'liebig', 'холодильник либиха', 'минеральные удобрения'],
    ru: 'Юстус Либих (1803–1873) — немецкий химик. Создал в Гисене первую **учебную химическую лабораторию** для студентов — так родилась современная система обучения химии. Основал агрохимию: доказал, что растения питаются минеральными веществами из почвы, и предложил минеральные удобрения. Его именем назван лабораторный холодильник Либиха и мясной экстракт. В школьном курсе — удобрения (9 класс) и лабораторная посуда.',
    en: 'Justus von Liebig (1803–1873) — German chemist; first teaching laboratory; agricultural chemistry and mineral fertilisers; Liebig condenser.',
    uz: 'Yustus Libix (1803–1873) — nemis kimyogari; birinchi oʻquv laboratoriyasi; agrokimyo va mineral oʻgʻitlar; Libix sovutgichi.',
  },
  {
    id: 'wurtz',
    keywords: ['вюрц', 'wurtz', 'реакция вюрца'],
    ru: 'Шарль Адольф Вюрц (1817–1884) — французский химик. Открыл **реакцию Вюрца** (1855): при действии натрия на галогеналканы образуются алканы с удлинённой углеродной цепью. Получил этиленгликоль и первые амины, был учителем многих химиков Европы. В школьном курсе — способы получения алканов (10 класс).',
    en: 'Charles Adolphe Wurtz (1817–1884) — French chemist; Wurtz reaction (1855) — alkanes from haloalkanes and sodium; ethylene glycol; amines.',
    uz: 'Sharl Adolf Vyurs (1817–1884) — fransuz kimyogari; Vyurs reaksiyasi (1855): galogenalkan va natriydan alkanlar.',
  },
  {
    id: 'fischer',
    keywords: ['фишер', 'эмиль фишер', 'emil fischer', 'fischer', 'проекция фишера'],
    ru: 'Эмиль Фишер (1852–1919) — немецкий химик-органик. Установил строение глюкозы и других **сахаров**, синтезировал их, изучил пурины и белки (пептидная связь), предложил проекционные формулы Фишера. Нобелевская премия по химии 1902 года. Образ работы фермента с субстратом описал как «ключ и замок». В школьном курсе — углеводы, белки (10 класс).',
    en: 'Emil Fischer (1852–1919) — German organic chemist; structure of sugars, purines, peptides; Fischer projections; Nobel Prize 1902; “lock and key”.',
    uz: 'Emil Fisher (1852–1919) — nemis organik kimyogari; qandlar va oqsillar tuzilishi; Fisher proyeksiyasi; 1902-yil Nobel mukofoti.',
  },
  {
    id: 'ramsay',
    keywords: ['рамзай', 'рэмзи', 'ramsay', 'благородные газы', 'инертные газы'],
    ru: 'Уильям Рамзай (1852–1916) — шотландский химик. Открыл **благородные газы**: аргон (1894, вместе с Рэлеем), гелий на Земле (1895), неон, криптон и ксенон (1898) — целую новую группу Периодической таблицы. Нобелевская премия по химии 1904 года. Говорил, что открытия пришли из «несовпадения в третьем знаке» плотности азота. В школьном курсе — VIII группа, строение атома (8 класс).',
    en: 'William Ramsay (1852–1916) — Scottish chemist; discovered the noble gases argon, helium (on Earth), neon, krypton, xenon; Nobel Prize 1904.',
    uz: 'Uilyam Ramzay (1852–1916) — shotland kimyogari; nodir gazlarni (argon, geliy, neon, kripton, ksenon) kashf etgan; 1904-yil Nobel mukofoti.',
  },
  {
    id: 'hahn',
    keywords: ['ган', 'отто ган', 'otto hahn', 'hahn', 'деление ядра', 'деление урана'],
    ru: 'Отто Ган (1879–1968) — немецкий радиохимик. В 1938 году вместе с Фрицем Штрассманом обнаружил, что при облучении урана нейтронами образуется барий — это было **деление атомного ядра**, физическое объяснение которому дала Лиза Мейтнер. Нобелевская премия по химии 1944 года. После войны выступал против ядерного оружия. В школьном курсе — ядерные реакции, изотопы (8 и 11 класс).',
    en: 'Otto Hahn (1879–1968) — German radiochemist; discovered nuclear fission of uranium (1938, with Strassmann; explained by Meitner); Nobel Prize 1944.',
    uz: 'Otto Gan (1879–1968) — nemis radiokimyogari; uran yadrosining boʻlinishini kashf etgan (1938); 1944-yil Nobel mukofoti.',
  },
  {
    id: 'seaborg',
    keywords: ['сиборг', 'seaborg', 'плутоний', 'трансурановые'],
    ru: 'Гленн Сиборг (1912–1999) — американский химик. Участвовал в открытии **плутония** и ещё девяти трансурановых элементов, предложил выделить актиноиды в отдельный ряд Периодической таблицы. Нобелевская премия по химии 1951 года. Единственный человек, при жизни которого элемент назвали его именем — сиборгий (№106). В школьном курсе — структура Периодической таблицы (8 класс).',
    en: 'Glenn Seaborg (1912–1999) — American chemist; co-discovered plutonium and nine transuranium elements; actinide concept; Nobel Prize 1951; seaborgium.',
    uz: 'Glenn Siborg (1912–1999) — amerikalik kimyogari; plutoniy va transuran elementlar; aktinoidlar qatori; 1951-yil Nobel mukofoti.',
  },
  {
    id: 'lewis',
    keywords: ['льюис', 'lewis', 'структура льюиса', 'электронная пара'],
    ru: 'Гилберт Ньютон Льюис (1875–1946) — американский физикохимик. В 1916 году объяснил **ковалентную связь** как общую электронную пару и ввёл электронные (точечные) формулы Льюиса, которыми до сих пор пользуются школьники. Предложил электронную теорию кислот и оснований (кислота Льюиса — акцептор пары электронов), получил тяжёлую воду. Нобелевскую премию так и не получил, хотя номинировался десятки раз. В школьном курсе — виды химической связи (8 класс).',
    en: 'Gilbert N. Lewis (1875–1946) — American chemist; covalent bond as a shared electron pair (1916); Lewis structures; Lewis acids and bases.',
    uz: 'Gilbert Lyuis (1875–1946) — amerikalik kimyogari; kovalent bogʻ — umumiy elektron juft (1916); Lyuis formulalari; Lyuis kislota-asoslari.',
  },
  {
    id: 'bronsted',
    keywords: ['брёнстед', 'бренстед', 'bronsted', 'brønsted', 'лоури', 'протонная теория'],
    ru: 'Йоханнес Брёнстед (1879–1947) — датский физикохимик. В 1923 году (одновременно с англичанином Томасом Лоури) предложил **протонную теорию кислот и оснований**: кислота — донор протона H⁺, основание — его акцептор. Теория объяснила кислотные свойства ионов и поведение веществ в неводных растворах. В школьном курсе — кислоты и основания, гидролиз (9 и 11 класс).',
    en: 'Johannes Brønsted (1879–1947) — Danish chemist; protonic theory of acids and bases (1923, independently with Lowry).',
    uz: 'Yoxannes Bryonsted (1879–1947) — daniyalik kimyogari; kislota va asoslarning proton nazariyasi (1923, Louri bilan birga).',
  },
  {
    id: 'cannizzaro',
    keywords: ['канниццаро', 'cannizzaro', 'конгресс в карлсруэ'],
    ru: 'Станислао Канниццаро (1826–1910) — итальянский химик. На первом международном съезде химиков в Карлсруэ (1860) убедил коллег принять закон Авогадро и чётко различать **атом и молекулу**, что дало верные атомные массы — без этого Менделеев не смог бы построить таблицу. Открыл реакцию Канниццаро для альдегидов. Участвовал в походах Гарибальди. В школьном курсе — атомно-молекулярное учение (7 класс).',
    en: 'Stanislao Cannizzaro (1826–1910) — Italian chemist; Karlsruhe Congress (1860): atoms vs molecules, correct atomic masses; Cannizzaro reaction.',
    uz: 'Stanislao Kannitsaro (1826–1910) — italyan kimyogari; Karlsrue syezdi (1860): atom va molekula farqi, toʻgʻri atom massalari.',
  },
  {
    id: 'werner',
    keywords: ['вернер', 'альфред вернер', 'werner', 'комплексные соединения', 'координационная теория'],
    ru: 'Альфред Вернер (1866–1919) — швейцарский химик. Создал **координационную теорию** комплексных соединений (1893): центральный атом окружён лигандами, число которых — координационное число. Нобелевская премия по химии 1913 года — первая по неорганической химии. Идея теории, по его словам, пришла ему во сне. В школьном курсе — комплексные соединения, амфотерность (9 и 11 класс).',
    en: 'Alfred Werner (1866–1919) — Swiss chemist; coordination theory of complex compounds (1893); Nobel Prize 1913.',
    uz: 'Alfred Verner (1866–1919) — shveysariyalik kimyogari; kompleks birikmalarning koordinatsion nazariyasi (1893); 1913-yil Nobel mukofoti.',
  },
  {
    id: 'staudinger',
    keywords: ['штаудингер', 'staudinger', 'макромолекулы', 'полимеры'],
    ru: 'Герман Штаудингер (1881–1965) — немецкий химик, основоположник химии полимеров. Доказал, что каучук, целлюлоза и пластмассы состоят из **макромолекул** — длинных цепей, связанных обычными ковалентными связями, а не из скоплений малых молекул. Коллеги долго смеялись над «гигантскими молекулами», но Нобелевская премия 1953 года подтвердила его правоту. В школьном курсе — высокомолекулярные соединения (10–11 класс).',
    en: 'Hermann Staudinger (1881–1965) — German chemist; concept of macromolecules (polymers); Nobel Prize 1953.',
    uz: 'German Shtaudinger (1881–1965) — nemis kimyogari; makromolekulalar (polimerlar) tushunchasi; 1953-yil Nobel mukofoti.',
  },
  {
    id: 'carothers',
    keywords: ['карозерс', 'carothers', 'нейлон', 'неопрен'],
    ru: 'Уоллес Карозерс (1896–1937) — американский химик, работал в фирме DuPont. Получил первый синтетический каучук неопрен и в 1935 году — **нейлон**, первое полностью синтетическое волокно, из которого вскоре начали делать чулки и парашюты. Разработал теорию поликонденсации. В школьном курсе — синтетические волокна и реакции поликонденсации (10–11 класс).',
    en: 'Wallace Carothers (1896–1937) — American chemist at DuPont; neoprene and nylon (1935), the first fully synthetic fibre; polycondensation.',
    uz: 'Uolles Karozers (1896–1937) — amerikalik kimyogari; neopren va neylon (1935) — birinchi sintetik tola; polikondensatsiya.',
  },
  {
    id: 'baekeland',
    keywords: ['бакеланд', 'baekeland', 'бакелит', 'первая пластмасса'],
    ru: 'Лео Бакеланд (1863–1944) — бельгийско-американский химик. В 1907 году получил **бакелит** — первую полностью синтетическую пластмассу — из фенола и формальдегида; из неё делали телефоны, розетки, радиоприёмники. До этого изобрёл фотобумагу «Велокс» и продал её Кодаку. С бакелита принято отсчитывать «век пластмасс». В школьном курсе — фенолформальдегидные смолы (10 класс).',
    en: 'Leo Baekeland (1863–1944) — Belgian-American chemist; Bakelite (1907), the first fully synthetic plastic, from phenol and formaldehyde.',
    uz: 'Leo Bakeland (1863–1944) — belgiyalik-amerikalik kimyogari; bakelit (1907) — fenol va formaldegiddan birinchi sintetik plastmassa.',
  },
  {
    id: 'hodgkin',
    keywords: ['ходжкин', 'hodgkin', 'рентгеноструктурный анализ', 'пенициллин строение', 'витамин b12'],
    ru: 'Дороти Ходжкин (1910–1994) — британский химик. Методом **рентгеноструктурного анализа** установила строение пенициллина, витамина B₁₂ и инсулина. Нобелевская премия по химии 1964 года. Работала, несмотря на тяжёлый артрит рук с юности. В школьном курсе — кристаллические решётки и методы исследования веществ (8 и 11 класс).',
    en: 'Dorothy Hodgkin (1910–1994) — British chemist; X-ray structures of penicillin, vitamin B₁₂ and insulin; Nobel Prize 1964.',
    uz: 'Doroti Xodjkin (1910–1994) — britaniyalik kimyogari; penitsillin, B₁₂ vitamini va insulinning rentgen tuzilishi; 1964-yil Nobel mukofoti.',
  },
  {
    id: 'soddy',
    keywords: ['содди', 'soddy', 'изотопы'],
    ru: 'Фредерик Содди (1877–1956) — английский радиохимик. Вместе с Резерфордом объяснил радиоактивность как превращение одних элементов в другие, ввёл понятие **изотопов** (1913) — атомов одного элемента с разной массой. Нобелевская премия по химии 1921 года. Позже отошёл от науки и занимался экономикой. В школьном курсе — изотопы, строение атома (8 класс).',
    en: 'Frederick Soddy (1877–1956) — English radiochemist; radioactive transmutation; concept of isotopes (1913); Nobel Prize 1921.',
    uz: 'Frederik Soddi (1877–1956) — ingliz radiokimyogari; izotoplar tushunchasi (1913); 1921-yil Nobel mukofoti.',
  },
  {
    id: 'becquerel',
    keywords: ['беккерель', 'becquerel'],
    ru: 'Анри Беккерель (1852–1908) — французский физик. В 1896 году случайно обнаружил, что соли урана засвечивают фотопластинку даже в темноте, — так была открыта **радиоактивность**. Нобелевская премия по физике 1903 года вместе с Пьером и Марией Кюри. Его именем названа единица активности — беккерель. В школьном курсе — радиоактивность и строение атома (8 класс).',
    en: 'Henri Becquerel (1852–1908) — French physicist; discovered radioactivity of uranium salts (1896); Nobel Prize 1903 with the Curies.',
    uz: 'Anri Bekkerel (1852–1908) — fransuz fizigi; uran tuzlarining radioaktivligini kashf etgan (1896); 1903-yil Nobel mukofoti.',
  },
  {
    id: 'volta',
    keywords: ['вольта', 'volta', 'вольтов столб', 'первая батарейка'],
    ru: 'Алессандро Вольта (1745–1827) — итальянский физик. В 1800 году собрал **вольтов столб** — первый химический источник тока из пластинок цинка и меди, разделённых тканью с раствором соли. Так появилась батарейка, а вскоре с помощью тока Дэви выделил натрий и калий. Единица напряжения вольт названа в его честь. В школьном курсе — гальванический элемент, электролиз (9 и 11 класс).',
    en: 'Alessandro Volta (1745–1827) — Italian physicist; voltaic pile (1800), the first chemical battery of zinc and copper discs.',
    uz: 'Alessandro Volta (1745–1827) — italyan fizigi; Volta ustuni (1800) — rux va misdan birinchi kimyoviy tok manbai.',
  },
  {
    id: 'kirchhoff',
    keywords: ['кирхгоф', 'kirchhoff', 'спектральный анализ'],
    ru: 'Густав Кирхгоф (1824–1887) — немецкий физик. Вместе с Бунзеном создал **спектральный анализ** (1859): каждый элемент даёт свой набор линий в спектре пламени. Этим методом они открыли цезий и рубидий, а позже по спектрам нашли гелий на Солнце. В школьном курсе — окрашивание пламени солями металлов, качественный анализ (9 класс).',
    en: 'Gustav Kirchhoff (1824–1887) — German physicist; spectral analysis with Bunsen (1859); discovered caesium and rubidium.',
    uz: 'Gustav Kirxgof (1824–1887) — nemis fizigi; Bunzen bilan spektral tahlil (1859); seziy va rubidiyni kashf etgan.',
  },
  {
    id: 'tsvet',
    keywords: ['цвет', 'михаил цвет', 'tsvet', 'tswett', 'хроматография'],
    ru: 'Михаил Семёнович Цвет (1872–1919) — русский ботаник и биохимик. В 1903 году изобрёл **хроматографию**: пропуская экстракт листьев через трубку с мелом, разделил зелёные и жёлтые пигменты растений на цветные полосы. Сегодня хроматография — главный метод разделения и анализа смесей в химии и медицине. Фамилия учёного и «цветной» метод совпали случайно. В школьном курсе — способы разделения смесей (7 класс).',
    en: 'Mikhail Tsvet (1872–1919) — Russian botanist; invented chromatography (1903) by separating leaf pigments on a chalk column.',
    uz: 'Mixail Svet (1872–1919) — rus botanigi; xromatografiyani ixtiro qilgan (1903) — barg pigmentlarini boʻr ustunida ajratgan.',
  },
  {
    id: 'meyer',
    keywords: ['лотар мейер', 'мейер', 'lothar meyer', 'meyer'],
    ru: 'Юлиус Лотар Мейер (1830–1895) — немецкий химик. Независимо от Менделеева составил таблицу элементов и в 1870 году опубликовал кривую зависимости **атомного объёма от атомной массы**, наглядно показавшую периодичность. В отличие от Менделеева, не решился предсказывать новые элементы. В школьном курсе — история открытия Периодического закона (8 класс).',
    en: 'Lothar Meyer (1830–1895) — German chemist; independent periodic table; atomic volume curve (1870) showing periodicity.',
    uz: 'Lotar Meyer (1830–1895) — nemis kimyogari; mustaqil davriy jadval; atom hajmi egri chizigʻi (1870).',
  },
  {
    id: 'vanderwaals',
    keywords: ['ван-дер-ваальс', 'ван дер ваальс', 'van der waals', 'межмолекулярные силы'],
    ru: 'Ян Дидерик Ван-дер-Ваальс (1837–1923) — нидерландский физик. Вывел уравнение состояния реального газа, учитывающее объём молекул и **силы притяжения между ними** — силы Ван-дер-Ваальса. Нобелевская премия по физике 1910 года. Начинал школьным учителем и получил степень только в 36 лет. В школьном курсе — межмолекулярное взаимодействие, агрегатные состояния (8 и 11 класс).',
    en: 'Johannes van der Waals (1837–1923) — Dutch physicist; equation of state for real gases; intermolecular (van der Waals) forces; Nobel Prize 1910.',
    uz: 'Yan van der Vaals (1837–1923) — niderland fizigi; real gazlar holat tenglamasi; molekulalararo kuchlar; 1910-yil Nobel mukofoti.',
  },
  {
    id: 'black',
    keywords: ['джозеф блэк', 'блэк', 'joseph black', 'углекислый газ открыл'],
    ru: 'Джозеф Блэк (1728–1799) — шотландский химик и врач. Открыл **углекислый газ** («связанный воздух», 1754), показав, что он выделяется при прокаливании и растворении карбонатов, и ввёл в химию точное взвешивание. Открыл скрытую теплоту плавления и испарения. Его учеником был Джеймс Уатт. В школьном курсе — оксид углерода(IV), карбонаты (9 класс).',
    en: 'Joseph Black (1728–1799) — Scottish chemist; discovered carbon dioxide (“fixed air”, 1754); latent heat; quantitative weighing.',
    uz: 'Jozef Blek (1728–1799) — shotland kimyogari; karbonat angidridni kashf etgan (1754); yashirin issiqlik.',
  },
  {
    id: 'solvay',
    keywords: ['сольве', 'solvay', 'аммиачный способ', 'производство соды'],
    ru: 'Эрнест Сольве (1838–1922) — бельгийский химик-промышленник. В 1861–1865 годах разработал **аммиачный способ получения соды** Na₂CO₃ из поваренной соли, аммиака и углекислого газа, вытеснивший старый способ Леблана и применяемый до сих пор. На доходы основал международные Сольвеевские конгрессы, собиравшие Эйнштейна, Кюри и Бора. В школьном курсе — производство соды, карбонаты (9 класс).',
    en: 'Ernest Solvay (1838–1922) — Belgian industrial chemist; ammonia-soda (Solvay) process for Na₂CO₃ (1860s); Solvay conferences.',
    uz: 'Ernest Solve (1838–1922) — belgiyalik kimyogar-sanoatchi; soda olishning ammiakli usuli (1860-yillar); Solve kongresslari.',
  },
  {
    id: 'goodyear',
    keywords: ['гудьир', 'goodyear', 'вулканизация'],
    ru: 'Чарльз Гудьир (1800–1860) — американский изобретатель. В 1839 году открыл **вулканизацию**: при нагревании каучука с серой получается резина, которая не липнет в жару и не трескается на морозе. Годами экспериментировал в бедности, сидел в долговой тюрьме, но благодаря ему появились шины и резиновая обувь. В школьном курсе — каучук и резина (10 класс).',
    en: 'Charles Goodyear (1800–1860) — American inventor; vulcanisation of rubber with sulfur (1839).',
    uz: 'Charlz Gudyir (1800–1860) — amerikalik ixtirochi; kauchukni oltingugurt bilan vulkanlash (1839).',
  },
  {
    id: 'fleming',
    keywords: ['флеминг', 'fleming', 'пенициллин'],
    ru: 'Александр Флеминг (1881–1955) — шотландский микробиолог. В 1928 году заметил, что плесень Penicillium убивает бактерии в забытой чашке Петри, и открыл **пенициллин** — первый антибиотик. Выделить и наладить производство вещества удалось позже Флори и Чейну; Нобелевская премия по медицине 1945 года — на троих. В школьном курсе — лекарственные вещества (10–11 класс).',
    en: 'Alexander Fleming (1881–1955) — Scottish microbiologist; discovered penicillin (1928), the first antibiotic; Nobel Prize 1945.',
    uz: 'Aleksandr Fleming (1881–1955) — shotland mikrobiologi; penitsillinni kashf etgan (1928) — birinchi antibiotik; 1945-yil Nobel mukofoti.',
  },
  {
    id: 'sanger',
    keywords: ['сенгер', 'сэнгер', 'sanger', 'секвенирование', 'строение инсулина'],
    ru: 'Фредерик Сенгер (1918–2013) — английский биохимик, один из немногих **дважды лауреатов Нобелевской премии по химии**: в 1958 году — за установление последовательности аминокислот в инсулине, в 1980 году — за метод чтения последовательности ДНК. Его методами расшифрован геном человека. Отказался от рыцарского звания, чтобы к нему не обращались «сэр». В школьном курсе — белки и нуклеиновые кислоты (10–11 класс).',
    en: 'Frederick Sanger (1918–2013) — English biochemist; two Nobel Prizes in Chemistry: insulin sequence (1958) and DNA sequencing (1980).',
    uz: 'Frederik Senger (1918–2013) — ingliz bioximigi; ikki marta Nobel mukofoti: insulin ketma-ketligi (1958), DNK sekvenirlash (1980).',
  },
  {
    id: 'franklin',
    keywords: ['розалинд франклин', 'франклин', 'rosalind franklin', 'franklin', 'структура днк'],
    ru: 'Розалинд Франклин (1920–1958) — британский химик и кристаллограф. Её рентгенограммы ДНК (знаменитая «фотография 51», 1952) показали **двойную спираль** и стали ключом к модели Уотсона и Крика. Также изучала строение угля и вирусов. Умерла в 37 лет, до присуждения Нобелевской премии за структуру ДНК. В школьном курсе — нуклеиновые кислоты (10–11 класс).',
    en: 'Rosalind Franklin (1920–1958) — British chemist; X-ray photographs of DNA (“Photo 51”, 1952) revealed the double helix.',
    uz: 'Rozalind Franklin (1920–1958) — britaniyalik kimyogari; DNKning rentgen suratlari (1952) qoʻsh spiralni koʻrsatgan.',
  },
  {
    id: 'oganessian',
    keywords: ['оганесян', 'oganessian', 'оганесон', 'сверхтяжёлые элементы'],
    ru: 'Юрий Цолакович Оганесян (род. 1933) — советский и российский физик-ядерщик, руководитель лаборатории в Дубне. Под его руководством синтезированы **сверхтяжёлые элементы** Периодической таблицы (с 113 по 118). Элемент №118 — оганесон — назван в его честь при жизни, как ранее только сиборгий. В школьном курсе — Периодическая таблица, ядерные реакции (8 и 11 класс).',
    en: 'Yuri Oganessian (b. 1933) — nuclear physicist at Dubna; synthesis of superheavy elements 113–118; oganesson (118) is named after him.',
    uz: 'Yuriy Oganesyan (1933-yilda tugʻilgan) — Dubna yadro fizigi; 113–118 oʻta ogʻir elementlar sintezi; oganesson uning nomida.',
  },
  {
    id: 'sadykov',
    keywords: ['садыков', 'абид садыков', 'sadykov', 'sodiqov', 'obid sodiqov', 'алкалоиды хлопчатника', 'химики узбекистана'],
    ru: 'Абид Садыкович Садыков (1913–1987) — узбекский химик-органик, академик, президент Академии наук Узбекистана (1966–1984). Изучал **алкалоиды** и другие природные соединения растений Средней Азии, в том числе хлопчатника, разработал на их основе лекарственные препараты. Создал в Ташкенте научную школу биоорганической химии; его имя носит Институт биоорганической химии АН Узбекистана. В школьном курсе — азотсодержащие органические соединения, химия Узбекистана (10–11 класс).',
    en: 'Obid Sodiqov (1913–1987) — Uzbek organic chemist, president of the Uzbek Academy of Sciences (1966–1984); alkaloids and natural compounds of Central Asian plants.',
    uz: 'Obid Sodiqov (1913–1987) — oʻzbek organik kimyogari, Oʻzbekiston Fanlar akademiyasi prezidenti (1966–1984); Oʻrta Osiyo oʻsimliklari alkaloidlari va tabiiy birikmalari.',
  },
  {
    id: 'yunusov',
    keywords: ['юнусов', 'сабир юнусов', 'yunusov', 'sobir yunusov', 'алкалоиды'],
    ru: 'Сабир Юнусович Юнусов (1909–1995) — узбекский химик, академик, основатель Института химии растительных веществ в Ташкенте. Выделил и изучил сотни **алкалоидов** из растений Средней Азии; на их основе созданы лекарства. Создал одну из крупнейших в мире школ химии природных соединений. В школьном курсе — природные органические вещества, химическая промышленность Узбекистана (10–11 класс).',
    en: 'Sobir Yunusov (1909–1995) — Uzbek chemist; founded the Institute of the Chemistry of Plant Substances in Tashkent; hundreds of alkaloids from Central Asian plants.',
    uz: 'Sobir Yunusov (1909–1995) — oʻzbek kimyogari; Toshkentdagi Oʻsimlik moddalari kimyosi institutini asoslagan; Oʻrta Osiyo oʻsimliklaridan yuzlab alkaloidlar.',
  },
  {
    id: 'khorezmi',
    keywords: ['хорезми', 'аль-хорезми', 'al-khwarizmi', 'xorazmiy', 'muhammad al-xorazmiy'],
    ru: 'Мухаммад ибн Муса аль-Хорезми (ок. 783–850) — учёный из Хорезма, работал в багдадском «Доме мудрости». Основатель **алгебры** (от названия его труда «Аль-джабр»); от латинской формы его имени произошло слово «алгоритм». Составил астрономические и географические таблицы. Для химика его наследие — точный расчёт: без алгебры не решить ни одной задачи на уравнение реакции. В школьном курсе — расчёты по уравнениям (7–8 класс).',
    en: 'Muhammad al-Khwarizmi (c. 783–850) — scholar from Khorezm; founder of algebra; the word “algorithm” comes from his name.',
    uz: 'Muhammad al-Xorazmiy (taxminan 783–850) — xorazmlik olim; algebra asoschisi; «algoritm» soʻzi uning nomidan.',
  },
  {
    id: 'ulugbek',
    keywords: ['улугбек', 'ulugbek', "ulug'bek", 'мирзо улугбек'],
    ru: 'Мирзо Улугбек (1394–1449) — правитель и учёный из Самарканда, внук Тимура. Построил крупнейшую обсерваторию своего времени и составил **звёздный каталог** более чем на тысячу звёзд с точностью, непревзойдённой до изобретения телескопа; измерил длину года с ошибкой меньше минуты. Открывал медресе, где преподавали естественные науки. Пример того, как точные измерения и честная фиксация данных — основа любой науки, включая химию.',
    en: 'Mirzo Ulugbek (1394–1449) — Samarkand ruler and astronomer; great observatory and a star catalogue of over a thousand stars; founded madrasas teaching science.',
    uz: 'Mirzo Ulugʻbek (1394–1449) — samarqandlik hukmdor va olim; buyuk rasadxona va mingdan ortiq yulduz katalogi; fan oʻqitiladigan madrasalar.',
  },
]

const DISPLAY_NAME: Record<string, string> = {
  mendeleev: 'Д. И. Менделеев',
  lavoisier: 'Антуан Лавуазье',
  lomonosov: 'М. В. Ломоносов',
  dalton: 'Джон Дальтон',
  avogadro: 'Амедео Авогадро',
  rutherford: 'Эрнест Резерфорд',
  bohr: 'Нильс Бор',
  curie: 'Мария Кюри',
  boyle: 'Роберт Бойль',
  arrhenius: 'Сванте Аррениус',
  'ibn-sina': 'Ибн Сина (Авиценна)',
  'al-biruni': 'Абу Райхан Беруни',
  jabir: 'Джабир ибн Хайян',
  'ar-razi': 'Ар-Рази',
  'al-kindi': 'Аль-Кинди',
  butlerov: 'А. М. Бутлеров',
  faraday: 'Майкл Фарадей',
  thomson: 'Дж. Дж. Томсон',
  chadwick: 'Джеймс Чедвик',
  berzelius: 'Йёнс Якоб Берцелиус',
  gaylussac: 'Жозеф Гей-Люссак',
  proust: 'Жозеф Пруст',
  lechatelier: 'Анри Ле Шателье',
  pauling: 'Лайнус Полинг',
  nobel: 'Альфред Нобель',
  zelinsky: 'Н. Д. Зелинский',
  markovnikov: 'Владимир Марковников',
  kekule: 'Фридрих Кекуле',
  wohler: 'Фридрих Вёлер',
  priestley: 'Джозеф Пристли',
  davy: 'Гемфри Дэви',
  bunsen: 'Роберт Бунзен',
  moseley: 'Генри Мозли',
  butlerov2: 'Николай Зинин',
  berthollet: 'Клод Бертолле',
  kurchatov: 'Игорь Курчатов',
  scheele: 'Карл Вильгельм Шееле',
  cavendish: 'Генри Кавендиш',
  hess: 'Г. И. Гесс',
  zaitsev: 'А. М. Зайцев',
  lebedev: 'С. В. Лебедев',
  semenov: 'Н. Н. Семёнов',
  haber: 'Фриц Габер',
  bosch: 'Карл Бош',
  ostwald: 'Вильгельм Оствальд',
  vanthoff: 'Якоб Вант-Гофф',
  nernst: 'Вальтер Нернст',
  gibbs: 'Джозайя Уиллард Гиббс',
  pasteur: 'Луи Пастер',
  liebig: 'Юстус Либих',
  wurtz: 'Шарль Адольф Вюрц',
  fischer: 'Эмиль Фишер',
  ramsay: 'Уильям Рамзай',
  hahn: 'Отто Ган',
  seaborg: 'Гленн Сиборг',
  lewis: 'Гилберт Льюис',
  bronsted: 'Йоханнес Брёнстед',
  cannizzaro: 'Станислао Канниццаро',
  werner: 'Альфред Вернер',
  staudinger: 'Герман Штаудингер',
  carothers: 'Уоллес Карозерс',
  baekeland: 'Лео Бакеланд',
  hodgkin: 'Дороти Ходжкин',
  soddy: 'Фредерик Содди',
  becquerel: 'Анри Беккерель',
  volta: 'Алессандро Вольта',
  kirchhoff: 'Густав Кирхгоф',
  tsvet: 'М. С. Цвет',
  meyer: 'Лотар Мейер',
  vanderwaals: 'Ян Ван-дер-Ваальс',
  black: 'Джозеф Блэк',
  solvay: 'Эрнест Сольве',
  goodyear: 'Чарльз Гудьир',
  fleming: 'Александр Флеминг',
  sanger: 'Фредерик Сенгер',
  franklin: 'Розалинд Франклин',
  oganessian: 'Ю. Ц. Оганесян',
  sadykov: 'Абид Садыков (Obid Sodiqov)',
  yunusov: 'Сабир Юнусов (Sobir Yunusov)',
  khorezmi: 'Аль-Хорезми',
  ulugbek: 'Мирзо Улугбек',
}

/** Записи и отображаемые имена — для быстрого ответа «об учёном» (src/learn/brain/human/scientistTalk.ts). */
export const SCIENTIST_ENTRIES: readonly ScientistEntry[] = SCIENTISTS
export const SCIENTIST_DISPLAY_NAME: Readonly<Record<string, string>> = DISPLAY_NAME

export const SCIENTISTS_KNOWLEDGE: ChemistryKnowledgeChunk[] = SCIENTISTS.map((s) => ({
  id: `sci-${s.id}`,
  topic: DISPLAY_NAME[s.id] ?? `Учёный: ${s.keywords[0]}`,
  grades: [7, 8, 9, 10, 11],
  keywords: [...s.keywords, 'учёный', 'химик', 'кто такой', 'вклад', 'открыл', 'scientist'],
  ru: s.ru,
  en: s.en,
}))
