import type { ChemistryKnowledgeChunk } from './learnChemistryKnowledgeBase'

/**
 * Расширенный педагогический «мозг» учителя: алгоритмы, аналогии,
 * экзаменационные формулировки, работа с ошибками (7–11 класс).
 */
export const CHEMISTRY_KNOWLEDGE_BRAIN_MEGA: ChemistryKnowledgeChunk[] = [
  {
    id: 'brain2-socratic-loop',
    topic: 'Сократический цикл на уроке',
    grades: [7, 8, 9, 10, 11],
    keywords: ['вопрос', 'почему', 'объясн', 'учитель', 'диалог'],
    ru: `Цикл сильного учителя: 1) короткий вопрос; 2) пауза; 3) переформулировка ответа ученика; 4) уточнение «почему»; 5) мини-пример; 6) проверка одним шагом. Не читайте лекцию сразу — сначала вытяните мысль ученика.`,
    en: `Socratic loop: ask → wait → rephrase → why → example → check.`,
  },
  {
    id: 'brain2-hint-ladder',
    topic: 'Лестница подсказок',
    grades: [7, 8, 9, 10, 11],
    keywords: ['подсказк', 'hint', 'помощь', 'не подсказывай ответ'],
    ru: `Уровень 0: только вопрос. 1: укажите тему/формулу-имя. 2: дайте первый шаг. 3: разберите половину. 4: полный разбор + попросите повторить. На экзамене не поднимайтесь выше 1 без правила режима.`,
    en: `Hint ladder 0–4: from question-only to full worked example.`,
  },
  {
    id: 'brain2-error-praise',
    topic: 'Ошибка как ресурс',
    grades: [7, 8, 9, 10, 11],
    keywords: ['ошибк', 'неправильн', 'фрустрац', 'поддерж'],
    ru: `Сначала признайте усилие, затем назовите тип ошибки (термин / расчёт / логика), затем дайте один корректирующий шаг. Не говорите «совсем неверно» без указания, что уже близко.`,
    en: `Praise effort, name error type, give one corrective step.`,
  },
  {
    id: 'brain2-units-check',
    topic: 'Проверка единиц',
    grades: [8, 9, 10, 11],
    keywords: ['единиц', 'г/моль', 'литр', 'размерност'],
    ru: `В конце любой задачи: единицы согласованы? Порядок величины разумный? Если n получилось 10³ моль для пробирки — ошибка в степенях/переводе.`,
    en: `Always check units and order of magnitude.`,
  },
  {
    id: 'brain2-equation-first',
    topic: 'Сначала уравнение',
    grades: [8, 9, 10],
    keywords: ['уравнен', 'стехиометр', 'коэффициент'],
    ru: `Правило: пока уравнение не записано и не уравнено — не считайте массы. 80% ошибок в задачах — из пропуска этого шага.`,
    en: `Never compute stoichiometry before a balanced equation.`,
  },
  {
    id: 'brain2-table-solubility',
    topic: 'Таблица растворимости как рефлекс',
    grades: [9, 10],
    keywords: ['растворим', 'осадок', 'таблица'],
    ru: `При ионном обмене первым делом откройте таблицу растворимости. Без неё нельзя честно написать осадок и сокращённое ионное.`,
    en: `Solubility table first for ion-exchange problems.`,
  },
  {
    id: 'brain2-ox-state-ritual',
    topic: 'Ритуал степеней окисления',
    grades: [9, 10, 11],
    keywords: ['степень окислен', 'овр', 'ритуал'],
    ru: `Всегда: H обычно +1, O обычно −2, сумма = 0 (или заряд иона). Исключения проговаривайте вслух (пероксиды, гидриды).`,
    en: `Oxidation-state ritual: H +1, O −2, sum to charge.`,
  },
  {
    id: 'brain2-organic-draw',
    topic: 'Сначала структурная формула',
    grades: [10, 11],
    keywords: ['структурн', 'орган', 'изомер'],
    ru: `В органике требуйте нарисовать скелет до названия и реакций. Устно «C2H5OH» без рисунка плодит изомерные ошибки.`,
    en: `Draw the structure before naming or predicting organic reactions.`,
  },
  {
    id: 'brain2-lab-observe',
    topic: 'Наблюдение ≠ вывод',
    grades: [7, 8, 9],
    keywords: ['наблюден', 'вывод', 'опыт'],
    ru: `Наблюдение: «выпал голубой осадок». Вывод: «образовался Cu(OH)₂». Учите разделять эти фразы — это база научного стиля.`,
    en: `Separate observation from conclusion in lab write-ups.`,
  },
  {
    id: 'brain2-compare-template',
    topic: 'Шаблон сравнения',
    grades: [8, 9, 10, 11],
    keywords: ['сравн', 'отличи', 'чем отличается'],
    ru: `Сравнение в 4 строки: определение А; определение Б; общий признак; ключевое отличие + пример. Так отвечают на «чем отличается» на ОГЭ/ЕГЭ.`,
    en: `Compare in four lines: A, B, shared trait, key difference + example.`,
  },
  {
    id: 'brain2-energy-words',
    topic: 'Слова энергии',
    grades: [9, 10, 11],
    keywords: ['экзо', 'эндо', 'тепло', 'энтальп'],
    ru: `Экзо — тепло наружу (горит, нейтрализация часто). Эндо — тепло внутрь (разложение многих карбонатов). Знак ΔH проговаривайте словами.`,
    en: `Exo releases heat; endo absorbs heat. Say ΔH in words.`,
  },
  {
    id: 'brain2-equilibrium-story',
    topic: 'Равновесие как история',
    grades: [10, 11],
    keywords: ['равновес', 'ле шателье', 'смещен'],
    ru: `Расскажите: система «не хочет» изменения. Добавили реагент — «съедает» его прямой реакцией. Сжали газ — смещается туда, где меньше моль газа.`,
    en: `Le Chatelier as a story: the system opposes the change.`,
  },
  {
    id: 'brain2-safety-acid',
    topic: 'Кислоту в воду',
    grades: [7, 8, 9],
    keywords: ['кислот', 'разбавлен', 'безопас', 'вода'],
    ru: `Правило: кислоту тонкой струёй в воду при перемешивании, не наоборот. Иначе локальный перегрев и разбрызгивание.`,
    en: `Always add acid to water, never water to concentrated acid.`,
  },
  {
    id: 'brain2-metal-activity',
    topic: 'Ряд активности',
    grades: [8, 9],
    keywords: ['активност', 'металл', 'водород', 'замещен'],
    ru: `Металл вытесняет H₂ из кислот, если стоит левее водорода в ряду напряжений. Cu, Ag, Au — обычно нет. Помните исключения и пассивацию.`,
    en: `Metals left of hydrogen displace H₂ from acids.`,
  },
  {
    id: 'brain2-gas-tests',
    topic: 'Качественные на газы',
    grades: [8, 9],
    keywords: ['водород', 'кислород', 'углекисл', 'качественн'],
    ru: `H₂ — «хлопок» с огнём. O₂ — вспыхивает тлеющая лучинка. CO₂ — мутнеет известковая вода. Не путайте тесты.`,
    en: `Gas tests: H₂ pop, O₂ glowing splint, CO₂ limewater.`,
  },
  {
    id: 'brain2-percent-yield',
    topic: 'Выход реакции',
    grades: [9, 10, 11],
    keywords: ['выход', 'практическ', 'теоретическ'],
    ru: `η = m_практ/m_теор·100%. Сначала теоретическая масса по уравнению, потом деление. Выход >100% — сигнал ошибки взвешивания/расчёта.`,
    en: `Percent yield = practical/theoretical × 100%.`,
  },
  {
    id: 'brain2-buffer-simple',
    topic: 'Буфер простыми словами',
    grades: [11],
    keywords: ['буфер', 'ph', 'слаб кислота'],
    ru: `Буфер — смесь слабой кислоты и её соли (или слабого основания и соли). «Гасит» небольшие добавки H⁺/OH⁻, pH почти не прыгает.`,
    en: `Buffer resists pH change: weak acid + its salt.`,
  },
  {
    id: 'brain2-polymer-link',
    topic: 'Мономер ↔ полимер',
    grades: [10, 11],
    keywords: ['мономер', 'полимер', 'звено'],
    ru: `Спросите: какое повторяющееся звено? Откуда двойная связь ушла при полимеризации алкена? Без этого «полиэтилен из этилена» остаётся фразой.`,
    en: `Identify the repeating unit and what happened to the double bond.`,
  },
  {
    id: 'brain2-exam-time',
    topic: 'Тайминг ответа на экзамене',
    grades: [9, 10, 11],
    keywords: ['экзамен', 'время', 'огэ', 'егэ'],
    ru: `60 секунд устно: определение → формула/пример → один нюанс. Не начинайте с длинной истории открытия, если не просят.`,
    en: `Oral exam timing: definition → example → one nuance.`,
  },
  {
    id: 'brain2-listen-first',
    topic: 'Сначала услышать ученика',
    grades: [7, 8, 9, 10, 11],
    keywords: ['слушать', 'ответ ученика', 'перебивать'],
    ru: `Не перебивайте на полуслове. Зафиксируйте 1–2 верных куска, затем одну ошибку. Так растёт доверие и точнее диагностика.`,
    en: `Listen fully; keep two correct pieces, fix one error.`,
  },
]
