/**
 * Рукописный набор «живых» фраз ученика с опечатками и разговорными формами (RU/EN/UZ),
 * НЕ пересекающийся с шаблонами генератора. Используется для честной оценки классификатора.
 */
import type { Intent } from '../../src/learn/brain/ml/intentFeatures.ts'

export const HOLDOUT: { text: string; intent: Intent }[] = [
  // greet
  { text: 'прив', intent: 'greet' },
  { text: 'здрасьте', intent: 'greet' },
  { text: 'дароу учитель', intent: 'greet' },
  { text: 'добрый вечерок', intent: 'greet' },
  { text: 'hello there teacher!', intent: 'greet' },
  { text: 'салом алейкум', intent: 'greet' },
  // bye
  { text: 'ну всё я пошла', intent: 'bye' },
  { text: 'досвидос', intent: 'bye' },
  { text: 'спокойной ночи учитель', intent: 'bye' },
  { text: 'ok bye for now', intent: 'bye' },
  { text: 'xayr, ertaga', intent: 'bye' },
  // thanks
  { text: 'спасибо огромное!!!', intent: 'thanks' },
  { text: 'сенк ю', intent: 'thanks' },
  { text: 'благодарю вас', intent: 'thanks' },
  { text: 'thank u teacher', intent: 'thanks' },
  { text: 'katta raxmat ustoz', intent: 'thanks' },
  // how_are_you
  { text: 'как настроение сегодня?', intent: 'how_are_you' },
  { text: 'как у вас дела учитель', intent: 'how_are_you' },
  { text: 'как твои дела', intent: 'how_are_you' },
  { text: 'how r u', intent: 'how_are_you' },
  { text: 'ishlaringiz qalay ustoz', intent: 'how_are_you' },
  // joke
  { text: 'расскажи анекдот про химика', intent: 'joke' },
  { text: 'пошути пж', intent: 'joke' },
  { text: 'знаешь смешную шутку?', intent: 'joke' },
  { text: 'tell me something funny about atoms', intent: 'joke' },
  { text: 'bitta hazil ayting', intent: 'joke' },
  // about_teacher
  { text: 'ты бот или человек', intent: 'about_teacher' },
  { text: 'а что ты вообще умеешь', intent: 'about_teacher' },
  { text: 'кто тебя создал', intent: 'about_teacher' },
  { text: 'what are you exactly', intent: 'about_teacher' },
  { text: 'siz robotmisiz yoki odam', intent: 'about_teacher' },
  // offtopic
  { text: 'какая погода в самарканде завтра', intent: 'offtopic' },
  { text: 'посоветуй сериал на вечер', intent: 'offtopic' },
  { text: 'кто выиграл чемпионат мира по футболу', intent: 'offtopic' },
  { text: 'напиши сочинение про лето', intent: 'offtopic' },
  { text: 'сколько стоит новый самсунг', intent: 'offtopic' },
  { text: 'whats the capital of canada', intent: 'offtopic' },
  { text: 'futbol o‘yini kim yutdi', intent: 'offtopic' },
  // gibberish
  { text: 'ыфвафыва', intent: 'gibberish' },
  { text: 'ммм ээ', intent: 'gibberish' },
  { text: 'лорпа', intent: 'gibberish' },
  { text: 'sdfsdf', intent: 'gibberish' },
  { text: 'ъъ', intent: 'gibberish' },
  // define
  { text: 'что токое валентность', intent: 'define' },
  { text: 'а что значит моль', intent: 'define' },
  { text: 'оксиды это что вообще', intent: 'define' },
  { text: 'дай определение кислоты', intent: 'define' },
  { text: 'what does electronegativity mean', intent: 'define' },
  { text: 'tuzlar nima', intent: 'define' },
  // why
  { text: 'почему медь не реагирует с соляной кислотой', intent: 'why' },
  { text: 'а почему железо ржавеет', intent: 'why' },
  { text: 'почему кислоту льют в воду', intent: 'why' },
  { text: 'why does sodium explode in water', intent: 'why' },
  { text: 'nega natriy suvda portlaydi', intent: 'why' },
  // how
  { text: 'как получить водород в лаборатории', intent: 'how' },
  { text: 'как определить валентность серы', intent: 'how' },
  { text: 'как составлять формулы солей', intent: 'how' },
  { text: 'how to find oxidation state of Mn in KMnO4', intent: 'how' },
  { text: 'kislorod qanday olinadi', intent: 'how' },
  // compare
  { text: 'чем отличается кислота от щёлочи', intent: 'compare' },
  { text: 'в чём разница между атомом и ионом', intent: 'compare' },
  { text: 'что активнее натрий или калий', intent: 'compare' },
  { text: 'difference between ionic and covalent bond', intent: 'compare' },
  { text: 'kislota va ishqor farqi', intent: 'compare' },
  // example
  { text: 'приведи примеры оснований', intent: 'example' },
  { text: 'пример реакции обмена', intent: 'example' },
  { text: 'а можно пример из жизни', intent: 'example' },
  { text: 'give me examples of salts', intent: 'example' },
  { text: 'oksidlarga misol', intent: 'example' },
  // calc_arith
  { text: 'сколько будет 12 умножить на 11', intent: 'calc_arith' },
  { text: 'посчитай 144/12', intent: 'calc_arith' },
  { text: '25+37', intent: 'calc_arith' },
  { text: 'what is 15*4', intent: 'calc_arith' },
  { text: '48 bo‘lish 6 necha', intent: 'calc_arith' },
  // molar_mass
  { text: 'молярная маса H2SO4', intent: 'molar_mass' },
  { text: 'какая молярная масса у воды', intent: 'molar_mass' },
  { text: 'найди M(NaOH)', intent: 'molar_mass' },
  { text: 'molar mass of CaCO3', intent: 'molar_mass' },
  { text: 'suvning molyar massasi qancha', intent: 'molar_mass' },
  // moles
  { text: 'сколько моль в 36 г воды', intent: 'moles' },
  { text: 'какая масса 2 моль CO2', intent: 'moles' },
  { text: 'сколько молекул в 0,5 моль кислорода', intent: 'moles' },
  { text: 'how many moles in 44 g of CO2', intent: 'moles' },
  { text: '18 g suvda necha mol bor', intent: 'moles' },
  // units
  { text: 'переведи 250 мл в литры', intent: 'units' },
  { text: 'сколько грамм в 2,5 кг', intent: 'units' },
  { text: '300 кельвинов в цельсии', intent: 'units' },
  { text: 'convert 1500 ml to liters', intent: 'units' },
  { text: '2 kg necha gramm', intent: 'units' },
  // problem
  { text: 'реши задачу: 10 г соли растворили в 90 г воды найди массовую долю', intent: 'problem' },
  { text: 'какой объём водорода выделится при растворении 13 г цинка в соляной кислоте', intent: 'problem' },
  { text: 'помоги с задачей на массовую долю', intent: 'problem' },
  { text: 'найди массовую долю кислорода в CO2', intent: 'problem' },
  { text: 'what mass of CaO forms from 100 g CaCO3', intent: 'problem' },
  { text: '20 g NaOH 80 g suvda eritildi massa ulushini toping', intent: 'problem' },
  // reaction_products
  { text: 'что будет если натрий бросить в воду', intent: 'reaction_products' },
  { text: 'NaOH + HCl = ?', intent: 'reaction_products' },
  { text: 'что образуется при горении магния', intent: 'reaction_products' },
  { text: 'с чем реагирует серная кислота', intent: 'reaction_products' },
  { text: 'what forms when zinc reacts with hydrochloric acid', intent: 'reaction_products' },
  { text: 'Zn + HCl → nima hosil bo‘ladi', intent: 'reaction_products' },
  // balance
  { text: 'уравняй Al + O2 → Al2O3', intent: 'balance' },
  { text: 'расставь коэфициенты Fe + Cl2 = FeCl3', intent: 'balance' },
  { text: 'помоги уравнять реакцию горения метана', intent: 'balance' },
  { text: 'balance H2 + O2 → H2O', intent: 'balance' },
  { text: 'Na + Cl2 = NaCl tenglashtiring', intent: 'balance' },
  // element_info
  { text: 'расскажи про натрий', intent: 'element_info' },
  { text: 'сколько протонов у кислорода', intent: 'element_info' },
  { text: 'в какой группе находится железо', intent: 'element_info' },
  { text: 'строение атома хлора', intent: 'element_info' },
  { text: 'tell me about calcium', intent: 'element_info' },
  { text: 'uglerod haqida gapirib bering', intent: 'element_info' },
  // compound_info
  { text: 'расскажи про серную кислоту', intent: 'compound_info' },
  { text: 'свойства поваренной соли', intent: 'compound_info' },
  { text: 'где применяют аммиак', intent: 'compound_info' },
  { text: 'растворяется ли мел в воде', intent: 'compound_info' },
  { text: 'properties of sodium hydroxide', intent: 'compound_info' },
  { text: 'ammiak qayerda ishlatiladi', intent: 'compound_info' },
  // exam_me
  { text: 'проверь меня по оксидам', intent: 'exam_me' },
  { text: 'задай мне вопросик', intent: 'exam_me' },
  { text: 'давай тест по кислотам', intent: 'exam_me' },
  { text: 'quiz me on acids', intent: 'exam_me' },
  { text: 'menga savol bering', intent: 'exam_me' },
  // simpler
  { text: 'объясни попроще плиз', intent: 'simpler' },
  { text: 'я ничего не понял', intent: 'simpler' },
  { text: 'сложно, давай проще', intent: 'simpler' },
  { text: 'can you explain it more simply', intent: 'simpler' },
  { text: 'soddaroq tushuntirib bering', intent: 'simpler' },
  // more_detail
  { text: 'а подробнее?', intent: 'more_detail' },
  { text: 'расскажи поподробнее про соли', intent: 'more_detail' },
  { text: 'давай глубже', intent: 'more_detail' },
  { text: 'tell me more please', intent: 'more_detail' },
  { text: 'batafsilroq ayting', intent: 'more_detail' },
  // repeat
  { text: 'повтори плз', intent: 'repeat' },
  { text: 'ещё раз скажи', intent: 'repeat' },
  { text: 'что ты сказал? не расслышал', intent: 'repeat' },
  { text: 'say again please', intent: 'repeat' },
  { text: 'yana bir bor takrorlang', intent: 'repeat' },
  // remember
  { text: 'запомни меня зовут Алишер', intent: 'remember' },
  { text: 'я учусь в 9 классе', intent: 'remember' },
  { text: 'запомни что я люблю органику', intent: 'remember' },
  { text: 'remember my name is Anna', intent: 'remember' },
  { text: 'eslab qoling mening ismim Bobur', intent: 'remember' },
  // correction
  { text: 'нет, я спросил что такое моль', intent: 'correction' },
  { text: 'это была шутка', intent: 'correction' },
  { text: 'я не это спрашивал, я про валентность', intent: 'correction' },
  { text: 'no i meant sodium', intent: 'correction' },
  { text: 'yo‘q men boshqa narsani so‘radim', intent: 'correction' },
  // feedback_pos
  { text: 'отлично, теперь понятно', intent: 'feedback_pos' },
  { text: 'класс спасибо понял', intent: 'feedback_pos' },
  { text: 'да именно так', intent: 'feedback_pos' },
  { text: 'great, got it', intent: 'feedback_pos' },
  { text: 'zo‘r, tushundim', intent: 'feedback_pos' },
  // feedback_neg
  { text: 'ты неправильно объяснил', intent: 'feedback_neg' },
  { text: 'это не ответ на мой вопрос', intent: 'feedback_neg' },
  { text: 'слишком длинно и непонятно', intent: 'feedback_neg' },
  { text: 'wrong answer', intent: 'feedback_neg' },
  { text: 'bu noto‘g‘ri javob', intent: 'feedback_neg' },
  // homework_help
  { text: 'помоги с домашкой по химии', intent: 'homework_help' },
  { text: 'задали параграф про кислоты, помоги', intent: 'homework_help' },
  { text: 'не могу сделать номер 5 по оксидам', intent: 'homework_help' },
  { text: 'help me with my chemistry homework', intent: 'homework_help' },
  { text: 'uy vazifasiga yordam bering kimyodan', intent: 'homework_help' },
  // lab_safety
  { text: 'что делать если кислота попала на руку', intent: 'lab_safety' },
  { text: 'правила техники безопасности в лаборатории', intent: 'lab_safety' },
  { text: 'можно ли нюхать хлор', intent: 'lab_safety' },
  { text: 'how to dilute acid safely', intent: 'lab_safety' },
  { text: 'kislota teriga tushsa nima qilish kerak', intent: 'lab_safety' },
  // encourage
  { text: 'я устал от химии', intent: 'encourage' },
  { text: 'у меня ничего не получается', intent: 'encourage' },
  { text: 'я тупой наверное', intent: 'encourage' },
  { text: 'боюсь завалить экзамен', intent: 'encourage' },
  { text: 'i give up, too hard', intent: 'encourage' },
  { text: 'menga juda qiyin, charchadim', intent: 'encourage' },
]
